/** M38.33 经论++ v33 精修第二十三轮 — 基督教灵修深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'john-cross-dark-night', title: '灵魂的黑夜', titleEn: 'Dark Night of the Soul', author: '十字若望', era: '16世纪', ring: 3, categorySlug: 'christianity', summary: '十字若望描述灵魂经过感官与心灵双重黑夜以达至与神合一的神秘之路。', significance: '基督教密契神学代表作,与大德兰齐名。', difficulty: 5, oxStageMin: 7, oxStageMax: 10, readingMins: 60, tags: ['加尔默罗', '神秘主义', '十字若望', '黑夜'], sortOrder: 700,
    chapters: [{ chapterNo: 1, title: '感官的黑夜', originalText: '灵魂要达到神的结合,必须先穿越感官的黑夜,放下一切对受造物的贪恋。这黑夜对灵魂而言是苦涩的,却是甘美的,因为它引向光明。', commentary: '神秘主义认为,破除外物贪恋是与神合一的必经之路。企业家的"黑夜"即放弃对数字与掌声的依赖。', practiceHint: '今日关闭所有通知3小时,体验被"剥离"的不适感。' }] },
  { slug: 'teresa-avila-autobiography', title: '圣德兰自传', titleEn: 'Life of Saint Teresa of Avila', author: '大德兰', era: '1565', ring: 3, categorySlug: 'christianity', summary: '西班牙加尔默罗会改革者大德兰亲笔自传,详述灵修经验与神秘恩赐。', significance: '基督教灵修经典,大德兰1970年被宣为教会圣师。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 90, tags: ['加尔默罗', '大德兰', '祈祷', '自传'], sortOrder: 701,
    chapters: [{ chapterNo: 1, title: '默观祈祷的四境', originalText: '我理解默观祈祷有四个阶段,如同园丁灌溉花园:第一阶段用水桶汲水(努力祈祷),第二阶段用水车(轻省),第三阶段是溪流(更轻省),第四阶段则是天降甘霖(纯粹恩宠)。', commentary: '祈祷的进阶由"用力"到"放手受恩"。领导力亦然:初期亲力亲为,成熟后如天降甘霖。', practiceHint: '今日找一件平时"用力做"的事,尝试完全委派,观察结果。' }] },
  { slug: 'eckhart-sermons', title: '埃克哈特讲道集', titleEn: 'Meister Eckhart Sermons', author: '迈斯特·埃克哈特', era: '14世纪', ring: 3, categorySlug: 'christianity', summary: '德国神秘主义神学家埃克哈特的德语讲道集,论神性、空无、灵魂之火花。', significance: '基督教神秘主义巅峰,影响海德格尔、铃木大拙及新时代运动。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 70, tags: ['埃克哈特', '德国神秘', '空无', '灵火'], sortOrder: 702,
    chapters: [{ chapterNo: 1, title: '灵魂中的上帝之火花', originalText: '在灵魂中有一点未受造、也不能受造之物,那就是理智,若整个灵魂都是这个,它便是未受造的、不能受造的。这是灵魂中神性的火花。', commentary: '埃克哈特指灵魂最深处有"神性火花"与上帝同质。企业家的"初心"即是这火花。', practiceHint: '今日静心15分钟,寻找你内心不随境变的"火花"。' }] },
  { slug: 'thomas-kempis-imitation', title: '效法基督', titleEn: 'The Imitation of Christ', author: '托马斯·肯培斯', era: '1418', ring: 3, categorySlug: 'christianity', summary: '肯培斯以谦卑为核心撰写的灵修小书,四卷,是继《圣经》之后基督教读者最多的书。', significance: '基督教灵修史上最受欢迎书籍,被译成50余种语言。', difficulty: 3, oxStageMin: 3, oxStageMax: 10, readingMins: 70, tags: ['效法基督', '谦卑', '灵修', '肯培斯'], sortOrder: 703,
    chapters: [{ chapterNo: 1, title: '论谦卑地省察自己', originalText: '人人都渴望知识,但若没有对神的敬畏,这知识又有何益?一个乡间谦卑敬神的农夫,胜过学富五车却骄傲的学者。真正认识自己的人,必在自己眼中卑微,也不以他人的称赞为喜。', commentary: '谦卑是一切美德的根。领导者越有地位越要省察自己的渺小,否则知识反成毒药。', practiceHint: '今日当众承认一个自己不懂的专业问题,请团队成员解释。' }] },
  { slug: 'bonhoeffer-cost-discipleship', title: '追随基督', titleEn: 'The Cost of Discipleship', author: '潘霍华', era: '1937', ring: 3, categorySlug: 'christianity', summary: '潘霍华在纳粹时期所写,批判"廉价恩典",呼吁作门徒必须付出代价。', significance: '20世纪最有影响的基督教伦理著作之一,潘霍华为信仰殉道。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 90, tags: ['潘霍华', '门徒', '代价', '廉价恩典'], sortOrder: 704,
    chapters: [{ chapterNo: 1, title: '廉价的恩典', originalText: '廉价恩典是我们教会的致命伤。廉价恩典是赦罪而无悔改,是洗礼而无教会纪律,是圣餐而无认罪,是赦免而无个人的告白。廉价恩典是无需作门徒的恩典。', commentary: '无需付出代价的"好处"终将腐蚀根本。企业的"廉价忠诚"亦然:只要高薪不要文化。', practiceHint: '今日思考公司一项"廉价福利",它是否让员工逃避了更重要的承诺?' }] },
  { slug: 'augustine-city-of-god', title: '上帝之城', titleEn: 'City of God', author: '奥古斯丁', era: '413-426', ring: 3, categorySlug: 'christianity', summary: '奥古斯丁22卷巨著,回应罗马陷落后对基督教的指责,构建"上帝之城"与"地上之城"的二元历史哲学。', significance: '西方政治神学奠基之作,中世纪政治哲学核心文本。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 150, tags: ['奥古斯丁', '政治神学', '二城说', '历史哲学'], sortOrder: 705,
    chapters: [{ chapterNo: 1, title: '两种爱造成两种城', originalText: '两种爱造成两种城:自爱而藐视神的,造成了地上之城;爱神而藐视自己的,造成了上帝之城。前者在自己身上荣耀,后者在主里荣耀。', commentary: '两种城市的根本差别在"爱何者"。企业亦有"自爱"(利润至上)与"爱使命"(荣神益人)两种。', practiceHint: '今日检视近10个决策,大多数属于"自爱"还是"爱使命"?' }] },
  { slug: 'francis-assisi-canticle', title: '太阳歌', titleEn: 'Canticle of the Sun', author: '亚西西的方济各', era: '1224', ring: 3, categorySlug: 'christianity', summary: '方济各在双目失明时所作的意大利语赞诗,赞美太阳、月亮、风水、火、大地与死亡,是意大利文学第一首诗。', significance: '意大利文学开篇之作,生态神学的源头。', difficulty: 2, oxStageMin: 3, oxStageMax: 10, readingMins: 10, tags: ['方济各', '生态', '赞美', '自然'], sortOrder: 706,
    chapters: [{ chapterNo: 1, title: '赞美诸造物', originalText: '至高、全能、美善的主,一切赞美、荣耀、尊崇都归于祢。愿祢藉所有的造物被赞美,尤其是太阳弟兄,他带来白昼,也把光赐给我们。愿祢因我姐妹月亮和众星被赞美。愿祢因风弟兄和空气被赞美。愿祢因水姐妹被赞美,她是如此有用、谦卑、宝贵、纯洁。', commentary: '视万物如兄弟姐妹是生态良知的源头。企业若视客户/员工/供应商如家人,自然生出慈悲。', practiceHint: '今日选3个常忽略的物(电脑/椅子/杯子),默默感谢它们。' }] },
  { slug: 'chambers-utmost-for-highest', title: '竭诚为主', titleEn: 'My Utmost for His Highest', author: '章伯斯', era: '1935', ring: 3, categorySlug: 'christianity', summary: '章伯斯365则灵修短讲,妻子记录出版,是20世纪销量最高的基督教灵修日课。', significance: '英语世界基督徒灵修日课,累计销量超1300万册。', difficulty: 3, oxStageMin: 3, oxStageMax: 10, readingMins: 60, tags: ['章伯斯', '灵修日课', '献身', '竭诚'], sortOrder: 707,
    chapters: [{ chapterNo: 1, title: '有一件事值得竭尽所能', originalText: '有一件事值得你竭尽所能,那就是认识神。若神让你经历苦难,不要问"为什么",要问"祂要我从中学什么"。不要为明天忧虑,今日的竭诚就是明日的恩典。', commentary: '专注于"认识"而非"解释",是信仰与智慧的分水岭。领导者的成熟标志是停止追问"为什么"。', practiceHint: '今日对一件未如愿的事,停止问"为什么",改问"我从中学到什么"。' }] },
  { slug: 'nouwen-return-prodigal', title: '浪子回头', titleEn: 'The Return of the Prodigal Son', author: '卢云', era: '1992', ring: 3, categorySlug: 'christianity', summary: '卢云对着林布兰《浪子回头》画作三年默想而成,从小儿子、大儿子、父亲三重视角反思灵修。', significance: '当代最受欢迎的灵修经典之一,卢云的代表作。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 60, tags: ['卢云', '浪子', '灵修', '林布兰'], sortOrder: 708,
    chapters: [{ chapterNo: 1, title: '成为父亲', originalText: '灵修生活最后的召唤,不是成为那个悔改的小儿子,也不是那个愤怒的大儿子,而是成为那位父亲——那个静静等候、永远原谅的人。', commentary: '灵修终局是从"被拥抱的人"变成"拥抱别人的人"。企业家的成熟也是从被栽培到栽培人。', practiceHint: '本周找一位员工,像"父亲"一样听他诉说10分钟,不评判不建议。' }] },
  { slug: 'lewis-mere-christianity', title: '返璞归真', titleEn: 'Mere Christianity', author: 'C.S.路易斯', era: '1952', ring: 3, categorySlug: 'christianity', summary: '路易斯BBC广播讲稿结集,以理性为基础论证基督信仰核心,是20世纪护教学代表作。', significance: '现代基督教理性护教典范,影响无数知识分子信主。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 80, tags: ['路易斯', '护教学', '理性', '基要'], sortOrder: 709,
    chapters: [{ chapterNo: 1, title: '道德律的证据', originalText: '人类所有争吵背后,都预设了一个"对错"的标准。两人争论时不说"我就是想要",而说"这不公平"——这就是道德律存在的证据。若无超越的律,何来公平不公平?', commentary: '道德争论本身就是"普世道德律"的存在证据。企业冲突亦然:总要诉诸一个更高原则。', practiceHint: '今日记录一次同事冲突,双方诉诸了什么"公平"标准?' }] },
];

runScripturePatch('M38.33 经论++ v33 精修第二十三轮 — 基督教灵修深化', SC);
