/** M38.36 经论++ v36 精修第二十六轮 — 印度教吠檀多深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'isha-upanishad', title: '伊莎奥义书', titleEn: 'Isha Upanishad', author: '古印度圣贤', era: '约公元前800年', ring: 3, categorySlug: 'hinduism', summary: '奥义书中最短之一,18颂,以"神居于万物之中"立说,融合行动与智慧之道。', significance: '吠陀诸奥义书之首,甘地日诵此经。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 15, tags: ['奥义书', '伊莎', '甘地', '吠檀多'], sortOrder: 1000,
    chapters: [{ chapterNo: 1, title: '放下而享受', originalText: '万物运行,皆由神居。应当放下而享受之,不可贪图,因所贪乃他人之财。如此行事者,可盼百岁而无忧,唯此一途,无别道矣。', commentary: '享受但不执着——吠檀多的核心智慧。企业家应享受财富流过而不占有。', practiceHint: '今日享受一顿丰盛午餐,不拍照不发朋友圈,纯粹享用后让它过去。' }] },
  { slug: 'katha-upanishad', title: '卡塔奥义书', titleEn: 'Katha Upanishad', author: '古印度圣贤', era: '约公元前600年', ring: 3, categorySlug: 'hinduism', summary: '纳奇凯达少年在死神阎摩处求"死后之谜"的对话,以战车比喻身心,是瑜伽哲学源头。', significance: '奥义书叙事典范,战车比喻为《薄伽梵歌》所承。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 40, tags: ['奥义书', '卡塔', '战车', '阎摩'], sortOrder: 1001,
    chapters: [{ chapterNo: 1, title: '战车之喻', originalText: '知自我为车主,身为战车,智慧为御者,意为缰绳。五根为马,五境为所行之路。智慧之车若驾驭得当,则到达毗湿奴最高处。', commentary: '身(战车)、意(缰绳)、智(御者)、我(车主)——瑜伽心理学的完整比喻。', practiceHint: '今日静坐时想象自己是"车主",观察各部门(马)在奔跑什么方向。' }] },
  { slug: 'mundaka-upanishad', title: '剃发奥义书', titleEn: 'Mundaka Upanishad', author: '古印度圣贤', era: '约公元前500年', ring: 3, categorySlug: 'hinduism', summary: '三章论两种知识(高级/低级)与梵我合一之道,印度国徽"唯真理胜利"出自此经。', significance: '吠檀多不二论重要经典,被印度独立运动奉为圣言。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 30, tags: ['奥义书', '剃发', '真理胜利', '不二'], sortOrder: 1002,
    chapters: [{ chapterNo: 1, title: '唯真理胜利', originalText: '唯真理胜利,非虚伪。真理之路,诸神所行,圣者因此达至最高之所。', commentary: 'Satyameva Jayate——唯真理胜利。企业长期成功的唯一秘诀就是真实不欺。', practiceHint: '今日检视产品宣传,有无一句夸大之词?立即修正。' }] },
  { slug: 'taittiriya-upanishad', title: '泰帝利耶奥义书', titleEn: 'Taittiriya Upanishad', author: '古印度圣贤', era: '约公元前600年', ring: 3, categorySlug: 'hinduism', summary: '三篇论教导,含著名"五藏论"(食/气/意/识/乐),描述人与梵之层次结构。', significance: '吠陀教育学与人体结构论经典,瑜伽哲学基础。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 35, tags: ['奥义书', '五藏', '教导', '梵我'], sortOrder: 1003,
    chapters: [{ chapterNo: 1, title: '五藏层次', originalText: '人有五藏:食所成藏(身体),气所成藏(呼吸),意所成藏(心念),识所成藏(智慧),乐所成藏(喜悦)。最深处是无上梵,即存在、意识、喜悦。', commentary: '从物质到心灵有五层。企业家的内在成长也是从体力→精力→思维→智慧→喜悦。', practiceHint: '今日评估自己在"五藏"哪一层疲惫,针对性调养。' }] },
  { slug: 'shankara-aparokshanubhuti', title: '直接觉悟', titleEn: 'Aparokshanubhuti', author: '商羯罗', era: '8世纪', ring: 3, categorySlug: 'hinduism', summary: '商羯罗入门小著,144颂,以简明偈颂阐述不二吠檀多直接觉悟之道。', significance: '不二论入门捷径,当代印度修行者必读。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 40, tags: ['商羯罗', '不二', '直接觉悟', '吠檀多'], sortOrder: 1004,
    chapters: [{ chapterNo: 1, title: '探问"我是谁"', originalText: '探问"我是谁"是解脱之道。身体不是我,心念不是我,智慧不是我——那么我是谁?如此层层深入,直到剩下那不可否定的"觉知"本身。', commentary: '商羯罗核心法门是"探问我是谁"。企业家的"自我认同"若太依附头衔,就不是真的"我"。', practiceHint: '今日静坐问3遍"我是谁?",不找答案,感受问题本身。' }] },
  { slug: 'vivekananda-karma-yoga', title: '业瑜伽', titleEn: 'Karma Yoga', author: '辨喜', era: '1896', ring: 3, categorySlug: 'hinduism', summary: '辨喜在纽约的演讲集,阐发"无执行动"的瑜伽之道,以西方人能懂的方式表达吠檀多。', significance: '印度教现代化的核心著作,促进东西方思想交流。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 60, tags: ['辨喜', '业瑜伽', '无执行动', '西方传'], sortOrder: 1005,
    chapters: [{ chapterNo: 1, title: '为行动而行动', originalText: '真正的伟大就是为行动而行动,不问收获。做事只为事情本身值得做,不是因为别人看见。这样工作不再是枷锁,而是解脱。', commentary: '无执行动是业瑜伽精髓。企业家做事若能"不问收获",反而收获最大。', practiceHint: '今日做一件完全不求回报的事,不让任何人知道。' }] },
  { slug: 'aurobindo-life-divine', title: '神圣人生论', titleEn: 'The Life Divine', author: '室利·奥罗宾多', era: '1914-1919', ring: 3, categorySlug: 'hinduism', summary: '奥罗宾多整合瑜伽哲学巨著,主张"整体进化",是20世纪印度哲学最恢弘的综合。', significance: '现代吠檀多最系统的哲学论证,宇宙进化论代表作。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 180, tags: ['奥罗宾多', '整体瑜伽', '进化', '超心智'], sortOrder: 1006,
    chapters: [{ chapterNo: 1, title: '神圣进化', originalText: '宇宙不是静止的神的创造,而是神在时间中的自我进化。物质进化为生命,生命进化为心智,心智将进化为超心智。人是这一进化的中转站,不是终点。', commentary: '进化尚未完成,人是过渡。企业家的使命若接上"宇宙进化",格局即刻不同。', practiceHint: '今日写下公司对"人类进化"能做的最小贡献是什么?' }] },
  { slug: 'ramana-upadesa-saram', title: '教导精华', titleEn: 'Upadesa Saram', author: '室利·拉玛那·马哈希', era: '1927', ring: 3, categorySlug: 'hinduism', summary: '拉玛那·马哈希以30颂阐述"自我探询"核心法门,是现代不二论最精炼之作。', significance: '20世纪印度最伟大圣者代表作,西方灵性经典。', difficulty: 3, oxStageMin: 5, oxStageMax: 10, readingMins: 20, tags: ['拉玛那', '自我探询', '不二', '精华'], sortOrder: 1007,
    chapters: [{ chapterNo: 1, title: '探问"我"的根源', originalText: '心念此起彼落,皆依"我念"而生。寻找"我"从何而来,心念自然止息,自我即显。此外无他道。', commentary: '拉玛那的心法:一切心念皆以"我"为根,追问"我"之源头即为修行。', practiceHint: '今日一个烦恼念头起,问"这个烦恼是谁的?",观察念头的反应。' }] },
  { slug: 'krishnamurti-first-last-freedom', title: '最初与最终的自由', titleEn: 'The First and Last Freedom', author: '克里希那穆提', era: '1954', ring: 3, categorySlug: 'hinduism', summary: '克氏首部系统论著,论自由不在宗教组织中,而在对自我认识的即刻觉照。', significance: '20世纪新印度哲学代表作,打破传统师徒体制。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 100, tags: ['克里希那穆提', '自由', '自我认识', '觉照'], sortOrder: 1008,
    chapters: [{ chapterNo: 1, title: '真理是无路之地', originalText: '真理是一片无路之地。你无法通过任何组织、任何信条、任何教条、任何牧师或仪式到达它。不可通过任何哲学知识或心理技术到达它。你必须通过关系之镜,通过对自己思想内容的理解,通过观察——而非智力分析——来发现它。', commentary: '真理不在权威中,而在对自身关系的觉照中。企业战略亦然:不在咨询报告,在自观。', practiceHint: '今日不接受任何"专家建议",就自己的观察作一个决定。' }] },
  { slug: 'nisargadatta-i-am-that', title: '我是那', titleEn: 'I Am That', author: '尼萨迦达塔·马哈拉杰', era: '1973', ring: 3, categorySlug: 'hinduism', summary: '孟买吸烟店主尼萨迦达塔与访客的问答集,直指"我是那"(I Am That)之根本体验。', significance: '现代不二论最受推崇经典之一,影响西方灵性运动。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 150, tags: ['尼萨迦达塔', '我是那', '不二', '问答'], sortOrder: 1009,
    chapters: [{ chapterNo: 1, title: '安住于"我在"', originalText: '只要安住于"我在"的感觉中。这感觉在所有经验之前,是最切近的事实。所有问题都围绕着"我在"转。与"我在"相处足够久,它会向你显露自己的真相。', commentary: '比"我是谁"更根本的是"我在"——纯粹的存在感。这是一切战略的起点。', practiceHint: '今日连续3小时,不说"我想/我要/我做",只觉察"我在"。' }] },
];

runScripturePatch('M38.36 经论++ v36 精修第二十六轮 — 印度教吠檀多深化', SC);
