/** M38.38 经论++ v38 精修第二十八轮 — 小传统补强 (锡克/神道/巴哈伊/原住民) 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'guru-gobind-jaap-sahib', title: '十祖赞真经', titleEn: 'Jaap Sahib', author: '戈宾德·辛格', era: '17世纪末', ring: 3, categorySlug: 'sikhism', summary: '锡克第十位古鲁戈宾德·辛格所作199节赞美诗,以多种语言描述神之属性,晨祷经典。', significance: '锡克教五大祈祷文之一,每日清晨必诵。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 45, tags: ['戈宾德·辛格', '十祖', '晨祷', '赞真经'], sortOrder: 1200,
    chapters: [{ chapterNo: 1, title: '千名的神', originalText: '祢无形无相,亦无种姓;祢无父无母,亦无眷属;祢无恐惧无敌意,亦无束缚;祢无名无形,永恒唯一。我向至尊者顶礼,向那光明之源顶礼。', commentary: '神超越一切形相与关系,是纯粹的"存在"。企业家的使命也应如此:超越个人关系,归于本质。', practiceHint: '今日祈祷或静坐时不求任何具体事,只认可"存在"本身。' }] },
  { slug: 'guru-angad-salok', title: '二祖萨洛克', titleEn: 'Salok of Guru Angad', author: '古鲁·安格德', era: '16世纪', ring: 3, categorySlug: 'sikhism', summary: '锡克第二位古鲁安格德的短诗(Salok),简洁有力地阐发服侍与谦卑之道。', significance: '锡克教古鲁格兰特·萨希卜重要部分,传承那那克精神。', difficulty: 3, oxStageMin: 3, oxStageMax: 10, readingMins: 30, tags: ['安格德', '萨洛克', '谦卑', '服侍'], sortOrder: 1201,
    chapters: [{ chapterNo: 1, title: '服侍之道', originalText: '若要尝神之甘美,须尝服侍之苦。不服侍他人者,永远不知何为真主。真正的古鲁,就是那个愿意成为众人仆人的人。', commentary: '领导即服侍——锡克教核心。真正的CEO不是被伺候的人,是伺候团队的人。', practiceHint: '今日亲自为团队端一次咖啡或泡一次茶。' }] },
  { slug: 'kojiki', title: '古事记', titleEn: 'Kojiki', author: '太安万侣 编', era: '712', ring: 3, categorySlug: 'shinto', summary: '日本现存最古史书,三卷,记神代与初代至推古天皇的神话传说,神道教最重要经典。', significance: '日本文学第一书,神道神学原典,本居宣长倾毕生精力注解。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 120, tags: ['古事记', '神代', '太安万侣', '神道'], sortOrder: 1202,
    chapters: [{ chapterNo: 1, title: '天地初发', originalText: '天地初发之时,于高天原成神名:天之御中主神。次,高御产巣日神。次,神产巣日神。此三柱神者,并独神成坐而,隐身也。', commentary: '神道宇宙生成论以"产巣日"(生成之灵)为核心。企业亦需认识"生成之灵"——初心与动势。', practiceHint: '今日回忆创业第一天的初心,写一句贴在桌边。' }] },
  { slug: 'nihon-shoki-jindai', title: '日本书纪·神代卷', titleEn: 'Nihon Shoki Age of Gods', author: '舍人亲王 编', era: '720', ring: 3, categorySlug: 'shinto', summary: '日本第二部正史《日本书纪》前两卷为神代,记天地开辟至神武天皇事,为神道另一根本经典。', significance: '与《古事记》并称神道双璧,记同一神话而视角不同。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 100, tags: ['日本书纪', '神代', '舍人亲王', '神话'], sortOrder: 1203,
    chapters: [{ chapterNo: 1, title: '伊邪那岐、伊邪那美', originalText: '伊邪那岐命、伊邪那美命二神,立于天浮桥上,以天之沼矛指下而搅之。盐水隐顺声,矛拔时,其矛末垂滴之盐,积累成岛,名曰淤能碁吕岛。', commentary: '创世神话以"搅动"为起源。企业的创立亦是对"混沌"的搅动,凝结成"岛"(产品)。', practiceHint: '今日回想你"搅动"出来的第一个产品,它当时是如何凝聚的?' }] },
  { slug: 'motoori-naobi-no-mitama', title: '直毘灵', titleEn: 'Direct Spirit', author: '本居宣长', era: '1771', ring: 3, categorySlug: 'shinto', summary: '本居宣长为《古事记传》作的序论,阐发"古之道"(ほうい)即日本原初神道精神。', significance: '日本国学派纲领,为明治维新神道复兴思想源头。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 50, tags: ['本居宣长', '国学', '直毘灵', '古道'], sortOrder: 1204,
    chapters: [{ chapterNo: 1, title: '古道的心', originalText: '古之道者,非儒非佛,乃神之所为。神心率直,不加造作,吉凶祸福皆神意,人当敬而顺之。若以理智分别,则失古道本味。', commentary: '不以知识分别,回到直觉之心。企业文化若太"理论化",反而失去灵魂。', practiceHint: '今日一个决策前关掉一切数据工具,凭直觉判断一次。' }] },
  { slug: 'bahaullah-book-certitude', title: '确信经', titleEn: 'Kitab-i-Iqan', author: '巴哈欧拉', era: '1861', ring: 3, categorySlug: 'bahai', summary: '巴哈欧拉回应叔父提问所著,200余页,是巴哈伊信仰最重要的神学著作。', significance: '巴哈伊信仰核心经典,奠定宗教演进论与先知连续启示思想。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 100, tags: ['巴哈欧拉', '确信', '神学', '启示'], sortOrder: 1205,
    chapters: [{ chapterNo: 1, title: '进步的启示', originalText: '神的启示如同太阳,以不同的名字和光芒重复升起。摩西、佛陀、耶稣、穆罕默德、巴孛、巴哈欧拉——都是同一位神的太阳,在不同时代为不同人群升起。', commentary: '连续启示论认为所有大先知同源。企业的文化融合亦然:不是取代,是呈现同一真理的不同面。', practiceHint: '今日在公司召开一场"文化互融"会,邀请不同背景同事分享信念。' }] },
  { slug: 'abdul-baha-paris-talks', title: '阿博都巴哈·巴黎演讲', titleEn: 'Paris Talks', author: '阿博都巴哈', era: '1911', ring: 3, categorySlug: 'bahai', summary: '阿博都巴哈访问巴黎期间的57次演讲,面向西方听众阐发巴哈伊信仰。', significance: '巴哈伊向西方传播的里程碑,人类一家思想的经典表达。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 90, tags: ['阿博都巴哈', '巴黎演讲', '一家', '西传'], sortOrder: 1206,
    chapters: [{ chapterNo: 1, title: '人类一家', originalText: '人类是一座花园,各民族是其中不同的花朵。若所有花都是同一颜色,花园便失去魅力。多样性之美正是宇宙的设计。你们要如兄弟姐妹,爱那不同于你的人,胜过爱与你相同的人。', commentary: '多样即美。企业多元化的深层意义不是合规,是美学。', practiceHint: '今日主动与一位和自己背景最不同的同事共进午餐。' }] },
  { slug: 'black-elk-speaks', title: '黑麋鹿说', titleEn: 'Black Elk Speaks', author: '黑麋鹿 (约翰·尼哈特 记录)', era: '1932', ring: 3, categorySlug: 'indigenous', summary: '苏族圣者黑麋鹿口述其一生与神圣异象的传记,由美国诗人尼哈特记录,是原住民灵性经典。', significance: '美洲原住民灵性文学的最高代表作,联合国原住民权利宣言思想源头。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 100, tags: ['苏族', '黑麋鹿', '异象', '原住民'], sortOrder: 1207,
    chapters: [{ chapterNo: 1, title: '圆圈中的一切', originalText: '万物都在圆圈中运行。天是圆的,大地是圆的如球,风在最强时打转形成旋风。鸟的巢是圆的,因为它们与我们同属一圆。太阳和月亮圆圆升起落下,四季构成一个大圆永远回到起点。', commentary: '原住民智慧的核心是"圆"——循环、完整、无边。企业思维亦可"圆圈化":始于初心,终于初心。', practiceHint: '今日画一个圆,写上公司一年内最重要的事,感受它的完整。' }] },
  { slug: 'seven-arrows-cheyenne', title: '七箭(夏安族)', titleEn: 'Seven Arrows', author: '海米约斯特·风暴', era: '1972', ring: 3, categorySlug: 'indigenous', summary: '北美夏安族作家以传统故事与药轮教学阐发原住民智慧,为现代原住民哲学代表作。', significance: '连接传统部落智慧与现代读者的经典,药轮教学普及之作。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 120, tags: ['夏安族', '药轮', '七箭', '部落'], sortOrder: 1208,
    chapters: [{ chapterNo: 1, title: '药轮四方', originalText: '药轮有四方:东方是新开始,智慧从此升起;南方是纯真,像孩子一样信任;西方是内省,进入自己的影子;北方是智慧,白发长者的教导。每个人一生都要走完四方。', commentary: '四方对应人生四阶段。企业领导者同样需经历开始/信任/反省/智慧四境。', practiceHint: '今日问自己:我当前在"药轮"哪个方位?' }] },
  { slug: 'maori-whakatauki', title: '毛利谚语集', titleEn: 'Maori Whakataukī', author: '毛利祖先(传)', era: '前殖民期', ring: 3, categorySlug: 'indigenous', summary: '新西兰毛利族传统谚语集,浓缩部落智慧于短句,是毛利教育核心工具。', significance: '大洋洲原住民口传智慧代表,新西兰正式文化财产。', difficulty: 2, oxStageMin: 3, oxStageMax: 10, readingMins: 30, tags: ['毛利', '谚语', '大洋洲', '口传'], sortOrder: 1209,
    chapters: [{ chapterNo: 1, title: '世上最重要', originalText: 'He aha te mea nui o te ao? He tangata, he tangata, he tangata. (世上最重要的是什么?是人,是人,是人。)', commentary: '毛利最著名谚语,三次重复"是人"——没有人就没有一切。企业的核心也永远是人。', practiceHint: '今日与3位同事各交谈10分钟,只谈他们,不谈业务。' }] },
];

runScripturePatch('M38.38 经论++ v38 精修第二十八轮 — 小传统补强', SC);
