/** M38.37 经论++ v37 精修第二十七轮 — 藏传佛教深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'gyalse-tokme-37', title: '佛子行三十七颂', titleEn: '37 Practices of a Bodhisattva', author: '无著贤', era: '14世纪', ring: 3, categorySlug: 'tibetan', summary: '西藏无著贤(托美桑波)所作37颂,以精简诗偈总结菩萨修行之道,藏传四大传统共遵。', significance: '藏传佛教菩萨道最普及的修心文,达赖喇嘛常讲。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 30, tags: ['佛子行', '无著贤', '菩萨行', '修心'], sortOrder: 1100,
    chapters: [{ chapterNo: 1, title: '皈依三宝', originalText: '此生幸得暇满船,自他须渡轮回海,故于昼夜不懈怠,闻思修是佛子行。贪恋亲方如水动,嗔憎怨方似火燃,痴昧取舍犹黑暗,抛弃故乡佛子行。', commentary: '暇满人身难得,更须不懈修行。企业家亦然:时间宝贵,不可空耗于贪嗔痴。', practiceHint: '今日起早一小时用于思考"最重要的事",不看手机。' }] },
  { slug: 'lojong-8-verses', title: '修心八颂', titleEn: 'Eight Verses of Training the Mind', author: '朗日塘巴', era: '11世纪', ring: 3, categorySlug: 'tibetan', summary: '噶当派朗日塘巴所作仅8颂的修心法本,教导视一切众生如珍宝、承担他人苦难。', significance: '藏传修心法门最简要文本,达赖喇嘛日诵经典。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 10, tags: ['修心', '八颂', '朗日塘巴', '噶当派'], sortOrder: 1101,
    chapters: [{ chapterNo: 1, title: '视他为珍', originalText: '我于一切有情众,视之尤胜如意宝,愿成究竟利他故,常怀珍爱为最上。随处与谁为伴时,视己较诸众卑劣,从心深处思他众,恒常敬彼为最上。', commentary: '把所有人都看得比自己重要。领导者若能真心如此,团队自然凝聚。', practiceHint: '今日一次会议中,发自内心把话筒让给最少发言的人。' }] },
  { slug: 'tsongkhapa-lamrim-chenmo', title: '菩提道次第广论', titleEn: 'Great Treatise on the Stages of the Path', author: '宗喀巴', era: '1402', ring: 3, categorySlug: 'tibetan', summary: '宗喀巴大师总结阿底峡《菩提道灯论》撰成的格鲁派根本论典,下士/中士/上士三道次第。', significance: '格鲁派修行总纲,藏传佛教系统修行的典范。', difficulty: 5, oxStageMin: 5, oxStageMax: 10, readingMins: 180, tags: ['宗喀巴', '菩提道次第', '格鲁派', '广论'], sortOrder: 1102,
    chapters: [{ chapterNo: 1, title: '暇满人身之义', originalText: '此暇满之身,较如意宝犹为希有。得时又极短促,如电光迅速。若思此而未能引发大利益,则如宝入穷子之手而不能用。', commentary: '人身如闪电之短,如意宝之贵,不用即空过。企业家亦不可空耗生命于无意义的忙碌。', practiceHint: '今日删除30分钟"时间杀手"活动(如刷手机),换为深思一次。' }] },
  { slug: 'gampopa-jewel-ornament', title: '解脱庄严论', titleEn: 'Jewel Ornament of Liberation', author: '冈波巴', era: '12世纪', ring: 3, categorySlug: 'tibetan', summary: '噶举派冈波巴整合噶当派与大手印传承的著作,21章论菩萨道次第,是藏传道次第经典。', significance: '噶举派根本论典,大手印传承融合显密之典范。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 120, tags: ['冈波巴', '解脱庄严', '噶举派', '大手印'], sortOrder: 1103,
    chapters: [{ chapterNo: 1, title: '成佛的因缘', originalText: '成佛有六因:一佛种性为因,二人身为所依,三善知识为缘,四方便为法,五正精进为用,六究竟佛果为报。六因俱全,则成佛可期。', commentary: '六因俱全方能成事。企业成就也需天时(性)、地利(身)、贵人(缘)、方法(法)、努力(进)、目标(果)。', practiceHint: '今日自检:我当前缺的是哪一因?是缺师父还是缺精进?' }] },
  { slug: 'patrul-kunzang-lamai-zhallung', title: '普贤上师言教', titleEn: 'Words of My Perfect Teacher', author: '巴楚仁波切', era: '19世纪', ring: 3, categorySlug: 'tibetan', summary: '宁玛派巴楚仁波切所著大圆满前行引导,详述共同加行与不共加行,是宁玛派前行必学。', significance: '大圆满前行教材典范,西方藏传弟子入门读本。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 90, tags: ['巴楚', '普贤上师言教', '宁玛派', '前行'], sortOrder: 1104,
    chapters: [{ chapterNo: 1, title: '死亡无常', originalText: '死亡决定会来,死时无定。死缘无定,死时除佛法外无一能利益,故当殷重修行。若能深思此一点,则世间琐事自然看淡,佛法自然精进。', commentary: '死亡确定、时间不定——这是最大的"战略倒逼"。企业家直面此点,决策立即清晰。', practiceHint: '今日问自己:若三年后必死,此事还值得做吗?' }] },
  { slug: 'longchenpa-three-cycles', title: '大圆满三休息', titleEn: 'Three Cycles of Resting', author: '龙钦巴', era: '14世纪', ring: 3, categorySlug: 'tibetan', summary: '大圆满祖师龙钦巴(无垢光)三部巨著总称,论心、妄、轮回三境界之自解脱。', significance: '宁玛派大圆满理论巅峰,被誉为"第二位普贤王如来"。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 120, tags: ['龙钦巴', '大圆满', '三休息', '宁玛派'], sortOrder: 1105,
    chapters: [{ chapterNo: 1, title: '心性本净', originalText: '心之本性,本来清净,无需造作。无明生起时,觉性即是解脱。烦恼升起时,本智即是法身。无有所取所舍,故名大圆满。', commentary: '大圆满核心是"本来即是",不加造作。企业管理最高境界亦然:不强制、不塑造,让真实显现。', practiceHint: '今日对某事停止控制3小时,只观察其自然发展。' }] },
  { slug: 'shabkar-autobiography', title: '夏嘎巴自传', titleEn: 'Life of Shabkar', author: '夏嘎·措珠让卓', era: '19世纪', ring: 3, categorySlug: 'tibetan', summary: '西藏大瑜伽士夏嘎巴亲笔自传,记录从普通喇嘛到大圆满成就者的一生修行路。', significance: '藏传佛教最动人的自传之一,融修行故事与歌道于一炉。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 120, tags: ['夏嘎巴', '自传', '瑜伽士', '大圆满'], sortOrder: 1106,
    chapters: [{ chapterNo: 1, title: '山间的歌', originalText: '我这个乞丐瑜伽士,无家无财产。天为帐,地为榻,风为伴,云为衣。众生为我的父母,佛陀为我的导师。我何所需?我何所求?快乐啊快乐!', commentary: '无所有即无所失。企业家若能体验一日"一无所有",便知真正的自由是什么。', practiceHint: '今天只带一张卡和手机出门,不带任何"身份证明物品"半天。' }] },
  { slug: 'milarepa-songs', title: '米拉日巴道歌集', titleEn: 'Songs of Milarepa', author: '米拉日巴', era: '11世纪', ring: 3, categorySlug: 'tibetan', summary: '西藏最著名瑜伽士米拉日巴的道歌集,以即兴诗偈教导弟子,是藏传文学瑰宝。', significance: '藏传佛教最具感染力的修行文学,西方公认的瑜伽诗圣。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 90, tags: ['米拉日巴', '道歌', '噶举派', '瑜伽'], sortOrder: 1107,
    chapters: [{ chapterNo: 1, title: '不修苦行亦不贪', originalText: '不修苦行亦不贪,安住本然任运中。不求名利亦不厌,三门如如皆解脱。食者无食食亦足,坐者无坐坐亦乐,行者无行行亦畅,思者无思思亦净。', commentary: '无为而为,不求不厌。企业家能达此境,工作即休闲,休闲即工作。', practiceHint: '今日工作时提醒自己3次:"就只是做,不加评判"。' }] },
  { slug: 'padmasambhava-natural-liberation', title: '自解脱见', titleEn: 'Self-Liberation through Seeing', author: '莲花生大士', era: '8世纪', ring: 3, categorySlug: 'tibetan', summary: '莲花生大士岩藏法,论见地之自解脱,藏语原名Rigpa Ngotro,直指觉性自显之道。', significance: '宁玛派直指心性根本法本,西方禅修界广为流传。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 60, tags: ['莲花生', '自解脱', '岩藏法', '觉性'], sortOrder: 1108,
    chapters: [{ chapterNo: 1, title: '一心之本性', originalText: '一心之本性:空而觉、觉而明、明而自然。非造作而有,非无明而无。即是而是,非是而非。于此安住,即是解脱。', commentary: '空、觉、明三位一体。企业领导的最高境界:清空预设(空)、清晰觉察(觉)、明智决断(明)。', practiceHint: '今日决策前静心3秒:我的心空吗?觉吗?明吗?' }] },
  { slug: 'dilgo-khyentse-heart-treasure', title: '心宝藏', titleEn: 'Heart Treasure of the Enlightened Ones', author: '顶果钦哲', era: '20世纪', ring: 3, categorySlug: 'tibetan', summary: '顶果钦哲仁波切根据巴楚《证悟自心状态》所作的开示集,精炼大圆满见修行果。', significance: '20世纪宁玛派最伟大上师的代表作,广受西方藏传弟子喜爱。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 80, tags: ['顶果钦哲', '心宝藏', '大圆满', '开示'], sortOrder: 1109,
    chapters: [{ chapterNo: 1, title: '现量安住', originalText: '当念头升起,不跟随,不压抑,只认出它如虚空中的云。云不染空,念不染心。安住于此觉知,一切烦恼自解脱。', commentary: '云不染空的比喻最精彩:念头不损伤心,只要不跟随。企业家面对情绪亦然。', practiceHint: '今日愤怒升起时,想象它是一朵云飘过,不抓不推。' }] },
];

runScripturePatch('M38.37 经论++ v37 精修第二十七轮 — 藏传佛教深化', SC);
