/** M38.32 经论++ v32 精修第二十二轮 — 道家深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'yinfu-jing', title: '阴符经', titleEn: 'Huangdi Yinfu Jing', author: '黄帝(传)', era: '先秦', ring: 3, categorySlug: 'taoism', summary: '黄帝阴符经三百余字,短而精深,为道家修真秘典,李筌注本最著。', significance: '道家第一短经,与《道德经》《清静经》并称道教三大宗经。', difficulty: 5, oxStageMin: 6, oxStageMax: 10, readingMins: 20, tags: ['道家', '阴符', '黄帝', '天机'], sortOrder: 600,
    chapters: [{ chapterNo: 1, title: '观天之道', originalText: '观天之道,执天之行,尽矣。天有五贼,见之者昌。五贼在心,施行于天。宇宙在乎手,万化生乎身。天性,人也;人心,机也。立天之道,以定人也。', commentary: '天道五贼(五行相克)见于心而行于天。企业家观察市场五大矛盾,藏于心而行于市。', practiceHint: '今日找出当前业务的"五大矛盾",写在纸上,暂不评判。' }] },
  { slug: 'qingjing-jing', title: '清静经', titleEn: 'Scripture of Purity and Tranquility', author: '太上老君(传)', era: '唐末', ring: 3, categorySlug: 'taoism', summary: '《太上老君说常清静经》仅六百字,为道教日诵功课之首,言清静之道。', significance: '道教徒每日诵读经典,内丹修炼入门心法。', difficulty: 3, oxStageMin: 3, oxStageMax: 9, readingMins: 15, tags: ['道教', '清静', '太上', '功课'], sortOrder: 601,
    chapters: [{ chapterNo: 1, title: '常清常静', originalText: '大道无形,生育天地;大道无情,运行日月;大道无名,长养万物。......人能常清静,天地悉皆归。夫人神好清,而心扰之;人心好静,而欲牵之。常能遣其欲,而心自静;澄其心,而神自清。', commentary: '清静不是无为,是去欲澄心。企业家想清晰决策必先澄除杂念。', practiceHint: '今晚睡前静坐5分钟,不处理任何事务,让心归静。' }] },
  { slug: 'taishang-ganying-pian', title: '太上感应篇', titleEn: 'Treatise on Response and Retribution', author: '李昌龄(传)', era: '宋', ring: 3, categorySlug: 'taoism', summary: '道教劝善书,首句"祸福无门,惟人自召"深入民间,列善恶诸事,明因果报应。', significance: '道教四大劝善书之首,清代印行超亿册,中国善书典范。', difficulty: 2, oxStageMin: 2, oxStageMax: 10, readingMins: 25, tags: ['劝善', '因果', '感应', '道教'], sortOrder: 602,
    chapters: [{ chapterNo: 1, title: '祸福无门', originalText: '太上曰:祸福无门,惟人自召;善恶之报,如影随形。是以天地有司过之神,依人所犯轻重,以夺人算。算减则贫耗,多逢忧患。', commentary: '祸福皆由自招,非外力给予。企业的运势本质是历史行为的结算。', practiceHint: '今日想象公司"司过之神"正在记录,本周做了哪3件会被"减算"的事?' }] },
  { slug: 'huangting-jing', title: '黄庭经', titleEn: 'Yellow Court Scripture', author: '魏华存(传)', era: '东晋', ring: 3, categorySlug: 'taoism', summary: '上清派存思内景经典,分内景/外景二篇,为道教养生内丹基础典籍。', significance: '上清派根本经典,存思身中诸神,王羲之曾写此经。', difficulty: 5, oxStageMin: 5, oxStageMax: 10, readingMins: 60, tags: ['上清派', '内丹', '存思', '养生'], sortOrder: 603,
    chapters: [{ chapterNo: 1, title: '黄庭内景玉经', originalText: '上清紫霞虚皇前,太上大道玉晨君。闲居蕊珠作七言,散化五形变万神。是为黄庭曰内篇。琴心三叠舞胎仙,九气映明出霄间,神盖童子生紫烟。', commentary: '黄庭为身中之中枢(脾胃),存思此处可"散化五形"。企业"中枢"在中后台,养护之则全身活。', practiceHint: '今日花5分钟审视公司"中后台"(HR/财务/IT),哪个在"积食"?' }] },
  { slug: 'zhouyi-cantong-qi', title: '周易参同契', titleEn: 'Kinship of the Three', author: '魏伯阳', era: '东汉', ring: 3, categorySlug: 'taoism', summary: '魏伯阳以《周易》爻象论内丹修炼,三者(易/黄老/炉火)相通,为"万古丹经王"。', significance: '外丹转内丹枢纽,朱熹化名"崆峒道士邹訢"为之作注。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 80, tags: ['内丹', '周易', '参同', '魏伯阳'], sortOrder: 604,
    chapters: [{ chapterNo: 1, title: '乾坤者易之门户', originalText: '乾坤者,易之门户,众卦之父母。坎离匡郭,运毂正轴。牝牡四卦,以为橐钥。覆冒阴阳之道,犹工御者,准绳墨,执衔辔,正规矩,随轨辙,处中以制外,数在律历纪。', commentary: '乾坤为体,坎离为用。内丹即在心(离)肾(坎)之间运转。企业中"定位"与"执行"亦如此。', practiceHint: '今日确认一件事:定位(心)对不对?执行(身)跟不跟?' }] },
  { slug: 'wuzhen-pian', title: '悟真篇', titleEn: 'Chapters on Awakening to Reality', author: '张伯端(紫阳真人)', era: '北宋 (1075)', ring: 3, categorySlug: 'taoism', summary: '张伯端作诗词九十余首阐述金丹大道,与《参同契》并称南宗双璧。', significance: '道教南宗丹法纲领,后世丹经皆宗此书。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 70, tags: ['南宗', '内丹', '张伯端', '金丹'], sortOrder: 605,
    chapters: [{ chapterNo: 1, title: '不求大道出迷途', originalText: '不求大道出迷途,纵负贤才岂丈夫?百岁光阴石火烁,一生身世水泡浮。只贪利禄求荣显,不顾形容暗悴枯。试问堆金等山岳,无常买得不来无?', commentary: '纵有百亿不能买寿一日。企业家不修"大道"则一切财富如石火水泡。', practiceHint: '今日在日程表上为"修道/读经"划出固定30分钟,如同董事会一样重要。' }] },
  { slug: 'baopuzi-neipian', title: '抱朴子·内篇', titleEn: 'Baopuzi Inner Chapters', author: '葛洪', era: '东晋 (317)', ring: 3, categorySlug: 'taoism', summary: '葛洪著内篇20卷论神仙方药炼丹之术,外篇50卷论儒家治世,为道教第一部系统论著。', significance: '道教理论与方术集大成,英国李约瑟誉为"中国科学史"重要源头。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 100, tags: ['葛洪', '抱朴子', '炼丹', '方术'], sortOrder: 606,
    chapters: [{ chapterNo: 1, title: '畅玄', originalText: '玄者,自然之始祖,而万殊之大宗也。眇眇乎其深也,故称微焉。绵绵乎其远也,故称妙焉。其高则冠盖乎九霄,其旷则笼罩乎八隅。', commentary: '玄为万物本源,深而微、远而妙。企业之"玄"即深藏不露的核心竞争力。', practiceHint: '今日写下公司最深处不可轻易示人的"玄"是什么?' }] },
  { slug: 'zuowang-lun', title: '坐忘论', titleEn: 'Discourse on Sitting in Oblivion', author: '司马承祯', era: '唐 (647-735)', ring: 3, categorySlug: 'taoism', summary: '司马承祯论修道七阶:信敬/断缘/收心/简事/真观/泰定/得道,是道教静坐法的里程碑。', significance: '唐代道教修炼论纲领,为宋元内丹七返九还之源。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 45, tags: ['坐忘', '司马承祯', '上清', '静坐'], sortOrder: 607,
    chapters: [{ chapterNo: 1, title: '断缘', originalText: '断缘者,断有为俗事之缘也。弃事则形不劳,无为则心自安,恬简日就,尘累日薄,迹弥远俗,心弥近道。', commentary: '坐忘的第一步是"断缘",简除无谓事务,形不劳则心自安。企业家更要学会"减法"。', practiceHint: '今日列出5件本周可"断"的事,果断推掉或委派出去。' }] },
  { slug: 'xingming-guizhi', title: '性命圭旨', titleEn: 'Principles of the Innate and the Vital', author: '尹真人高弟(传)', era: '明', ring: 3, categorySlug: 'taoism', summary: '明代内丹集大成之作,分元贞利亨四集,图文并茂阐述性命双修,为道教修炼百科。', significance: '内丹术系统化图解典范,融合儒释道三教修炼。', difficulty: 5, oxStageMin: 7, oxStageMax: 10, readingMins: 90, tags: ['内丹', '性命双修', '三教合一', '圭旨'], sortOrder: 608,
    chapters: [{ chapterNo: 1, title: '性命说', originalText: '何谓之性?元始真如,一灵炯炯是也。何谓之命?先天至精,一气氤氲是也。然有性便有命,有命便有性,性命原不可分。但以其在天则谓之命,在人则谓之性,性命实非有两。', commentary: '性为灵知,命为精气。二者本一,因天人而分名。企业亦如此:使命(性)与现金流(命)不可偏废。', practiceHint: '今日写下公司的"性"(一句话使命)和"命"(12个月现金流)。' }] },
  { slug: 'taiyi-jinhua-zongzhi', title: '太乙金华宗旨', titleEn: 'Secret of the Golden Flower', author: '吕洞宾(传)', era: '清', ring: 3, categorySlug: 'taoism', summary: '扶乩传出的吕祖内丹要诀,十三章,荣格为德文版作序,成为西方心理学与东方丹道交汇的里程碑。', significance: '道教丹法在西方传播的代表作,荣格分析心理学重要参考。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 50, tags: ['内丹', '吕祖', '金华', '西方传'], sortOrder: 609,
    chapters: [{ chapterNo: 1, title: '天心', originalText: '自然曰道,道无名相,一性而已,一元神而已。性命不可见,寄之天光,天光不可见,寄之两目。自古仙真,口口相传,传一得一。', commentary: '道寓于元神,元神寓于天光,天光寓于两目。企业之"道"寓于文化,文化寓于领导人言行。', practiceHint: '今日记录自己3个无意识的小动作,它们就是公司"天光"。' }] },
];

runScripturePatch('M38.32 经论++ v32 精修第二十二轮 — 道家深化', SC);
