/** M38.39 经论++ v39 精修第二十九轮 — 禅宗核心与临济深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'bodhidharma-four-practices', title: '二入四行观', titleEn: 'Two Entrances and Four Practices', author: '菩提达摩', era: '南北朝', ring: 1, categorySlug: 'zen-core', summary: '禅宗初祖达摩核心开示,论"理入"与"行入",行入含四行:报冤/随缘/无所求/称法。', significance: '禅宗最早的正式文献,中国禅宗理论起点。', difficulty: 4, oxStageMin: 4, oxStageMax: 9, readingMins: 20, tags: ['达摩', '二入四行', '禅宗初祖', '理行'], sortOrder: 1300,
    chapters: [{ chapterNo: 1, title: '四行:报冤行', originalText: '第一报冤行者,修道行人若受苦时,当自念言:我从往昔无数劫中,弃本从末,流浪诸有,多起冤憎,违害无限。今虽无犯,是我宿殃,恶业果熟,非天非人所能见与。甘心忍受,都无冤诉。', commentary: '遇逆境不怨天,视为宿业自消。企业遭遇打击时亦当如此:这是旧债清偿,不怨外界。', practiceHint: '今日面对一个"不公"时,假设"这是旧账要还清",不起辩解念头。' }] },
  { slug: 'niutou-juegang-lun', title: '绝观论', titleEn: 'Treatise on Severing Contemplation', author: '牛头法融', era: '7世纪', ring: 1, categorySlug: 'zen-core', summary: '牛头宗法融禅师代表作,以师徒问答形式论"无心合道",为东山法门的重要补充。', significance: '牛头宗纲领文本,彻底的无相无念思想,影响后世马祖道一。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 30, tags: ['牛头宗', '法融', '绝观', '无心'], sortOrder: 1301,
    chapters: [{ chapterNo: 1, title: '无心合道', originalText: '问:何名为心,何名安心?答:汝不须立心,亦不须强安,可谓安矣。问:若无有心,云何学道?答:道非心念,何在于心。', commentary: '牛头宗极端:既无心,则无修可言。企业管理的高阶也是"无管理"——文化自运行。', practiceHint: '今日一个小时不下任何指令,只观察团队自行运转。' }] },
  { slug: 'mazu-shi-zhong', title: '马祖示众', titleEn: 'Mazu Instructions', author: '马祖道一', era: '8世纪', ring: 1, categorySlug: 'zen-core', summary: '洪州禅创始人马祖道一的示众语录,提出"即心即佛""平常心是道"等核心命题。', significance: '禅宗从观心转向任运的转折点,洪州禅纲领。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 30, tags: ['马祖', '洪州禅', '平常心', '即心即佛'], sortOrder: 1302,
    chapters: [{ chapterNo: 1, title: '平常心是道', originalText: '道不用修,但莫污染。何为污染?但有生死心,造作趣向,皆是污染。若欲直会其道,平常心是道。何谓平常心?无造作,无是非,无取舍,无断常,无凡无圣。', commentary: '修道不是造作,而是不污染本心。企业家的"平常心"即是不起贪嗔取舍。', practiceHint: '今日做重要决定时不加"应该/必须"的念头,只问"此刻合不合适"。' }] },
  { slug: 'baizhang-qinggui', title: '百丈清规', titleEn: 'Baizhang Monastic Rules', author: '百丈怀海', era: '9世纪', ring: 1, categorySlug: 'zen-core', summary: '百丈怀海建立禅宗丛林制度的根本规章,"一日不作一日不食"即出此书。', significance: '禅宗制度化的里程碑,中国僧团自立运作的制度基础。', difficulty: 2, oxStageMin: 3, oxStageMax: 9, readingMins: 40, tags: ['百丈', '清规', '丛林', '农禅'], sortOrder: 1303,
    chapters: [{ chapterNo: 1, title: '一日不作一日不食', originalText: '师凡作务执劳,必先于众。众不忍,藏其作具。师至食时不食,曰:"吾无德,安敢劳人。"后遍求作具不获,亦不复食。故有"一日不作,一日不食"之语。', commentary: '百丈以行动立制:劳动即修行。企业领导者亲力亲为的榜样,胜过十次训话。', practiceHint: '今日做一项平时"让下属做"的体力活,不发朋友圈。' }] },
  { slug: 'linji-lu-sibin-zhuke', title: '临济录·四宾主', titleEn: 'Linji Four Host-Guest', author: '临济义玄', era: '9世纪', ring: 1, categorySlug: 'zen-linji', summary: '临济义玄"四宾主"教学法:主看宾/宾看主/宾看宾/主看主,辨别师徒契机深浅。', significance: '临济宗教学纲领,辨证机锋的方法论核心。', difficulty: 5, oxStageMin: 6, oxStageMax: 10, readingMins: 40, tags: ['临济', '四宾主', '教学法', '机锋'], sortOrder: 1304,
    chapters: [{ chapterNo: 1, title: '主中宾·宾中主', originalText: '如诸方学人来,山僧此间作三种根器断:如中下根器来,我便夺其境而不除其法;中上根器来,我便境法俱夺;上上根器来,我便境法人俱不夺;如有出格见解人来,山僧此间便全体作用,不历根器。', commentary: '临济因材施教,对不同根器用不同手段。企业管理亦然:对不同员工用不同沟通法。', practiceHint: '今日针对三位不同风格的下属,用三种不同方式交代同一任务。' }] },
  { slug: 'fenyang-shizhi-tongzhen', title: '汾阳十智同真', titleEn: 'Fenyang Ten Wisdoms', author: '汾阳善昭', era: '10-11世纪', ring: 1, categorySlug: 'zen-linji', summary: '汾阳善昭首倡"十智同真"作为印证禅者见地的检验标准,是临济宗精致化的里程碑。', significance: '临济宗从石头野火到精致体系的转折,宋代文字禅先驱。', difficulty: 5, oxStageMin: 7, oxStageMax: 10, readingMins: 30, tags: ['汾阳', '十智', '文字禅', '临济'], sortOrder: 1305,
    chapters: [{ chapterNo: 1, title: '十智同真', originalText: '善知识!十智同真:一同一质,二同大事,三总同参,四同真智,五同遍普,六同具足,七同得失,八同生杀,九同音吼,十同得入。此十智若辨得,方为真禅者。', commentary: '十智是印证见地的十面镜。企业评估"真战略"亦可设十个维度交叉验证。', practiceHint: '今日给一个核心决策设计10个检验维度,逐项打分。' }] },
  { slug: 'yangqi-fanghui-yulu', title: '杨岐方会语录', titleEn: 'Yangqi Fanghui Recorded Sayings', author: '杨岐方会', era: '11世纪', ring: 1, categorySlug: 'zen-linji', summary: '临济宗杨岐派创始人方会的语录,家风峻烈,直指人心,杨岐派后为临济正统。', significance: '杨岐派开山之作,临济五宗之一,对日本黄檗宗影响深远。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 40, tags: ['杨岐', '方会', '临济五家', '机锋'], sortOrder: 1306,
    chapters: [{ chapterNo: 1, title: '铁酸豏', originalText: '僧问:"如何是佛?"师云:"铁酸豏。"僧云:"意旨如何?"师云:"咬著舌头。"', commentary: '铁酸豏是铁做的饺子——咬不动。佛是什么?非思维可及,一思即咬著舌头。', practiceHint: '今日一个"大问题"起时,不回答,只观察思维被卡住的瞬间。' }] },
  { slug: 'wuzu-fayan-yulu', title: '五祖法演语录', titleEn: 'Wuzu Fayan Recorded Sayings', author: '五祖法演', era: '11世纪', ring: 1, categorySlug: 'zen-linji', summary: '临济杨岐派五祖法演禅师语录,其门下出"三佛"(佛眼/佛果/佛鉴),为宋代禅门中坚。', significance: '南宋禅宗中兴之师,圆悟克勤的亲师父,影响碧岩录。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 40, tags: ['五祖法演', '杨岐派', '三佛', '机锋'], sortOrder: 1307,
    chapters: [{ chapterNo: 1, title: '老鼠入牛角', originalText: '如虫御木,偶得成文。譬如老鼠入牛角——愈入愈尖,尖极无路。若到尖时,便能转身,方可言"透出"。若转不得,即死在牛角内。', commentary: '修行到极致要能转身。企业遇到绝境,若能"转身"反而通达。', practiceHint: '今日面对一个"死胡同"问题,尝试完全相反方向思考。' }] },
  { slug: 'dahui-shuwen', title: '大慧书问', titleEn: 'Dahui Letters', author: '大慧宗杲', era: '12世纪', ring: 1, categorySlug: 'zen-linji', summary: '大慧宗杲禅师与士大夫书信集,推广"看话禅",与宏智正觉的默照禅并列宋代两大禅法。', significance: '看话禅(参话头)纲领文本,影响朝鲜韩国禅宗至今。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 80, tags: ['大慧', '看话禅', '参话头', '士大夫'], sortOrder: 1308,
    chapters: [{ chapterNo: 1, title: '参"无"字话头', originalText: '僧问赵州:"狗子还有佛性也无?"州云:"无。"此一字子,乃是摧许多恶知恶觉底器仗也。但将妄想颠倒底心,思量分别底心,好生恶死底心,都来合作一团,顿在"无"字上。', commentary: '大慧以"无"字作武器,截断妄想。企业家面对纷扰,亦可找一个"定心词"作锚。', practiceHint: '今日焦虑时反复默念一个单字("静"/"空"/"无"),直到情绪松动。' }] },
  { slug: 'xuyun-kaishi', title: '虚云和尚开示', titleEn: 'Xuyun Discourses', author: '虚云', era: '20世纪', ring: 1, categorySlug: 'zen-core', summary: '近代禅宗泰斗虚云老和尚开示集,融合五宗家风,重兴禅门,为20世纪禅宗中兴祖。', significance: '近代禅宗复兴之父,享寿120岁,亲传临济曹洞云门法眼沩仰五家法脉。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 60, tags: ['虚云', '近代禅宗', '五家传承', '开示'], sortOrder: 1309,
    chapters: [{ chapterNo: 1, title: '参禅要旨', originalText: '参禅的先决条件,是深信因果。信因果者,勿论做何事,皆不敢起妄念。妄念既息,则参禅一事,自然水到渠成。妄念不歇而言参禅,如砂煮饭,终无所成。', commentary: '参禅先要信因果,否则妄念不息。企业战略亦然:不信"种什么得什么",无论如何都难成。', practiceHint: '今日检视一个不顺的业务,溯源追问:最初种了什么因?' }] },
];

runScripturePatch('M38.39 经论++ v39 精修第二十九轮 — 禅宗核心与临济深化', SC);
