/** M38.35 经论++ v35 精修第二十五轮 — 犹太卡巴拉深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'sefer-yetzirah', title: '创造之书', titleEn: 'Sefer Yetzirah', author: '亚伯拉罕(传)', era: '公元前2世纪-公元2世纪', ring: 3, categorySlug: 'judaism', summary: '犹太神秘主义最古老文本,阐述希伯来字母如何创造宇宙,是卡巴拉根基。', significance: '卡巴拉三大根本文献之一,数字神秘主义源头。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 40, tags: ['卡巴拉', '创造', '字母', '希伯来'], sortOrder: 900,
    chapters: [{ chapterNo: 1, title: '三十二条智慧之路', originalText: '以三十二条奇妙的智慧之路,永活之神、万军之主、以色列之神、大能的活神,在祂的名下,以三个记录创造了世界:书、数、语。', commentary: '三十二路=十质点(Sefirot)+二十二字母。企业文化若有"32条根本",则成体系。', practiceHint: '今日写下公司"10个核心价值"+"22条操作守则"的框架草案。' }] },
  { slug: 'zohar-introduction', title: '光辉之书·引言', titleEn: 'Zohar Introduction', author: '摩西·德·莱昂', era: '1280', ring: 3, categorySlug: 'judaism', summary: '卡巴拉最重要文献《光辉之书》的引言部分,阐明卡巴拉的神秘使命与学习方法。', significance: '卡巴拉中世纪巅峰之作,被视为第三部妥拉。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 60, tags: ['光辉之书', '卡巴拉', '中世纪', '秘密'], sortOrder: 901,
    chapters: [{ chapterNo: 1, title: '秘密与玫瑰', originalText: '西缅拉比说:玫瑰有十三片花瓣,犹如圣会(Shekhinah)有十三种慈爱。玫瑰有五片萼片如五种严厉。玫瑰之秘即神之秘。', commentary: '玫瑰的结构即神性的结构。万物中都有神圣几何,企业组织亦然。', practiceHint: '今日画出公司组织架构图,问自己:它有美感吗?' }] },
  { slug: 'maimonides-guide-perplexed', title: '迷途指津', titleEn: 'Guide for the Perplexed', author: '迈蒙尼德', era: '1190', ring: 3, categorySlug: 'judaism', summary: '迈蒙尼德调和希伯来启示与亚里士多德哲学的巨著,三卷,是中世纪犹太哲学巅峰。', significance: '犹太理性神学最高成就,直接影响阿奎那的基督教神学。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 120, tags: ['迈蒙尼德', '理性', '亚里士多德', '指津'], sortOrder: 902,
    chapters: [{ chapterNo: 1, title: '否定神学', originalText: '我们无法说神"是什么",只能说神"不是什么"。神不是有形的,不是可见的,不是可分的,不是可变的。越能说神"不是",越接近对神的认识。', commentary: '否定神学通过否定接近真相。企业战略亦可"否定法":先想清楚"我们绝不做什么"。', practiceHint: '今日列出公司"永远不做"的5件事,比列"要做"清单更清晰。' }] },
  { slug: 'baal-shem-tov-tales', title: '巴尔·谢姆·托夫故事集', titleEn: 'Tales of Baal Shem Tov', author: '巴尔·谢姆·托夫(门徒记录)', era: '18世纪', ring: 3, categorySlug: 'judaism', summary: '哈西德派创始人巴尔·谢姆·托夫的言行录,以故事形式传递喜乐修行。', significance: '哈西德派根本文献,东欧犹太教复兴运动之源。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 60, tags: ['哈西德', '巴尔·谢姆·托夫', '喜乐', '故事'], sortOrder: 903,
    chapters: [{ chapterNo: 1, title: '锁与钥匙', originalText: '有人向巴尔·谢姆·托夫问:"若神无处不在,为什么我感觉祂远?"师答:"因为你的心门上了锁。锁上了,钥匙却在你口袋。祈祷不是在找神,是在开自己的锁。"', commentary: '神从未离开,是我们给心门上了锁。企业里的"问题"亦然:往往答案在自己口袋。', practiceHint: '今日面对一个"无解"问题时,先问:我口袋里哪一把钥匙忘了用?' }] },
  { slug: 'tanya-likkutei-amarim', title: '坦雅', titleEn: 'Tanya', author: '施纳·扎尔曼', era: '1796', ring: 3, categorySlug: 'judaism', summary: '哈巴德哈西德派创始人所著,分五部,系统阐述哈西德心理学与神秘主义。', significance: '哈巴德运动根本文本,被称为"哈西德口传律法"。', difficulty: 5, oxStageMin: 7, oxStageMax: 10, readingMins: 90, tags: ['坦雅', '哈巴德', '哈西德', '心理学'], sortOrder: 904,
    chapters: [{ chapterNo: 1, title: '两个灵魂', originalText: '每个犹太人身内有两个灵魂:神圣灵魂与动物灵魂。它们不是对立的敌人,而是两位伙伴。动物灵魂渴望物质,神圣灵魂渴望神。修行就是让神圣灵魂驾驭动物灵魂,而不是消灭它。', commentary: '动物灵魂是能量,神圣灵魂是方向。企业家的"野心"若被"使命"驾驭,即是善用此力。', practiceHint: '今日一个野心勃勃的目标,问:它服务什么更高使命?' }] },
  { slug: 'abulafia-light-intellect', title: '理智之光', titleEn: 'Light of the Intellect', author: '亚伯拉罕·阿布拉菲亚', era: '13世纪', ring: 3, categorySlug: 'judaism', summary: '阿布拉菲亚"预言卡巴拉"核心文本,主张通过希伯来字母冥想达至先知境界。', significance: '卡巴拉冥想派代表作,对当代犹太神秘主义影响深远。', difficulty: 5, oxStageMin: 8, oxStageMax: 10, readingMins: 70, tags: ['阿布拉菲亚', '预言', '字母', '冥想'], sortOrder: 905,
    chapters: [{ chapterNo: 1, title: '字母的转动', originalText: '取一张纸,写下神圣的名字,开始在心中转动字母。每转一次,说出一个音。当字母不再是字母,而成为纯粹的光,你就准备好接受预言了。', commentary: '字母冥想是有节奏的分心训练。企业家需要类似"空心"练习来接受洞见。', practiceHint: '今日反复默念公司使命的一个关键词10分钟,观察浮现什么。' }] },
  { slug: 'nachman-likkutei-moharan', title: '雷比摩哈兰言教录', titleEn: 'Likkutei Moharan', author: '纳赫曼拉比', era: '19世纪初', ring: 3, categorySlug: 'judaism', summary: '布列斯劳夫哈西德派创始人纳赫曼的讲道集,充满创造性解经与心理洞见。', significance: '布列斯劳夫派根本文献,纳赫曼被视为犹太教的"喜乐导师"。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 90, tags: ['纳赫曼', '布列斯劳夫', '喜乐', '哈西德'], sortOrder: 906,
    chapters: [{ chapterNo: 1, title: '全世界是一座窄桥', originalText: '要知道:全世界是一座非常非常窄的桥,最重要的是——不要害怕。恐惧使桥变窄,信心使桥变宽。', commentary: '纳赫曼最著名的一句话。企业家的全部挑战也是:不要害怕。', practiceHint: '今日面对一个让你恐惧的决策时,问自己:如果不怕,我会怎么做?' }] },
  { slug: 'heschel-sabbath', title: '安息日', titleEn: 'The Sabbath', author: '亚伯拉罕·海舍尔', era: '1951', ring: 3, categorySlug: 'judaism', summary: '海舍尔对犹太安息日神学的抒情诠释,以"时间的大教堂"比喻第七日。', significance: '20世纪犹太灵性经典,西方宗教哲学常青书。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 60, tags: ['海舍尔', '安息日', '时间', '灵性'], sortOrder: 907,
    chapters: [{ chapterNo: 1, title: '时间的大教堂', originalText: '犹太教不是在空间上建造大教堂,而是在时间上建造。安息日就是时间的大教堂。一周六天我们劳作征服空间,第七天我们停下来朝拜时间。', commentary: '现代企业家被"空间"(办公室/产品/规模)占据,忘了"时间"也是圣殿。', practiceHint: '本周强制一天不碰工作,把时间当作"圣殿"进入。' }] },
  { slug: 'buber-i-and-thou', title: '我与你', titleEn: 'I and Thou', author: '马丁·布伯', era: '1923', ring: 3, categorySlug: 'judaism', summary: '布伯对话哲学代表作,区分"我-你"与"我-它"两种关系,是20世纪最有影响的犹太哲学著作。', significance: '对话哲学奠基之作,影响存在主义、基督教神学、心理治疗。', difficulty: 5, oxStageMin: 7, oxStageMax: 10, readingMins: 80, tags: ['布伯', '对话', '我与你', '存在主义'], sortOrder: 908,
    chapters: [{ chapterNo: 1, title: '两种基本关系', originalText: '世界对人呈现为两种态度,一是"我-它",一是"我-你"。"我-它"把对方当作经验的客体,"我-你"则是全然的相遇。没有"我-你"的相遇,就没有真正的生命。', commentary: '客户不是"它",员工不是"它"。企业的灵魂在于多少"我-你"的相遇。', practiceHint: '今日与一位员工谈话时,全程不看手机、不想下一件事。' }] },
  { slug: 'levinas-totality-infinity', title: '总体与无限', titleEn: 'Totality and Infinity', author: '伊曼努埃尔·列维纳斯', era: '1961', ring: 3, categorySlug: 'judaism', summary: '列维纳斯以"面容"概念重构伦理学,主张他者的面容是一切伦理的起源。', significance: '后现代伦理学奠基之作,为犹太思想对当代哲学最大贡献。', difficulty: 5, oxStageMin: 9, oxStageMax: 10, readingMins: 120, tags: ['列维纳斯', '伦理', '面容', '他者'], sortOrder: 909,
    chapters: [{ chapterNo: 1, title: '他者的面容', originalText: '他者的面容直接向我说:"不要杀我。"这是第一个道德命令,它先于一切理论、一切推理。面容是无限的痕迹,是超越之召唤。', commentary: '伦理先于一切,面对他人的面容即是道德起点。企业伦理亦然:不是规则,是相遇。', practiceHint: '今日裁员/处罚一个下属前,先静看他的照片1分钟。' }] },
];

runScripturePatch('M38.35 经论++ v35 精修第二十五轮 — 犹太卡巴拉深化', SC);
