/**
 * seed-destinations-v5.ts — 目的地++ 自动循环 v5 (rounds 10-19)
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

interface S {
  name: string; nameEn: string; religionSlug: string; country: string;
  latitude: number; longitude: number; utcOffset: number;
  soundEffect?: string | null; description: string;
  openingHours?: string; ticketPrice?: string; bestSeason?: string;
  visitDuration?: string; transport?: string; tips?: string[]; batch: string;
}

const SITES: S[] = [
  // ── R10: 道教名山补强 ──
  { batch: 'R10-道教名山', name: '罗浮山', nameEn: 'Mount Luofu', religionSlug: 'taoism', country: '中国', latitude: 23.2833, longitude: 114.0333, utcOffset: 8, soundEffect: 'wind_chimes', description: '岭南第一山 —— 葛洪炼丹地\n432座山峰，冲虚古观为千年道场，东晋葛洪著《抱朴子》于此', openingHours: '07:00-18:00', ticketPrice: '¥60', transport: '广州东站至博罗高铁30分钟转车', tips: ['白水门瀑布可合游', '夏季避暑胜地', '冲虚观为核心'] },
  { batch: 'R10-道教名山', name: '老君山', nameEn: 'Mount Laojun', religionSlug: 'taoism', country: '中国', latitude: 33.7361, longitude: 111.6342, utcOffset: 8, soundEffect: 'wind_chimes', description: '河南伏牛山主峰 —— 李耳归隐处\n海拔2217米，山顶金顶道观群为中原道教文化核心', openingHours: '07:00-18:00', ticketPrice: '¥100 + 索道 ¥110', transport: '洛阳至栾川大巴3小时', tips: ['金顶云海日出最佳', '冬季雾凇奇观', '索道两段需分别购票'] },
  { batch: 'R10-道教名山', name: '武夷山', nameEn: 'Mount Wuyi (Taoist sites)', religionSlug: 'taoism', country: '中国', latitude: 27.7333, longitude: 117.9756, utcOffset: 8, soundEffect: 'wind_chimes', description: '三教名山 —— 朱熹讲学地\n天心永乐禅寺与桃源洞道观并存，九曲溪漂流闻名，UNESCO世界遗产', openingHours: '07:00-17:30', ticketPrice: '¥140 + 竹筏 ¥130', transport: '武夷山站高铁直达', tips: ['九曲溪漂流必体验', '岩茶茶山可参观', '避开5月假期'] },
  { batch: 'R10-道教名山', name: '三山五岳南岳衡山', nameEn: 'Mount Heng (South)', religionSlug: 'taoism', country: '中国', latitude: 27.3014, longitude: 112.6940, utcOffset: 8, soundEffect: 'wind_chimes', description: '南岳衡山 —— 寿岳\n南岳大庙佛道共存格局天下独一，祝融峰海拔1300米', openingHours: '全天开放', ticketPrice: '旺季 ¥120 / 淡季 ¥80', transport: '衡阳高铁站接驳至南岳区', tips: ['八月香期十万朝山', '祝融峰日出需住山上', '火神信仰独特'] },
  { batch: 'R10-道教名山', name: '巍宝山', nameEn: 'Mount Weibao', religionSlug: 'taoism', country: '中国', latitude: 25.1944, longitude: 100.2167, utcOffset: 8, soundEffect: 'wind_chimes', description: '南诏发祥地 —— 道教文化西南第一山\n云南巍山，22座宫观散布，细奴逻发迹地', openingHours: '08:00-17:30', ticketPrice: '¥60', transport: '大理巍山县城车程20分钟', tips: ['与巍山古城合游', '长春洞为精华', '彝族火把节氛围独特'] },
  { batch: 'R10-道教名山', name: '鹤鸣山', nameEn: 'Mount Heming', religionSlug: 'taoism', country: '中国', latitude: 30.6014, longitude: 103.2861, utcOffset: 8, soundEffect: 'wind_chimes', description: '道教文化发源地 —— 张道陵创天师道\n东汉汉安元年(142年)张道陵在此创立五斗米道', openingHours: '08:00-17:00', ticketPrice: '¥30', transport: '成都大邑县车程1小时', tips: ['与青城山齐名更幽静', '迎仙阁为核心', '四季皆宜'] },
  { batch: 'R10-道教名山', name: '太白山', nameEn: 'Mount Taibai', religionSlug: 'taoism', country: '中国', latitude: 33.9511, longitude: 107.7611, utcOffset: 8, soundEffect: 'wind_chimes', description: '秦岭主峰 —— 海拔3767米\n张三丰隐修处，云海雪峰并存，AAAAA级景区', openingHours: '08:00-18:00 (冬季封山)', ticketPrice: '¥100 + 景区车 ¥60', transport: '西安北站至眉县高铁40分钟', tips: ['上山要坐3段车', '海拔高防高反', '冬季11月到次年3月封山'] },
  { batch: 'R10-道教名山', name: '武夷山桃源洞', nameEn: 'Taoyuan Cave Wuyi', religionSlug: 'taoism', country: '中国', latitude: 27.6944, longitude: 117.9544, utcOffset: 8, soundEffect: 'wind_chimes', description: '武夷山九曲溪深处道观 —— 洞天福地\n幽径通幽别有洞天，王羲之、李商隐曾游', openingHours: '08:00-17:00', ticketPrice: '含在武夷山大票中', transport: '九曲溪坐竹筏至五曲码头徒步', tips: ['人少幽静', '桃花春季最美', '沿途奇石多'] },
  { batch: 'R10-道教名山', name: '括苍山', nameEn: 'Mount Kuocang', religionSlug: 'taoism', country: '中国', latitude: 28.6639, longitude: 121.2119, utcOffset: 8, soundEffect: 'wind_chimes', description: '浙东道教文化名山 —— 十大洞天第十\n台州括苍山主峰米筛浪1382米，东海观日出胜地', openingHours: '全天开放', ticketPrice: '免费', transport: '台州黄岩车程2小时', tips: ['风电景观独特', '冬季云海壮美', '山顶野宿爱好者多'] },
  { batch: 'R10-道教名山', name: '青羊宫', nameEn: 'Qingyang Gong Temple', religionSlug: 'taoism', country: '中国', latitude: 30.6656, longitude: 104.0444, utcOffset: 8, soundEffect: 'wind_chimes', description: '成都最古道观 —— 老子说法地\n传为老子骑青牛西出函谷前说法处，现存明清建筑', openingHours: '08:00-18:00', ticketPrice: '¥10', transport: '成都地铁5号线青羊宫站', tips: ['与文殊院近邻可合游', '农历二月十五花会节最盛', '铜羊为镇观之宝'] },

  // ── R11: 道教海外/华人社区 ──
  { batch: 'R11-道教海外', name: '香港青松观', nameEn: 'Ching Chung Koon', religionSlug: 'taoism', country: '中国', latitude: 22.4078, longitude: 113.9747, utcOffset: 8, soundEffect: 'wind_chimes', description: '香港全真龙门派祖庭 —— 1950年创\n屯门盆景园美誉，全真教文化海外传承典范', openingHours: '07:00-17:30', ticketPrice: '免费', transport: '轻铁505线青松站出', tips: ['盆景园免费', '素斋馆值得一试', '周末家族祭祀热闹'] },
  { batch: 'R11-道教海外', name: '香港蓬瀛仙馆', nameEn: 'Fung Ying Seen Koon', religionSlug: 'taoism', country: '中国', latitude: 22.4964, longitude: 114.1331, utcOffset: 8, soundEffect: 'wind_chimes', description: '粉岭全真道场 —— 1929年创\n港岛最大道教文化慈善机构之一', openingHours: '08:00-17:00', ticketPrice: '免费', transport: '东铁线粉岭站A1出口', tips: ['有素食馆对外开放', '重阳节庙会最盛', '园林静雅'] },
  { batch: 'R11-道教海外', name: '新加坡玉皇殿', nameEn: 'Jade Emperor Temple Singapore', religionSlug: 'taoism', country: '新加坡', latitude: 1.2850, longitude: 103.8497, utcOffset: 8, soundEffect: 'wind_chimes', description: '新加坡华人道教文化中心 —— 天公坛\n玉皇大帝主祀，每年正月初九天公生节最盛', openingHours: '07:00-18:00', ticketPrice: '免费', transport: '牛车水地铁站步行', tips: ['正月初九祭天特别隆重', '与马里安曼神庙邻近', '可合游牛车水'] },
  { batch: 'R11-道教海外', name: '马来西亚鹤山观', nameEn: 'Hor San Koon Penang', religionSlug: 'taoism', country: '马来西亚', latitude: 5.4152, longitude: 100.3292, utcOffset: 8, soundEffect: 'wind_chimes', description: '槟城百年道教文化祖庙 —— 华人南迁文化火种\n清末华人南洋开埠时始建', openingHours: '07:00-18:00', ticketPrice: '免费', transport: '槟城乔治市老街区步行', tips: ['与观音亭合游', '农历三月三最盛', '街区华人人文精神浓'] },
  { batch: 'R11-道教海外', name: '台湾台北指南宫', nameEn: 'Zhinan Temple Taipei', religionSlug: 'taoism', country: '中国台湾', latitude: 24.9736, longitude: 121.5889, utcOffset: 8, soundEffect: 'wind_chimes', description: '台北木栅八仙山 —— 吕洞宾主祀\n猫空缆车可达，台北道教文化第一大庙', openingHours: '全天开放', ticketPrice: '免费', transport: '台北捷运至动物园站转猫空缆车', tips: ['恋人传说勿双入', '俯瞰台北夜景极佳', '斋菜可品尝'] },
  { batch: 'R11-道教海外', name: '台北行天宫', nameEn: 'Xingtian Temple Taipei', religionSlug: 'taoism', country: '中国台湾', latitude: 25.0628, longitude: 121.5336, utcOffset: 8, soundEffect: 'wind_chimes', description: '台北关公庙 —— 商界朝拜中心\n1968年建，不收功德钱不烧金纸的现代道场', openingHours: '04:00-22:30', ticketPrice: '免费', transport: '台北捷运行天宫站', tips: ['收惊(改运)仪式免费', '不收香油钱', '门前地下道算命街独特'] },
  { batch: 'R11-道教海外', name: '高雄左营孔子庙', nameEn: 'Kaohsiung Lotus Pond Temple', religionSlug: 'taoism', country: '中国台湾', latitude: 22.6789, longitude: 120.2953, utcOffset: 8, soundEffect: 'wind_chimes', description: '莲池潭春秋阁 —— 玄天上帝与关公\n台湾南部道教文化龙虎塔标志，左营莲池潭畔', openingHours: '06:00-22:00', ticketPrice: '免费', transport: '高雄捷运红线左营站', tips: ['龙虎塔入龙出虎为传统', '莲池潭日落最美', '附近夜市'] },
  { batch: 'R11-道教海外', name: '越南河内白马寺', nameEn: 'Bach Ma Temple Hanoi', religionSlug: 'taoism', country: '越南', latitude: 21.0361, longitude: 105.8497, utcOffset: 7, soundEffect: 'wind_chimes', description: '河内三十六街区老庙 —— 11世纪白马神\n李太祖建都升龙时所祀城隍，越南道教文化融合本土', openingHours: '08:00-18:00', ticketPrice: '免费', transport: '河内老街区步行', tips: ['农历2月13日庙会最盛', '与周围老街区合游', '建筑精致'] },
  { batch: 'R11-道教海外', name: '纽约华尔街附近关帝庙', nameEn: 'Mahayana Temple NYC (Guandi Altar)', religionSlug: 'taoism', country: '美国', latitude: 40.7175, longitude: -73.9967, utcOffset: -5, soundEffect: 'wind_chimes', description: '纽约华埠关帝祭坛 —— 移民人文精神\n美东华人社区道教文化代表，大乘寺内设坛', openingHours: '09:00-18:00', ticketPrice: '免费', transport: '纽约地铁 Canal St 站', tips: ['与坚尼街华埠合游', '周末人多', '楼上有金佛供奉'] },
  { batch: 'R11-道教海外', name: '旧金山天后古庙', nameEn: 'Tin How Temple San Francisco', religionSlug: 'taoism', country: '美国', latitude: 37.7955, longitude: -122.4083, utcOffset: -8, soundEffect: 'ocean_waves', description: '北美最古老道教文化庙 —— 1852年创\n旧金山唐人街天后(妈祖)庙，海外华人人文精神火种', openingHours: '10:00-16:00', ticketPrice: '免费 (欢迎捐献)', transport: '旧金山唐人街 Waverly Pl 125号顶楼', tips: ['需爬三层楼梯', '禁摄影进殿', '旧金山华埠游必访'] },

  // ── R12: 儒家书院补强 ──
  { batch: 'R12-儒家书院', name: '鹅湖书院', nameEn: 'Ehu Academy', religionSlug: 'confucianism', country: '中国', latitude: 28.3386, longitude: 117.8672, utcOffset: 8, soundEffect: 'wind_chimes', description: '朱陆鹅湖之会圣地 —— 1175年\n朱熹与陆九渊三日辩论理学心学分野，江西铅山', openingHours: '08:00-17:00', ticketPrice: '¥30', transport: '上饶站至铅山县城车程1小时', tips: ['人少幽静', '与武夷山合游线路', '鹅湖诗石刻值得细读'] },
  { batch: 'R12-儒家书院', name: '茅山书院', nameEn: 'Maoshan Academy', religionSlug: 'confucianism', country: '中国', latitude: 31.7536, longitude: 119.3128, utcOffset: 8, soundEffect: 'wind_chimes', description: '宋代四大书院之一 —— 与岳麓白鹿洞嵩阳并列\n江苏金坛茅山南麓，朱熹题"道统"匾', openingHours: '08:00-17:00', ticketPrice: '¥20', transport: '镇江句容车程30分钟', tips: ['与茅山道教合游', '人少原生态', '春秋季最佳'] },
  { batch: 'R12-儒家书院', name: '万松书院', nameEn: 'Wansong Academy', religionSlug: 'confucianism', country: '中国', latitude: 30.2397, longitude: 120.1319, utcOffset: 8, soundEffect: 'wind_chimes', description: '杭州明代书院 —— 梁祝同窗传说地\n万松岭上古松成林，明王阳明曾讲学于此', openingHours: '07:30-17:30', ticketPrice: '¥10', transport: '杭州凤凰山脚下步行', tips: ['与西湖合游', '梁祝爱情园合并', '山顶观西湖佳'] },
  { batch: 'R12-儒家书院', name: '茶山书院', nameEn: 'Chashan Academy', religionSlug: 'confucianism', country: '中国', latitude: 27.8208, longitude: 116.9361, utcOffset: 8, soundEffect: 'wind_chimes', description: '江西贵溪元代书院 —— 吴澄讲学处\n1292年建，元代理学重要传承点', openingHours: '08:00-17:00', ticketPrice: '¥15', transport: '贵溪市区车程30分钟', tips: ['偏远人少', '朱子学传承地', '秋季银杏美'] },
  { batch: 'R12-儒家书院', name: '龙冈书院', nameEn: 'Longgang Academy', religionSlug: 'confucianism', country: '中国', latitude: 26.8644, longitude: 106.7086, utcOffset: 8, soundEffect: 'wind_chimes', description: '王阳明龙场悟道处 —— 心学发源地\n贵州修文县，1508年王守仁贬谪悟"致良知"', openingHours: '08:00-18:00', ticketPrice: '¥50', transport: '贵阳市车程1小时', tips: ['玩易窝洞内王阳明悟道雕像', '与阳明洞合游', '心学信徒必访'] },
  { batch: 'R12-儒家书院', name: '尼山书院', nameEn: 'Nishan Academy', religionSlug: 'confucianism', country: '中国', latitude: 35.5456, longitude: 117.1056, utcOffset: 8, soundEffect: 'wind_chimes', description: '孔子出生地夫子洞旁 —— 2013年重建\n曲阜尼山，以"尼山论坛"闻名的文明对话平台所在', openingHours: '08:00-17:00', ticketPrice: '¥80 (含尼山景区)', transport: '曲阜站车程30分钟', tips: ['与孔庙孔林合游', '夜场实景演出', '孔子观川亭观沂河'] },
  { batch: 'R12-儒家书院', name: '五台山儒家讲堂', nameEn: 'Wutai Confucius Hall', religionSlug: 'confucianism', country: '中国', latitude: 31.0406, longitude: 121.3706, utcOffset: 8, soundEffect: 'wind_chimes', description: '上海松江五台书堂 —— 清代文人雅集\n嘉定孔庙与松江五台书堂并重，江南文脉节点', openingHours: '09:00-16:30 周一闭', ticketPrice: '¥10', transport: '上海松江地铁9号线', tips: ['周一闭馆', '与嘉定孔庙合游', '松江老城邻近'] },
  { batch: 'R12-儒家书院', name: '韩国陶山书院', nameEn: 'Dosan Seowon', religionSlug: 'confucianism', country: '韩国', latitude: 36.7131, longitude: 128.8422, utcOffset: 9, soundEffect: 'wind_chimes', description: '韩国儒学至圣地 —— 李退溪讲学处\n1574年建，千元韩币图案来源，UNESCO世界遗产(韩国9书院)', openingHours: '09:00-18:00 (冬 09:00-17:00)', ticketPrice: 'KRW 1500', transport: '安东市区车程40分钟', tips: ['附近有退溪宗宅', '秋季红叶美', '韩币1000元纸币图案即为陶山书院建筑'] },
  { batch: 'R12-儒家书院', name: '韩国屏山书院', nameEn: 'Byeongsan Seowon', religionSlug: 'confucianism', country: '韩国', latitude: 36.5422, longitude: 128.6803, utcOffset: 9, soundEffect: 'wind_chimes', description: '安东河回屏山 —— 柳成龙纪念书院\nUNESCO世界遗产，晚对楼俯瞰洛东江最佳', openingHours: '09:00-17:30', ticketPrice: 'KRW 2000', transport: '安东河回村徒步或骑车10分钟', tips: ['与河回村合游', '晚对楼观江无敌', '春秋银杏美'] },
  { batch: 'R12-儒家书院', name: '越南顺化国子监', nameEn: 'Imperial Academy Hue', religionSlug: 'confucianism', country: '越南', latitude: 16.4642, longitude: 107.5792, utcOffset: 7, soundEffect: 'wind_chimes', description: '阮朝最高学府 —— 1821年建\n顺化皇城内，越南末代儒学中心，UNESCO世界遗产', openingHours: '07:00-17:30', ticketPrice: 'VND 150000 (含皇城)', transport: '顺化机场出租30分钟', tips: ['与顺化皇城合游', '石碑刻进士名录', '春节冷清秋冬合宜'] },

  // ── R13: 禅宗祖庭补强 ──
  { batch: 'R13-禅宗祖庭', name: '达摩面壁洞少林寺', nameEn: 'Damo Cave Shaolin', religionSlug: 'buddhism', country: '中国', latitude: 34.5097, longitude: 112.9306, utcOffset: 8, soundEffect: 'temple_bell', description: '达摩九年面壁处 —— 禅宗初祖洞\n少林寺后山五乳峰山顶天然洞穴', openingHours: '08:00-17:00 (含在少林门票内)', ticketPrice: '含少林寺 ¥100', transport: '少林寺往后山徒步1.5小时或索道', tips: ['徒步单程1.5小时', '索道单程 ¥50', '洞内供达摩石像'] },
  { batch: 'R13-禅宗祖庭', name: '黄梅五祖寺', nameEn: 'Wuzu Temple Huangmei', religionSlug: 'buddhism', country: '中国', latitude: 30.1931, longitude: 115.8769, utcOffset: 8, soundEffect: 'temple_bell', description: '禅宗五祖弘忍道场 —— 传衣六祖处\n湖北黄梅，六祖慧能在此得法南归，东禅寺', openingHours: '07:30-17:00', ticketPrice: '¥50', transport: '九江至黄梅车程1.5小时', tips: ['六祖槽厂遗址', '真身殿供五祖金身像', '与四祖寺合游'] },
  { batch: 'R13-禅宗祖庭', name: '黄梅四祖寺', nameEn: 'Sizu Temple Huangmei', religionSlug: 'buddhism', country: '中国', latitude: 30.1411, longitude: 115.8681, utcOffset: 8, soundEffect: 'temple_bell', description: '禅宗四祖道信道场 —— 中国最早僧团自耕自食地\n双峰山下，净慧老和尚复兴禅七', openingHours: '07:30-17:00', ticketPrice: '¥50', transport: '九江黄梅车程1.5小时', tips: ['禅七活动常年举办', '住宿客堂可预约', '环境清幽'] },
  { batch: 'R13-禅宗祖庭', name: '韶关云门寺', nameEn: 'Yunmen Temple Shaoguan', religionSlug: 'buddhism', country: '中国', latitude: 24.7886, longitude: 113.5692, utcOffset: 8, soundEffect: 'temple_bell', description: '云门宗祖庭 —— 文偃禅师开宗\n923年创，虚云和尚1943年重兴', openingHours: '08:00-17:00', ticketPrice: '免费', transport: '韶关乳源县车程40分钟', tips: ['与南华寺合游六祖路线', '虚云舍利塔必瞻', '斋堂对外开放'] },
  { batch: 'R13-禅宗祖庭', name: '江西云居山真如寺', nameEn: 'Yunju Zhenru Temple', religionSlug: 'buddhism', country: '中国', latitude: 29.2472, longitude: 115.7086, utcOffset: 8, soundEffect: 'temple_bell', description: '曹洞宗祖庭 —— 虚云和尚驻锡终老处\n江西永修，1953年虚云114岁重兴', openingHours: '08:00-17:00', ticketPrice: '¥50', transport: '九江市永修县车程1.5小时', tips: ['虚云塔为精神圣地', '禅堂可参加坐香', '居士班常年'] },
  { batch: 'R13-禅宗祖庭', name: '江西洞山普利寺', nameEn: 'Dongshan Puli Temple', religionSlug: 'buddhism', country: '中国', latitude: 28.4161, longitude: 114.7736, utcOffset: 8, soundEffect: 'temple_bell', description: '曹洞宗本山 —— 良价祖师开宗\n宜丰县，曹山本寂禅师与师徒创"曹洞"宗', openingHours: '08:00-17:00', ticketPrice: '免费', transport: '南昌至宜丰车程2.5小时', tips: ['与曹山宝积寺合游', '五位君臣偈发源地', '幽深人少'] },
  { batch: 'R13-禅宗祖庭', name: '湖南沩山密印寺', nameEn: 'Weishan Miyin Temple', religionSlug: 'buddhism', country: '中国', latitude: 28.3222, longitude: 112.3658, utcOffset: 8, soundEffect: 'temple_bell', description: '沩仰宗祖庭 —— 灵佑禅师开宗\n807年唐元和二年创，千手观音为特色', openingHours: '07:30-17:30', ticketPrice: '¥30', transport: '长沙宁乡车程2小时', tips: ['万佛殿千手观音为后塑但震撼', '附近石林秀美', '沩仰宗信众朝拜点'] },
  { batch: 'R13-禅宗祖庭', name: '福建福州鼓山涌泉寺', nameEn: 'Yongquan Temple Fuzhou', religionSlug: 'buddhism', country: '中国', latitude: 26.0833, longitude: 119.3689, utcOffset: 8, soundEffect: 'temple_bell', description: '福州鼓山临济宗祖庭 —— 五代时期建\n闽南禅宗最大道场，虚云曾住持', openingHours: '07:00-18:00', ticketPrice: '¥40 (含山门)', transport: '福州地铁2号线至鼓山站换公交', tips: ['山门石刻"涌泉"二字', '万佛陶塔独特', '可步行古道上山'] },
  { batch: 'R13-禅宗祖庭', name: '浙江宁波天童寺', nameEn: 'Tiantong Temple Ningbo', religionSlug: 'buddhism', country: '中国', latitude: 29.7778, longitude: 121.7869, utcOffset: 8, soundEffect: 'temple_bell', description: '曹洞宗东传日本起点 —— 道元回国携此法\n1225年日本道元禅师在此得法，为日本曹洞宗源', openingHours: '07:00-17:00', ticketPrice: '¥30', transport: '宁波市区公交约1小时', tips: ['日本信众朝拜不绝', '阿育王寺邻近合游', '四季分明环境幽静'] },
  { batch: 'R13-禅宗祖庭', name: '浙江阿育王寺', nameEn: 'Ayuwang Temple', religionSlug: 'buddhism', country: '中国', latitude: 29.7722, longitude: 121.7189, utcOffset: 8, soundEffect: 'temple_bell', description: '江南现存最古寺院之一 —— 西晋始建\n藏佛舍利(金塔保存)，义学中心', openingHours: '07:00-17:00', ticketPrice: '¥5', transport: '宁波市区公交', tips: ['与天童寺同日游', '舍利塔需预约', '斋堂对外开放'] },

  // ── R14: 神道补强至30 ──
  { batch: 'R14-神道补强', name: '东京神田明神', nameEn: 'Kanda Myojin', religionSlug: 'shinto', country: '日本', latitude: 35.7017, longitude: 139.7678, utcOffset: 9, soundEffect: 'taiko_drum', description: '江户镇守 —— 神田祭闻名\n730年创，秋叶原IT族朝拜电子产品安全', openingHours: '全天参拜 (社务所 09:00-16:00)', ticketPrice: '免费', transport: '东京地铁御茶水站步行5分钟', tips: ['秋叶原邻近可合游', '5月神田祭盛大', '有IT守护御守'] },
  { batch: 'R14-神道补强', name: '京都八坂神社', nameEn: 'Yasaka Shrine', religionSlug: 'shinto', country: '日本', latitude: 35.0036, longitude: 135.7786, utcOffset: 9, soundEffect: 'wind_chimes', description: '祇园镇守 —— 祇园祭本社\n656年创，7月祇园祭为日本三大祭之一', openingHours: '全天开放', ticketPrice: '免费', transport: '京阪电车祇园四条站', tips: ['祇园艺伎区对面', '夜间灯笼点亮', '与圆山公园相连'] },
  { batch: 'R14-神道补强', name: '北野天满宫', nameEn: 'Kitano Tenmangu', religionSlug: 'shinto', country: '日本', latitude: 35.0311, longitude: 135.7350, utcOffset: 9, soundEffect: 'taiko_drum', description: '学问之神总本社 —— 菅原道真\n梅花2000株，高中生考前必访', openingHours: '05:00-18:00', ticketPrice: '免费 (宝物殿 ¥1000)', transport: '京都市巴士50路至北野天满宫前', tips: ['2月梅花祭最盛', '每月25日天神市集跳蚤市场', '与金阁寺合游'] },
  { batch: 'R14-神道补强', name: '京都平野神社', nameEn: 'Hirano Shrine', religionSlug: 'shinto', country: '日本', latitude: 35.0344, longitude: 135.7319, utcOffset: 9, soundEffect: 'wind_chimes', description: '京都樱花名所 —— 985年始\n400株樱花60余品种，夜樱最美', openingHours: '06:00-17:00', ticketPrice: '免费', transport: '京都市巴士50路', tips: ['4月初樱花期夜间灯光', '与北野天满宫可步行', '摊位多氛围好'] },
  { batch: 'R14-神道补强', name: '奈良若草山麓手向山八幡宫', nameEn: 'Tamukeyama Hachimangu', religionSlug: 'shinto', country: '日本', latitude: 34.6861, longitude: 135.8453, utcOffset: 9, soundEffect: 'taiko_drum', description: '奈良东大寺守护神 —— 749年迁座\n奈良朝廷所建八幡神社，鹿随参道', openingHours: '05:30-17:30', ticketPrice: '免费', transport: '东大寺大佛殿后步行10分钟', tips: ['与东大寺合游', '鹿可近距离接触', '秋季红叶独特'] },
  { batch: 'R14-神道补强', name: '日光二荒山神社', nameEn: 'Futarasan Shrine', religionSlug: 'shinto', country: '日本', latitude: 36.7581, longitude: 139.5986, utcOffset: 9, soundEffect: 'wind_chimes', description: '日光三社之一 —— 767年创\n奥日光华严瀑布为御神域，UNESCO世界遗产', openingHours: '04月-10月 08:00-17:00 / 11-3月 09:00-16:00', ticketPrice: '神苑 ¥300', transport: '日光巴士至神桥步行5分钟', tips: ['与东照宫合游', '神桥为日本三大奇桥', '秋季红叶期人多'] },
  { batch: 'R14-神道补强', name: '仙台大崎八幡宫', nameEn: 'Osaki Hachimangu Sendai', religionSlug: 'shinto', country: '日本', latitude: 38.2719, longitude: 140.8450, utcOffset: 9, soundEffect: 'taiko_drum', description: '伊达政宗建造 —— 国宝社殿\n1607年桃山式建筑，镜池与鸟居经典', openingHours: '09:00-16:00', ticketPrice: '免费', transport: '仙台巴士国見丘下车步行5分钟', tips: ['1月焰祭(松焚祭)壮观', '日本传统婚礼圣地', '与仙台城合游'] },
  { batch: 'R14-神道补强', name: '鹿儿岛雾岛神宫', nameEn: 'Kirishima Jingu', religionSlug: 'shinto', country: '日本', latitude: 31.8583, longitude: 130.8681, utcOffset: 9, soundEffect: 'wind_chimes', description: '天孙降临地 —— 琼琼杵尊\n6世纪始建，坂本龙马蜜月地', openingHours: '全天 (社务所 08:00-16:30)', ticketPrice: '免费', transport: '雾岛神宫站徒步10分钟或巴士', tips: ['与雾岛温泉合游', '秋季红叶佳', '龙马纪念地'] },
  { batch: 'R14-神道补强', name: '岛根县须佐神社', nameEn: 'Susa Shrine Izumo', religionSlug: 'shinto', country: '日本', latitude: 35.2864, longitude: 132.8731, utcOffset: 9, soundEffect: 'wind_chimes', description: '须佐之男命终焉地 —— 日本最古神社之一\n七不思议(须佐七怪)传说', openingHours: '全天 (社务所 09:00-17:00)', ticketPrice: '免费', transport: '出云市巴士40分钟偏远山间', tips: ['与出云大社合游需自驾', '大杉古木2000年', '人少静谧'] },
  { batch: 'R14-神道补强', name: '和歌山熊野本宫大社', nameEn: 'Kumano Hongu Taisha', religionSlug: 'shinto', country: '日本', latitude: 33.8378, longitude: 135.7736, utcOffset: 9, soundEffect: 'wind_chimes', description: '熊野三山之首 —— 熊野古道终点\n8世纪创，UNESCO世界遗产(纪伊半岛圣地与参诣道)', openingHours: '全天 (社务所 08:00-17:00)', ticketPrice: '免费', transport: '新宫/白浜机场巴士约2小时', tips: ['熊野古道徒步胜地', '大斋原日本最高鸟居34米', '与那智/新宫三山游'] },

  // ── R15: 藏传补强 ──
  { batch: 'R15-藏传补强', name: '青海果洛查朗寺', nameEn: 'Charang Monastery', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 34.4167, longitude: 100.2500, utcOffset: 8, soundEffect: 'singing_bowl', description: '宁玛派藏东大寺 —— 格鲁派入藏前古刹\n果洛藏族自治州，600年藏学中心', openingHours: '09:00-18:00', ticketPrice: '免费', transport: '西宁至果洛车程8小时', tips: ['海拔高防高反', '无商业化体验', '冬季道路不通'] },
  { batch: 'R15-藏传补强', name: '四川甘孜德格八邦寺', nameEn: 'Palpung Monastery', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 31.7833, longitude: 98.6167, utcOffset: 8, soundEffect: 'singing_bowl', description: '噶玛噶举派小布达拉宫 —— 大司徒仁波切驻锡\n海拔3670米，藏东噶玛巴画派艺术核心', openingHours: '09:00-17:00', ticketPrice: '免费', transport: '甘孜州德格县车程1.5小时', tips: ['与德格印经院合游', '道路艰险需越野车', '夏季最佳'] },
  { batch: 'R15-藏传补强', name: '青海玉树新寨嘛呢石经城', nameEn: 'Gyanak Mani', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 33.0136, longitude: 96.9792, utcOffset: 8, soundEffect: 'singing_bowl', description: '世界最大玛尼石堆 —— 25亿块石刻经文\n1715年起积累至今，藏传佛教文化信众虔诚明证', openingHours: '全天开放', ticketPrice: '免费', transport: '玉树结古镇出租30分钟', tips: ['高海拔3700米', '右绕3圈传统', '冬季风大注意保暖'] },
  { batch: 'R15-藏传补强', name: '西藏拉萨小昭寺', nameEn: 'Ramoche Temple', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 29.6533, longitude: 91.1283, utcOffset: 8, soundEffect: 'singing_bowl', description: '文成公主所建 —— 7世纪与大昭寺并立\n原供释迦牟尼8岁等身佛，后与大昭寺主佛对调', openingHours: '09:00-17:30', ticketPrice: '¥20', transport: '大昭寺步行10分钟', tips: ['比大昭寺安静', '释迦牟尼12岁等身像(原为大昭寺的)', '上密院隶属'] },
  { batch: 'R15-藏传补强', name: '西藏乃琼寺', nameEn: 'Nechung Monastery', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 29.6847, longitude: 91.0483, utcOffset: 8, soundEffect: 'singing_bowl', description: '乃琼护法神殿 —— 西藏国家神谕所\n达赖喇嘛国师降神所在，哲蚌寺旁', openingHours: '09:00-17:00', ticketPrice: '¥10', transport: '哲蚌寺车程5分钟', tips: ['与哲蚌寺合游', '护法殿壁画震撼', '有时不对游客开放'] },
  { batch: 'R15-藏传补强', name: '藏北纳木错扎西寺', nameEn: 'Tashi Dor Monastery', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 30.7614, longitude: 90.9772, utcOffset: 8, soundEffect: 'singing_bowl', description: '纳木错湖畔千年古寺 —— 莲花生加持地\n海拔4718米，扎西半岛五洞穴传说', openingHours: '日出到日落', ticketPrice: '免费 (纳木错景区 ¥120)', transport: '拉萨至纳木错车程4.5小时', tips: ['高海拔严重高反', '6-9月最佳', '冬季封山'] },
  { batch: 'R15-藏传补强', name: '青海塔公寺', nameEn: 'Tagong Temple', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 30.0694, longitude: 101.5256, utcOffset: 8, soundEffect: 'singing_bowl', description: '小大昭寺 —— 文成公主遗像\n甘孜塔公草原，萨迦派藏东重要道场', openingHours: '09:00-18:00', ticketPrice: '¥20', transport: '康定新都桥至塔公车程1小时', tips: ['塔公草原合游', '赛马节(7-8月)最盛', '藏地风光典范'] },
  { batch: 'R15-藏传补强', name: '西藏山南昌珠寺', nameEn: 'Tradruk Monastery', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 29.2439, longitude: 91.7761, utcOffset: 8, soundEffect: 'singing_bowl', description: '吐蕃最古寺院之一 —— 7世纪松赞干布建\n藏王夏宫，金汁珍珠唐卡为镇寺之宝', openingHours: '09:00-17:30', ticketPrice: '¥70', transport: '拉萨至泽当车程3小时', tips: ['珍珠唐卡必看', '山南文化中心合游雍布拉康', '人文精神厚重'] },
  { batch: 'R15-藏传补强', name: '西藏雍布拉康', nameEn: 'Yumbulagang', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 29.2275, longitude: 91.7347, utcOffset: 8, soundEffect: 'singing_bowl', description: '西藏第一座宫殿 —— 第一代赞普聂赤所建\n公元前2世纪始建，藏族人文精神发祥地', openingHours: '09:00-17:30', ticketPrice: '¥30', transport: '山南泽当出租30分钟', tips: ['可骑马上山', '山顶观雅砻河谷', '传说松赞干布寝宫'] },
  { batch: 'R15-藏传补强', name: '青海瞿昙寺藏经楼', nameEn: 'Qutan Temple Scriptorium', religionSlug: 'tibetan-buddhism', country: '中国', latitude: 36.3114, longitude: 102.2889, utcOffset: 8, soundEffect: 'singing_bowl', description: '小故宫 —— 明初皇家修建汉藏合璧\n1392年明太祖敕建，76幅壁画为明代壁画艺术巅峰', openingHours: '08:30-17:00', ticketPrice: '¥50', transport: '西宁乐都县车程1.5小时', tips: ['壁画禁闪光拍照', '规模比故宫小但完整', '与塔尔寺合游'] },

  // ── R16: 原住民美洲 ──
  { batch: 'R16-原住民美洲', name: '梅萨维德', nameEn: 'Mesa Verde', religionSlug: 'indigenous', country: '美国', latitude: 37.1853, longitude: -108.4869, utcOffset: -7, soundEffect: 'wind_chimes', description: '普韦布洛悬崖宫殿 —— 600-1300年阿纳萨齐文明\n600座悬崖房屋嵌入峡谷石壁，UNESCO世界遗产', openingHours: '公园全年 / 宫殿导览 4-10月', ticketPrice: '车辆 $30/7天 + 导览 $8-25', transport: '丹佛自驾7小时至公园', tips: ['Cliff Palace导览需预约', '夏季人多需提前2周', '冬季部分导览停止'] },
  { batch: 'R16-原住民美洲', name: '卡霍基亚土墩群', nameEn: 'Cahokia Mounds', religionSlug: 'indigenous', country: '美国', latitude: 38.6556, longitude: -90.0608, utcOffset: -6, soundEffect: 'wind_chimes', description: '密西西比文明首都 —— 700-1400年\n最大曾容纳2万人，Monks Mound为北美最大史前建筑', openingHours: '09:00-17:00 周一闭', ticketPrice: '免费 (建议 $7 捐献)', transport: '圣路易斯市东15分钟自驾', tips: ['登Monks Mound顶', '博物馆讲解透彻', '春夏野餐区佳'] },
  { batch: 'R16-原住民美洲', name: '陶斯普韦布洛', nameEn: 'Taos Pueblo', religionSlug: 'indigenous', country: '美国', latitude: 36.4389, longitude: -105.5458, utcOffset: -7, soundEffect: 'wind_chimes', description: '千年居民村 —— UNESCO世界遗产\n阿美利加现存持续居住最久的村落，红色土坯建筑', openingHours: '08:00-16:30 (部分季节闭村仪式期)', ticketPrice: '$25/人', transport: '圣菲北上车程90分钟', tips: ['入村前查关闭日', '禁进墓地与圣域', '节庆期游客限制'] },
  { batch: 'R16-原住民美洲', name: '卡尼恩德舍利', nameEn: 'Canyon de Chelly', religionSlug: 'indigenous', country: '美国', latitude: 36.1342, longitude: -109.4686, utcOffset: -7, soundEffect: 'wind_chimes', description: '纳瓦霍圣谷 —— 白屋悬崖\n5000年居住史，仅限导游陪同进入谷底', openingHours: '24小时 (观景台)', ticketPrice: '免费 (私家导游 $75+)', transport: '亚利桑那Chinle镇', tips: ['独行只能走白屋步道', '其他区域必须有纳瓦霍向导', '秋季最佳'] },
  { batch: 'R16-原住民美洲', name: '四角纪念碑', nameEn: 'Four Corners Monument', religionSlug: 'indigenous', country: '美国', latitude: 36.9989, longitude: -109.0453, utcOffset: -7, soundEffect: 'wind_chimes', description: '四州交界唯一点 —— 纳瓦霍部落公园\n亚犹科新四州交界，纳瓦霍文化展示中心', openingHours: '08:00-17:00 (夏至延长)', ticketPrice: '$8/人', transport: '科特兹车程1.5小时', tips: ['人少照片好拍', '附近土著工艺品售卖', '偏远需充足油水'] },
  { batch: 'R16-原住民美洲', name: '蒂卡尔玛雅古城', nameEn: 'Tikal', religionSlug: 'indigenous', country: '危地马拉', latitude: 17.2220, longitude: -89.6237, utcOffset: -6, soundEffect: 'wind_chimes', description: '玛雅文明三大城之一 —— 公元前600年至900年\n六大金字塔群，最高72米，UNESCO世界文化自然双遗产', openingHours: '06:00-18:00', ticketPrice: 'GTQ 150 (日出/日落另 GTQ 100)', transport: '弗洛雷斯机场至蒂卡尔车程1.5小时', tips: ['日出游览最魔幻', '带驱虫剂防蚊', '丛林中猴子多'] },
  { batch: 'R16-原住民美洲', name: '卡拉克穆尔', nameEn: 'Calakmul', religionSlug: 'indigenous', country: '墨西哥', latitude: 18.1050, longitude: -89.8117, utcOffset: -6, soundEffect: 'wind_chimes', description: '玛雅蛇王朝首都 —— 公元前400-900年\n丛林深处，Structure II是玛雅第二高金字塔，UNESCO世界遗产', openingHours: '08:00-17:00', ticketPrice: 'MXN 100', transport: '坎佩切至Xpujil车程3小时再转60公里土路', tips: ['极度偏远', '需清晨出发', '游客稀少荒野感强'] },
  { batch: 'R16-原住民美洲', name: '蒙特阿尔万', nameEn: 'Monte Albán', religionSlug: 'indigenous', country: '墨西哥', latitude: 17.0439, longitude: -96.7672, utcOffset: -6, soundEffect: 'wind_chimes', description: '萨波特克文明首都 —— 公元前500年起\n瓦哈卡山顶古城，三面绝壁，UNESCO世界遗产', openingHours: '08:00-17:00', ticketPrice: 'MXN 90', transport: '瓦哈卡市出租30分钟', tips: ['舞者浮雕神秘', '瓦哈卡市区合游', '山顶风大带外套'] },
  { batch: 'R16-原住民美洲', name: '莫奇卡太阳金字塔', nameEn: 'Huaca del Sol', religionSlug: 'indigenous', country: '秘鲁', latitude: -8.1303, longitude: -78.9725, utcOffset: -5, soundEffect: 'wind_chimes', description: '前印加莫奇卡文明 —— 公元100-800年\n泥砖金字塔，特鲁希略北部大遗迹', openingHours: '09:00-16:00', ticketPrice: 'PEN 10', transport: '特鲁希略市区出租30分钟', tips: ['与月亮神庙同区', '沙漠气候干燥', '太阳神庙主体闭展'] },
  { batch: 'R16-原住民美洲', name: '昌昌遗址', nameEn: 'Chan Chan', religionSlug: 'indigenous', country: '秘鲁', latitude: -8.1033, longitude: -79.0756, utcOffset: -5, soundEffect: 'wind_chimes', description: '奇穆文明首都 —— 世界最大土砖城\n1300-1470年，6万人居，UNESCO世界遗产', openingHours: '09:00-16:00', ticketPrice: 'PEN 11 (含特鲁希略4遗址)', transport: '特鲁希略市公交20分钟', tips: ['联票有效2天', '日晒强烈带帽', '博物馆精致'] },

  // ── R17: 原住民 非洲/大洋洲/亚洲 ──
  { batch: 'R17-原住民跨洲', name: '卡卡杜国家公园岩画', nameEn: 'Kakadu Rock Art', religionSlug: 'indigenous', country: '澳大利亚', latitude: -12.8720, longitude: 132.8322, utcOffset: 9.5, soundEffect: 'wind_chimes', description: '原住民5万年岩画艺术 —— X光画风\n5000处岩画遗址，UNESCO世界双遗产', openingHours: '全年 (雨季11-4月部分封闭)', ticketPrice: 'AUD 40/人/7天 (旺季)', transport: '达尔文市自驾3小时至Jabiru', tips: ['Ubirr与Nourlangie为主要岩画点', '雨季部分封闭', '夜观星空极佳'] },
  { batch: 'R17-原住民跨洲', name: '瓦尔彭里萨夫人圣地', nameEn: 'Wilpena Pound', religionSlug: 'indigenous', country: '澳大利亚', latitude: -31.5211, longitude: 138.6189, utcOffset: 9.5, soundEffect: 'wind_chimes', description: '阿达尼亚玛桑原住民圣域\n天然环形山脉弗林德斯山脉核心，千年梦创故事发生地', openingHours: '全天', ticketPrice: 'AUD 13', transport: '阿德莱德北上500公里', tips: ['与原住民导游徒步最佳', '日出日落光线佳', '部分禁区需尊重'] },
  { batch: 'R17-原住民跨洲', name: '图姆阿斯山洞(毛利创世洞)', nameEn: 'Waitomo Caves', religionSlug: 'indigenous', country: '新西兰', latitude: -38.2608, longitude: 175.1033, utcOffset: 12, soundEffect: 'wind_chimes', description: '毛利萤火虫洞 —— 传说祖先灵魂之门\n螺旋钟乳洞，毛利Ruakuri家族世代守护', openingHours: '09:00-17:00', ticketPrice: 'NZD 62-99', transport: '奥克兰南下3小时', tips: ['萤火虫船游必选', '毛利家族导游讲解', '雨后水位升可能调整'] },
  { batch: 'R17-原住民跨洲', name: '莱塞-埃济耶洞窟', nameEn: 'Lascaux Caves', religionSlug: 'indigenous', country: '法国', latitude: 45.0533, longitude: 1.1728, utcOffset: 1, soundEffect: 'wind_chimes', description: '克罗马农人岩画 —— 2万年前\n600幅动物壁画(原洞禁入，看Lascaux IV复制品)，UNESCO世界遗产', openingHours: '复制洞 09:30-18:30 (季节变动)', ticketPrice: '€22', transport: '波尔多至Montignac车程2.5小时', tips: ['原洞自1963年关闭', 'Lascaux IV为精确复制', '夏季提前预约'] },
  { batch: 'R17-原住民跨洲', name: '印度尼西亚桑伊兰', nameEn: 'Sangiran Early Man Site', religionSlug: 'indigenous', country: '印尼', latitude: -7.4567, longitude: 110.8367, utcOffset: 7, soundEffect: 'wind_chimes', description: '爪哇人化石发现地 —— 150万年人类演化\n50余原人化石出土，UNESCO世界遗产', openingHours: '08:00-16:00', ticketPrice: 'IDR 10000', transport: '梭罗市西北车程1.5小时', tips: ['博物馆陈列丰富', '与婆罗浮屠合游方便', '干旱季节节9-10月佳'] },
  { batch: 'R17-原住民跨洲', name: '肯尼亚马赛马拉圣地', nameEn: 'Maasai Sacred Trees', religionSlug: 'indigenous', country: '肯尼亚', latitude: -1.5061, longitude: 35.1436, utcOffset: 3, soundEffect: 'wind_chimes', description: '马赛族神圣无花果树 —— Nkahu树\n部落长老议事与婚礼仪式神圣树荫，非博物馆传统活态传承', openingHours: '随马赛村落导览', ticketPrice: 'USD 20 部落门票', transport: '内罗毕机场飞马赛马拉1.5小时', tips: ['与Safari合游', '需持相机礼仪尊重', '雨季10-11月路险'] },
  { batch: 'R17-原住民跨洲', name: '尼日利亚奥逊森林', nameEn: 'Osun-Osogbo Sacred Grove', religionSlug: 'indigenous', country: '尼日利亚', latitude: 7.7525, longitude: 4.5436, utcOffset: 1, soundEffect: 'wind_chimes', description: '约鲁巴水神奥逊圣林 —— 400年守护\n原始森林中神庙雕塑群，UNESCO世界遗产', openingHours: '07:00-18:00', ticketPrice: 'NGN 1000', transport: '奥苏博市出租30分钟', tips: ['8月Osun-Osogbo节最盛', '不许水中游泳(神圣河)', '向导必要'] },
  { batch: 'R17-原住民跨洲', name: '加拿大赖廷罗克艺术', nameEn: 'Writing-on-Stone', religionSlug: 'indigenous', country: '加拿大', latitude: 49.0808, longitude: -111.6236, utcOffset: -7, soundEffect: 'wind_chimes', description: '黑脚印第安人岩画圣地 —— 3000年\n北美草原最大岩画群，UNESCO世界遗产', openingHours: '夏 09:00-21:00 / 冬 09:00-16:30', ticketPrice: 'CAD 8', transport: '卡尔加里南下4小时', tips: ['岩画游览需参加导览', '露营区可预订', '五月雁归季节最美'] },
  { batch: 'R17-原住民跨洲', name: '玻利维亚萨玛帕塔', nameEn: 'Samaipata', religionSlug: 'indigenous', country: '玻利维亚', latitude: -18.1800, longitude: -63.8231, utcOffset: -4, soundEffect: 'wind_chimes', description: '世界最大单岩雕刻遗址 —— 前印加奇里瓜诺文化\n250米×60米岩床雕刻几何与动物图腾，UNESCO世界遗产', openingHours: '09:00-16:30', ticketPrice: 'BOB 50', transport: '圣克鲁斯车程2.5小时', tips: ['印加岩石"El Fuerte"必看', '与小镇合游一日', '高海拔1950米'] },
  { batch: 'R17-原住民跨洲', name: '芬兰萨米驯鹿圣湖', nameEn: 'Sami Lake Inari', religionSlug: 'indigenous', country: '芬兰', latitude: 68.9083, longitude: 27.0250, utcOffset: 2, soundEffect: 'wind_chimes', description: '萨米族母湖 —— 北极圈原住民圣地\n芬兰最大湖泊之一，Ukonkivi岛为萨米祭天圣石', openingHours: '全年 (Ukonkivi夏季船游)', ticketPrice: '游湖船 €20-40', transport: '伊瓦洛机场出租40分钟至伊纳里村', tips: ['萨米博物馆Siida精致', '冬季可看极光', '夏季永昼'] },

  // ── R18: 巴哈伊 ──
  { batch: 'R18-巴哈伊', name: '以色列巴哈欧拉尘世陵', nameEn: 'Mansion of Mazraih', religionSlug: 'bahai', country: '以色列', latitude: 32.9778, longitude: 35.0794, utcOffset: 2, soundEffect: 'wind_chimes', description: '巴哈欧拉1877年出狱居所 —— 阿卡城外\n巴哈伊信仰创立者晚年居住地之一', openingHours: '周五-周日 09:00-16:00', ticketPrice: '免费 (需邮箱预约)', transport: '海法至阿卡火车30分钟', tips: ['需着装正式', '女性需肩膝覆盖', '团队可申请导览'] },
  { batch: 'R18-巴哈伊', name: '阿巴斯陵', nameEn: 'Shrine of Abdul-Baha', religionSlug: 'bahai', country: '以色列', latitude: 32.8175, longitude: 34.9744, utcOffset: 2, soundEffect: 'wind_chimes', description: '阿巴斯·阿芬迪新陵寝 —— 2024年开放\n巴哈伊第二代圣护，海法卡梅尔山脚', openingHours: '09:00-12:00 (部分日)', ticketPrice: '免费', transport: '海法巴哈伊花园南侧', tips: ['新建陵寝朝圣热潮', '需在线预约', '免费讲解'] },
  { batch: 'R18-巴哈伊', name: '伊朗设拉子巴孛家', nameEn: "Bab's House Shiraz", religionSlug: 'bahai', country: '伊朗', latitude: 29.6100, longitude: 52.5419, utcOffset: 3.5, soundEffect: 'wind_chimes', description: '巴孛宣示处 —— 1844年5月23日\n巴哈伊信仰先驱的宣道地，原宅1979年毁现纪念位', openingHours: '非开放遗址', ticketPrice: '—', transport: '设拉子市中心', tips: ['不对公开旅游开放', '巴哈伊信众可私访', '历史意义巨大'] },
  { batch: 'R18-巴哈伊', name: '印度浦那巴哈伊中心', nameEn: 'Pune Bahai Centre', religionSlug: 'bahai', country: '印度', latitude: 18.5204, longitude: 73.8567, utcOffset: 5.5, soundEffect: 'wind_chimes', description: '南亚巴哈伊重要中心 —— 教育与灵性聚会\n印度第二大巴哈伊社区所在', openingHours: '09:00-18:00', ticketPrice: '免费', transport: '浦那市区出租', tips: ['图书馆开放', '定期19日灵性聚会', '可参加礼拜'] },
  { batch: 'R18-巴哈伊', name: '巴布亚新几内亚灵曦堂', nameEn: 'PNG Bahai House of Worship', religionSlug: 'bahai', country: '巴布亚新几内亚', latitude: -9.4438, longitude: 147.1803, utcOffset: 10, soundEffect: 'wind_chimes', description: '大洋洲第二灵曦堂(规划中)\n2024年奠基，国家级灵曦堂五洲其一', openingHours: '建设中 (预计2028)', ticketPrice: '—', transport: '莫尔兹比港', tips: ['当前仅奠基纪念可瞻', '计划2028年落成', '代表大洋洲新人文精神进展'] },
  { batch: 'R18-巴哈伊', name: '刚果民主共和国灵曦堂', nameEn: 'DR Congo Bahai Temple', religionSlug: 'bahai', country: '刚果金', latitude: -4.3167, longitude: 15.3167, utcOffset: 1, soundEffect: 'wind_chimes', description: '非洲国家级灵曦堂 —— 2023年启用\n金沙萨卢比鲁马设区，白色九面几何', openingHours: '08:00-17:00', ticketPrice: '免费', transport: '金沙萨市区出租', tips: ['代表非洲巴哈伊发展', '周日聚会对公众开放', '建筑现代'] },
  { batch: 'R18-巴哈伊', name: '柬埔寨巴淡邦地方灵曦堂', nameEn: 'Battambang Bahai Temple', religionSlug: 'bahai', country: '柬埔寨', latitude: 13.1032, longitude: 103.1963, utcOffset: 7, soundEffect: 'wind_chimes', description: '东南亚首座巴哈伊地方灵曦堂\n2017年建成，当地首座', openingHours: '08:00-17:00', ticketPrice: '免费', transport: '巴淡邦市区', tips: ['建筑高棉风格九面穹顶', '与吴哥合游可', '19日聚会对公众'] },
  { batch: 'R18-巴哈伊', name: '哥伦比亚诺里港地方灵曦堂', nameEn: 'Norte del Cauca Bahai Temple', religionSlug: 'bahai', country: '哥伦比亚', latitude: 3.0658, longitude: -76.3972, utcOffset: -5, soundEffect: 'wind_chimes', description: '南美首座地方灵曦堂 —— 2018年\n哥伦比亚黑人社区文化象征', openingHours: '09:00-17:00', ticketPrice: '免费', transport: '卡利车程1小时', tips: ['建筑象征可可树', '参观需预约', '周日聚会开放'] },
  { batch: 'R18-巴哈伊', name: '巴哈伊国家纪念花园', nameEn: 'Bahai Monument Gardens Haifa', religionSlug: 'bahai', country: '以色列', latitude: 32.8147, longitude: 34.9803, utcOffset: 2, soundEffect: 'wind_chimes', description: '卡梅尔山巴哈伊后花园 —— 纪念先驱\n19步骤花园延伸，家族纪念花园', openingHours: '09:00-17:00', ticketPrice: '免费', transport: '海法巴哈伊花园上方', tips: ['花园顶端视野', '与下花园合游', '着装需肩膝'] },
  { batch: 'R18-巴哈伊', name: '马耳他巴哈伊国家中心', nameEn: 'Malta Bahai National Centre', religionSlug: 'bahai', country: '马耳他', latitude: 35.8989, longitude: 14.5146, utcOffset: 1, soundEffect: 'wind_chimes', description: '地中海巴哈伊精神灯塔\n瓦莱塔郊区，南欧北非巴哈伊社区节点', openingHours: '09:00-17:00', ticketPrice: '免费', transport: '瓦莱塔市区出租15分钟', tips: ['小社区温馨', '19日聚会对公众', '可随时参访交流'] },

  // ── R19: 锡克+犹太+补强 ──
  { batch: 'R19-锡克犹太补强', name: '孟买阿夫加尼萨希卜', nameEn: 'Gurdwara Guru Nanak Darbar Mumbai', religionSlug: 'sikhism', country: '印度', latitude: 19.0760, longitude: 72.8777, utcOffset: 5.5, soundEffect: 'taiko_drum', description: '孟买锡克中心 —— 1901年创\n印度西部最大锡克庙，24小时langar食堂', openingHours: '24小时', ticketPrice: '免费', transport: '孟买中央火车站出租15分钟', tips: ['入殿戴头巾脱鞋', '免费素食', '周日人多'] },
  { batch: 'R19-锡克犹太补强', name: '德里达姆达玛·萨希卜', nameEn: 'Gurdwara Damdama Sahib Delhi', religionSlug: 'sikhism', country: '印度', latitude: 28.5250, longitude: 77.1764, utcOffset: 5.5, soundEffect: 'taiko_drum', description: '德里锡克六庙之一 —— Guru Gobind Singh停驻地\n德里南郊，Awrangzeb接见后短驻', openingHours: '04:00-22:00', ticketPrice: '免费', transport: '德里地铁Khan Market站出租', tips: ['与Bangla Sahib一日朝拜', '人少安静', '讲究礼仪'] },
  { batch: 'R19-锡克犹太补强', name: '德里拉坎萨希卜', nameEn: 'Gurdwara Rakab Ganj Sahib', religionSlug: 'sikhism', country: '印度', latitude: 28.6157, longitude: 77.2056, utcOffset: 5.5, soundEffect: 'taiko_drum', description: '德里Guru Tegh Bahadur火葬地\n1675年第九古鲁殉教后遗体火化之所', openingHours: '04:00-21:00', ticketPrice: '免费', transport: '德里议会大厦附近步行', tips: ['与Bangla Sahib联动', '庄严气氛', '历史浓'] },
  { batch: 'R19-锡克犹太补强', name: '纽约曼哈顿锡克文化中心', nameEn: 'Sikh Cultural Society NYC', religionSlug: 'sikhism', country: '美国', latitude: 40.7355, longitude: -73.8494, utcOffset: -5, soundEffect: 'wind_chimes', description: '美东最大锡克社区中心 —— 皇后区\nRichmond Hill区，北美锡克移民文化中心', openingHours: '06:00-21:00', ticketPrice: '免费', transport: '纽约地铁J线121 St站', tips: ['周日langar对公众', '入殿戴头巾脱鞋', '社区活动丰富'] },
  { batch: 'R19-锡克犹太补强', name: '塞拉热窝老犹太会堂', nameEn: 'Sarajevo Old Synagogue', religionSlug: 'judaism', country: '波黑', latitude: 43.8583, longitude: 18.4289, utcOffset: 1, soundEffect: 'wind_chimes', description: '巴尔干塞法迪犹太人文化中心 —— 1581年\n奥斯曼时期西班牙流亡者后裔建，博物馆', openingHours: '10:00-18:00 夏 / 10:00-14:00 冬', ticketPrice: 'BAM 3', transport: '塞拉热窝市中心步行', tips: ['多数展品展现战时历史', '与老城合游', '现在一楼仍为会堂'] },
  { batch: 'R19-锡克犹太补强', name: '摩洛哥菲斯犹太区', nameEn: 'Mellah of Fes', religionSlug: 'judaism', country: '摩洛哥', latitude: 34.0617, longitude: -4.9833, utcOffset: 1, soundEffect: 'wind_chimes', description: '北非最古犹太区 —— 15世纪建立\nFez el-Jdid老城内，Aben Danan会堂为核心', openingHours: '09:00-18:00 周五下午及周六闭', ticketPrice: 'MAD 20 (会堂)', transport: '菲斯老城西门出租', tips: ['犹太公墓独特白墓碑', '与皇宫合游', '需导游防迷路'] },
  { batch: 'R19-锡克犹太补强', name: '西西里锡拉库萨犹太区', nameEn: 'Ortigia Jewish Quarter', religionSlug: 'judaism', country: '意大利', latitude: 37.0583, longitude: 15.2944, utcOffset: 1, soundEffect: 'wind_chimes', description: '意大利最古米克瓦仪式浴池 —— 6世纪\n奥尔蒂贾岛地下16米米克瓦浴池', openingHours: '参观需预约', ticketPrice: '€5-10', transport: '锡拉库萨市中心', tips: ['仅预约参观', '与奥尔蒂贾岛合游', '讲解深入历史'] },
  { batch: 'R19-锡克犹太补强', name: '伦敦贝维斯马克斯会堂', nameEn: 'Bevis Marks Synagogue', religionSlug: 'judaism', country: '英国', latitude: 51.5150, longitude: -0.0786, utcOffset: 0, soundEffect: 'wind_chimes', description: '英国最古持续使用会堂 —— 1701年\n塞法迪犹太人社区中心，银吊灯珍贵', openingHours: '周日至五 10:30-13:00', ticketPrice: '£10', transport: '伦敦地铁Liverpool Street站', tips: ['犹太公会墓园附近合游', '周六(安息日)不对游客', '历史讲解详细'] },
  { batch: 'R19-锡克犹太补强', name: '以色列贝特谢安古会堂遗址', nameEn: 'Beit Shean Synagogue Ruin', religionSlug: 'judaism', country: '以色列', latitude: 32.4983, longitude: 35.4972, utcOffset: 2, soundEffect: 'wind_chimes', description: '拜占庭时代犹太聚落 —— 6世纪\n马赛克地板保存完好，贝特谢安国家公园内', openingHours: '08:00-17:00 (夏延至18:00)', ticketPrice: 'NIS 28', transport: '提比利亚车程40分钟', tips: ['马赛克保存极佳', '与尚坦遗址合游', '夏季酷热'] },
  { batch: 'R19-锡克犹太补强', name: '以色列莫迪因马卡比墓', nameEn: 'Maccabee Tombs Modiin', religionSlug: 'judaism', country: '以色列', latitude: 31.8983, longitude: 35.0100, utcOffset: 2, soundEffect: 'wind_chimes', description: '马卡比家族故里 —— 光明节起源\n公元前167年马卡比起义策源地', openingHours: '全天遗址开放', ticketPrice: '免费', transport: '莫迪因市出租', tips: ['实际墓址学界有争议但地点确定', '光明节前朝圣', '与老城合游'] },
];

async function main() {
  console.log('🎯 目的地++ v5: rounds 10-19 批量补丁\n');
  const religions = await prisma.religion.findMany({ select: { id: true, slug: true } });
  const slugToId = new Map(religions.map((r) => [r.slug, r.id]));

  let created = 0, skipped = 0;
  const byBatch: Record<string, { created: number; skipped: number }> = {};

  for (const site of SITES) {
    byBatch[site.batch] ??= { created: 0, skipped: 0 };
    const religionId = slugToId.get(site.religionSlug);
    if (!religionId) { console.warn(`⚠ skip ${site.name}: religion ${site.religionSlug}`); continue; }

    const existing = await prisma.holySite.findFirst({
      where: { name: site.name, religionId }, select: { id: true },
    });
    if (existing) { skipped++; byBatch[site.batch].skipped++; continue; }

    await prisma.holySite.create({
      data: {
        name: site.name, nameEn: site.nameEn, country: site.country,
        latitude: site.latitude, longitude: site.longitude, utcOffset: site.utcOffset,
        soundEffect: site.soundEffect ?? null, description: site.description,
        openingHours: site.openingHours, ticketPrice: site.ticketPrice,
        bestSeason: site.bestSeason, visitDuration: site.visitDuration,
        transport: site.transport, tips: site.tips ?? [],
        source: 'AI_KNOWLEDGE', status: 'ACTIVE', religionId,
      },
    });
    created++; byBatch[site.batch].created++;
  }

  console.log('📦 批次:');
  for (const [b, s] of Object.entries(byBatch)) console.log(`  ${b}: +${s.created}/skip ${s.skipped}`);
  console.log(`\n✓ 新增: ${created}   ⏭ 跳过: ${skipped}`);
  console.log(`📊 HolySite 总数: ${await prisma.holySite.count()}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
