/** M38.34 经论++ v34 精修第二十四轮 — 伊斯兰苏菲深化 10 部 */
import { runScripturePatch, NewScriptureDef } from './_scripture-patch-runner';

const SC: NewScriptureDef[] = [
  { slug: 'hafez-divan', title: '哈菲兹诗集', titleEn: 'Divan of Hafez', author: '哈菲兹', era: '14世纪', ring: 3, categorySlug: 'islam', summary: '波斯伟大诗人哈菲兹的抒情诗集,约500首加扎勒,歌颂爱、酒、玫瑰、夜莺,暗喻苏菲修行。', significance: '波斯文学最高峰,被誉为"舌之奇迹",歌德称"东方诗人之王"。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 80, tags: ['苏菲', '波斯诗', '哈菲兹', '加扎勒'], sortOrder: 800,
    chapters: [{ chapterNo: 1, title: '玫瑰与夜莺', originalText: '玫瑰无言地绽放,夜莺为她歌唱。若你问我爱是什么,我会沉默,因为沉默是爱最深的语言。醉心于真主的人,无须世间的酒。', commentary: '苏菲诗歌以酒、玫瑰、夜莺隐喻神爱。企业家的使命亦是"无言绽放"——做事不争辩。', practiceHint: '今日完成一项工作,不发朋友圈、不宣传,默默完成即可。' }] },
  { slug: 'saadi-rose-garden', title: '蔷薇园', titleEn: 'Gulistan of Saadi', author: '萨迪', era: '1258', ring: 3, categorySlug: 'islam', summary: '波斯诗人萨迪以散文和诗歌交织写成的道德故事集,8卷,是波斯文学双璧之一。', significance: '伊斯兰世界道德教育经典,被译成数十种语言。', difficulty: 2, oxStageMin: 3, oxStageMax: 10, readingMins: 70, tags: ['萨迪', '波斯', '蔷薇园', '道德'], sortOrder: 801,
    chapters: [{ chapterNo: 1, title: '亚当子孙皆兄弟', originalText: '亚当子孙皆兄弟,兄弟犹如手足亲。造物之初本一体,一肢罹病染全身。为人不恤他人苦,不配人字共我称。', commentary: '此诗刻于联合国总部大厅。企业家若视全球员工为兄弟,决策自然有温度。', practiceHint: '今日写一封感谢信给一位远程同事,不谈工作,只问近况。' }] },
  { slug: 'attar-conference-birds', title: '百鸟朝凤', titleEn: 'Conference of the Birds', author: '法里德·丁·阿塔尔', era: '1177', ring: 3, categorySlug: 'islam', summary: '阿塔尔以鸟类朝圣寻凤王西穆格的寓言,讲述苏菲七谷灵修历程。', significance: '苏菲派寓言诗巅峰,鲁米称阿塔尔为其精神之父。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 90, tags: ['阿塔尔', '百鸟', '七谷', '寓言'], sortOrder: 802,
    chapters: [{ chapterNo: 1, title: '七谷:寻求之谷', originalText: '第一谷是寻求之谷。在这里你必须抛下一切,忍受千辛万苦。许多年过去,你努力不懈。血从你心流出。你会做许多看似不可能的事。然后你会到达下一谷:爱之谷。', commentary: '寻求之谷就是创业初期的九死一生。不流血者,不能进入下一阶段。', practiceHint: '今日对正在放弃的一件难事,再坚持一次,不为结果只为经历。' }] },
  { slug: 'rumi-masnavi-book2', title: '玛斯纳维·卷二', titleEn: 'Masnavi Book Two', author: '鲁米', era: '13世纪', ring: 3, categorySlug: 'islam', summary: '鲁米玛斯纳维第二卷,主题为"友谊与导师",以大量故事阐明苏菲师徒关系。', significance: '波斯文学巅峰,被称为"波斯语的古兰经"。', difficulty: 4, oxStageMin: 5, oxStageMax: 10, readingMins: 90, tags: ['鲁米', '玛斯纳维', '导师', '苏菲'], sortOrder: 803,
    chapters: [{ chapterNo: 1, title: '大象与盲人', originalText: '一群盲人第一次摸到大象,摸到腿的说它像柱子,摸到耳的说它像扇子,摸到鼻的说它像水管,摸到尾的说它像绳子。各人都真诚地描述,却没有一人见到大象全貌。', commentary: '每个人只见局部真相。企业管理的冲突本质都是"盲人摸象",没人全对也没人全错。', practiceHint: '今日遇到争论时,先承认:我摸到的只是大象的一部分。' }] },
  { slug: 'ghazali-mishkat-anwar', title: '光的壁龛', titleEn: 'Niche of Lights', author: '安萨里', era: '11世纪', ring: 3, categorySlug: 'islam', summary: '安萨里解释《古兰经》"光节"的神秘著作,将光分为五层,阐明苏菲的光之体验。', significance: '伊斯兰神秘主义认识论经典,影响后世苏菲思想深远。', difficulty: 5, oxStageMin: 7, oxStageMax: 10, readingMins: 60, tags: ['安萨里', '光', '神秘主义', '苏菲'], sortOrder: 804,
    chapters: [{ chapterNo: 1, title: '真主是诸天与大地之光', originalText: '"真主是诸天与大地之光"——这是古兰经的光节。真正的光只有一个,就是真主本身。其他一切所谓"光"都是借来的,如月光借自日光。', commentary: '万有之光皆借自唯一之光。企业的一切"亮点"其实都借自使命之光。', practiceHint: '今日想象公司每个产品都是使命的"月光",它反射的是什么?' }] },
  { slug: 'ibn-arabi-fusus-hikam', title: '智慧宝石', titleEn: 'Fusus al-Hikam', author: '伊本·阿拉比', era: '1229', ring: 3, categorySlug: 'islam', summary: '伊本·阿拉比最后的著作,以27位先知各配一章,阐述"万有存在合一"(wahdat al-wujud)。', significance: '苏菲派最深奥的理论著作,被誉为"伟大谢赫"之顶峰。', difficulty: 5, oxStageMin: 9, oxStageMax: 10, readingMins: 100, tags: ['伊本·阿拉比', '智慧宝石', '存在合一', '先知'], sortOrder: 805,
    chapters: [{ chapterNo: 1, title: '亚当的智慧', originalText: '真主想看见自己,于是创造了亚当作为一面镜子。镜子只有被擦亮才能映现,所以人类的使命就是擦亮自己的心,让真主藉由自己认识自己。', commentary: '人是神的自我认识。企业家的"自我实现"其实是让更大的生命藉由自己显化。', practiceHint: '今日一个决策问:是"我想要",还是"使命藉我显化"?' }] },
  { slug: 'jami-yusuf-zulaikha', title: '优素福与祖莱哈', titleEn: 'Yusuf and Zulaikha', author: '贾米', era: '1483', ring: 3, categorySlug: 'islam', summary: '波斯最后一位大诗人贾米,以优素福(约瑟)与祖莱哈的爱情寓言,阐苏菲"爱慕神"之道。', significance: '波斯古典诗歌最后高峰,苏菲爱情诗代表作。', difficulty: 3, oxStageMin: 4, oxStageMax: 10, readingMins: 70, tags: ['贾米', '优素福', '爱情寓言', '苏菲'], sortOrder: 806,
    chapters: [{ chapterNo: 1, title: '爱之火', originalText: '爱是永恒之火,一旦点燃不可熄灭。祖莱哈爱优素福至死不渝,正如灵魂爱真主。世俗之爱是神爱的影子,不可轻视,因为影子也指向光源。', commentary: '世俗之爱是神爱的预演。企业家对事业的激情若是真爱,则是更深使命的影子。', practiceHint: '今日问自己:我对公司的热情,背后更深的"爱"是什么?' }] },
  { slug: 'nafahat-uns', title: '亲近之香气', titleEn: 'Nafahat al-Uns', author: '贾米', era: '1476', ring: 3, categorySlug: 'islam', summary: '贾米汇编的苏菲圣人传记,收录600多位苏菲大师生平与言行,是苏菲史重要史料。', significance: '伊斯兰神秘主义史料汇编,苏菲传记学集大成之作。', difficulty: 3, oxStageMin: 5, oxStageMax: 10, readingMins: 90, tags: ['贾米', '苏菲圣人', '传记', '亲近'], sortOrder: 807,
    chapters: [{ chapterNo: 1, title: '巴耶济德的谦卑', originalText: '有人问巴耶济德:"你是怎么认识神的?"他答:"通过忘记自己。"又问:"这需要多久?"他答:"我花了三十年才学会不说我。"', commentary: '真正的领导力是三十年学会"不说我"。企业家的修炼在于让"我"越来越小。', practiceHint: '今天开会时统计自己用了多少次"我",下次尝试减半。' }] },
  { slug: 'iqbal-asrar-khudi', title: '自我之秘密', titleEn: 'Asrar-i Khudi', author: '伊克巴尔', era: '1915', ring: 3, categorySlug: 'islam', summary: '巴基斯坦国父伊克巴尔波斯语哲学诗,阐发"自我"(khudi)之哲学,融合伊斯兰与尼采。', significance: '南亚现代伊斯兰哲学代表作,巴基斯坦建国思想源头。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 70, tags: ['伊克巴尔', '自我', '现代伊斯兰', '哲学诗'], sortOrder: 808,
    chapters: [{ chapterNo: 1, title: '自我的强化', originalText: '生命的秘密在于强化自我,而不是湮灭自我。湮灭是终点,不是道路。一个强大的自我才能真正成为真主的仆人,因为只有真实存在的"我"才能真诚地说"我不是"。', commentary: '伊克巴尔颠覆传统苏菲"无我"论,主张先有强大自我再能超越。企业家先要"成为",才能"放下"。', practiceHint: '今日为自己设定一个不可妥协的底线,写下来贴在桌前。' }] },
  { slug: 'nasafi-insan-kamil', title: '完人论', titleEn: 'The Perfect Man', author: '阿齐兹丁·纳赛非', era: '13世纪', ring: 3, categorySlug: 'islam', summary: '纳赛非苏菲学著作,论"完人"(insan kamil)概念,融合伊本·阿拉比思想为通俗导论。', significance: '苏菲"完人论"入门经典,波斯苏菲文学简明代表。', difficulty: 4, oxStageMin: 6, oxStageMax: 10, readingMins: 60, tags: ['纳赛非', '完人', '苏菲', '波斯'], sortOrder: 809,
    chapters: [{ chapterNo: 1, title: '完人的四种品质', originalText: '完人有四种品质:好言、好行、好德、好知识。缺一不可。有言无行是伪君子,有行无德是机器,有德无知是愚忠,有知无言是冷漠。', commentary: '完人须言行德知四全。企业领导者亦然:说、做、品、智缺一则偏。', practiceHint: '今日自评四项,最薄弱的一项,这周刻意补强。' }] },
];

runScripturePatch('M38.34 经论++ v34 精修第二十四轮 — 伊斯兰苏菲深化', SC);
