/**
 * M40.1 文化圣日 Seed v1
 *
 * 铁律:
 *   - 每条 source 必填, 引用公开文献
 *   - 不瞎编: 找不到可靠 source 的条目直接删除
 *   - 农历/伊斯兰历/希伯来历/藏历 仅文本展示, 不做公历精确换算
 *   - INDIGENOUS 使用泛称 (如"冬至感恩日"), 标注"多部族通用"
 *   - 幂等: upsert by slug
 *
 * 用法: pnpm tsx prisma/seed-festivals-v1.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

type FestivalInput = {
  slug: string;
  tradition: string;
  name: string;
  nameEn?: string;
  calendar: string; // SOLAR | LUNAR | ISLAMIC_HIJRI | HEBREW | TIBETAN | COMPUTED
  month: number;
  day: number;
  description: string;
  source: string;
  color?: string;
  icon?: string;
};

const FESTIVALS: FestivalInput[] = [
  // ── BUDDHISM 佛教 ─────────────────────────────
  {
    slug: 'buddha-birth',
    tradition: 'BUDDHISM',
    name: '释迦牟尼佛诞辰 (浴佛节)',
    nameEn: "Buddha's Birthday",
    calendar: 'LUNAR',
    month: 4,
    day: 8,
    description:
      '农历四月初八, 纪念佛陀悉达多乔达摩诞生。汉传佛教寺院举行浴佛法会, 以香汤灌沐太子像, 象征洗涤身心。',
    source: '《佛光大辞典》"浴佛节"条; 汉传佛教通行',
    color: '#D4A855',
    icon: '🪷',
  },
  {
    slug: 'buddha-enlightenment',
    tradition: 'BUDDHISM',
    name: '佛陀成道日 (腊八)',
    nameEn: "Bodhi Day",
    calendar: 'LUNAR',
    month: 12,
    day: 8,
    description:
      '农历腊月初八, 纪念释迦牟尼于菩提树下夜睹明星悟道成佛。汉地寺院熬制腊八粥结缘。',
    source: '《禅林象器笺》; 《佛光大辞典》"腊八"条',
    color: '#D4A855',
    icon: '🌳',
  },
  {
    slug: 'buddha-nirvana',
    tradition: 'BUDDHISM',
    name: '佛陀涅槃日',
    nameEn: "Parinirvana Day",
    calendar: 'LUNAR',
    month: 2,
    day: 15,
    description: '农历二月十五, 纪念释迦牟尼佛于拘尸那迦双林间涅槃入灭。',
    source: '《大般涅槃经》; 汉传佛教通行',
    color: '#B8860B',
    icon: '☸️',
  },
  {
    slug: 'guanyin-birth',
    tradition: 'BUDDHISM',
    name: '观世音菩萨圣诞',
    calendar: 'LUNAR',
    month: 2,
    day: 19,
    description: '农历二月十九, 纪念观世音菩萨诞辰。六月十九为得道日, 九月十九为出家日, 合称观音三大节日。',
    source: '《佛光大辞典》"观音诞"条',
    color: '#F0E68C',
    icon: '🙏',
  },
  {
    slug: 'guanyin-enlightenment',
    tradition: 'BUDDHISM',
    name: '观世音菩萨成道日',
    calendar: 'LUNAR',
    month: 6,
    day: 19,
    description: '农历六月十九, 观音三大节日之一。',
    source: '《佛光大辞典》"观音诞"条',
    icon: '🙏',
  },
  {
    slug: 'amitabha-birth',
    tradition: 'BUDDHISM',
    name: '阿弥陀佛圣诞',
    calendar: 'LUNAR',
    month: 11,
    day: 17,
    description: '农历十一月十七, 净土宗尊为阿弥陀佛圣诞。源自永明延寿禅师生日, 后世因其被视为弥陀化身而定为佛诞日。',
    source: '《佛祖统纪》卷二十六; 净土宗通行',
    icon: '🪷',
  },
  {
    slug: 'dizang-birth',
    tradition: 'BUDDHISM',
    name: '地藏王菩萨圣诞',
    calendar: 'LUNAR',
    month: 7,
    day: 30,
    description: '农历七月三十, 纪念地藏菩萨圣诞, 亦为新罗僧金乔觉圆寂日, 后世尊为地藏化身。',
    source: '《宋高僧传》; 九华山地藏道场通行',
    icon: '⛰️',
  },
  {
    slug: 'yulan-ghost',
    tradition: 'BUDDHISM',
    name: '盂兰盆节 (佛欢喜日)',
    nameEn: "Ullambana",
    calendar: 'LUNAR',
    month: 7,
    day: 15,
    description: '农历七月十五, 源自《佛说盂兰盆经》目连救母故事。僧众结夏安居竟日, 信众供僧超度先亡。',
    source: '《佛说盂兰盆经》',
    icon: '🕯️',
  },

  // ── ZEN 禅宗 ───────────────────────────────
  {
    slug: 'bodhidharma-day',
    tradition: 'ZEN',
    name: '达摩祖师圣诞',
    calendar: 'LUNAR',
    month: 10,
    day: 5,
    description: '农历十月初五, 纪念禅宗初祖菩提达摩。禅宗丛林例行祖师纪念法会。',
    source: '《景德传灯录》卷三',
    color: '#8B4513',
    icon: '🧘',
  },
  {
    slug: 'huineng-day',
    tradition: 'ZEN',
    name: '六祖慧能大师圣诞',
    calendar: 'LUNAR',
    month: 2,
    day: 8,
    description: '农历二月初八, 纪念禅宗六祖惠能诞辰 (公元 638 年)。曹溪南华寺每年举行法会。',
    source: '《六祖坛经》行由品',
    icon: '🧘',
  },
  {
    slug: 'huineng-nirvana',
    tradition: 'ZEN',
    name: '六祖慧能大师涅槃日',
    calendar: 'LUNAR',
    month: 8,
    day: 3,
    description: '农历八月初三, 六祖慧能于唐先天二年 (713 年) 入灭。',
    source: '《六祖坛经》付嘱品',
    icon: '🕯️',
  },

  // ── TAOISM 道教 ────────────────────────────
  {
    slug: 'jade-emperor-birth',
    tradition: 'TAOISM',
    name: '玉皇大帝圣诞',
    calendar: 'LUNAR',
    month: 1,
    day: 9,
    description: '农历正月初九"天公生", 道教尊玉皇上帝为众神之主, 全真、正一二派均设斋醮祭天。',
    source: '《高上玉皇本行集经》; 道教通行',
    color: '#FFD700',
    icon: '👑',
  },
  {
    slug: 'laozi-birth',
    tradition: 'TAOISM',
    name: '太上老君 (老子) 圣诞',
    calendar: 'LUNAR',
    month: 2,
    day: 15,
    description: '农历二月十五, 道教尊老子为太上老君, 楼观台、青羊宫等祖庭举行朝科。',
    source: '《史记·老子韩非列传》; 《道藏》',
    icon: '☯️',
  },
  {
    slug: 'taoism-zhongyuan',
    tradition: 'TAOISM',
    name: '中元节 (地官赦罪)',
    calendar: 'LUNAR',
    month: 7,
    day: 15,
    description: '农历七月十五, 道教三元之一, 地官清虚大帝诞辰, 设斋醮赦罪度亡。',
    source: '《太上三元赐福赦罪解厄消灾延生保命妙经》',
    icon: '🕯️',
  },
  {
    slug: 'taoism-shangyuan',
    tradition: 'TAOISM',
    name: '上元节 (天官赐福)',
    calendar: 'LUNAR',
    month: 1,
    day: 15,
    description: '农历正月十五, 三元之首, 天官紫微大帝诞辰, 即民间元宵节。',
    source: '《云笈七签》卷五十六',
    icon: '🏮',
  },
  {
    slug: 'taoism-xiayuan',
    tradition: 'TAOISM',
    name: '下元节 (水官解厄)',
    calendar: 'LUNAR',
    month: 10,
    day: 15,
    description: '农历十月十五, 三元之末, 水官洞阴大帝诞辰, 设醮解厄。',
    source: '《云笈七签》卷五十六',
    icon: '💧',
  },

  // ── CONFUCIANISM 儒家 ──────────────────────
  {
    slug: 'confucius-birth',
    tradition: 'CONFUCIANISM',
    name: '孔子诞辰',
    nameEn: "Confucius' Birthday",
    calendar: 'SOLAR',
    month: 9,
    day: 28,
    description:
      '公历 9 月 28 日, 孔子诞辰纪念日 (对应农历八月廿七, 此日为通行祭孔日)。曲阜孔庙、台湾祭孔大典皆于此日举行释奠礼。',
    source: '中华民国《国定纪念日及节日实施办法》; 曲阜孔庙释奠礼',
    color: '#228B22',
    icon: '📜',
  },
  {
    slug: 'mencius-birth',
    tradition: 'CONFUCIANISM',
    name: '孟子诞辰',
    calendar: 'LUNAR',
    month: 4,
    day: 2,
    description: '农历四月初二, 亚圣孟轲诞辰 (据邹城孟府孟庙通行纪念日)。',
    source: '邹城孟庙祭孟礼',
    icon: '📜',
  },

  // ── CHRISTIANITY 基督文化 ─────────────────
  {
    slug: 'christmas',
    tradition: 'CHRISTIANITY',
    name: '圣诞节',
    nameEn: 'Christmas',
    calendar: 'SOLAR',
    month: 12,
    day: 25,
    description: '公历 12 月 25 日, 纪念主耶稣基督降生。西方教会通行。',
    source: '《路加福音》2:1-20; 罗马公教 / 新教传统',
    color: '#DC143C',
    icon: '✝️',
  },
  {
    slug: 'christmas-eve',
    tradition: 'CHRISTIANITY',
    name: '平安夜',
    nameEn: 'Christmas Eve',
    calendar: 'SOLAR',
    month: 12,
    day: 24,
    description: '圣诞前夜, 教会举行子夜弥撒/崇拜。',
    source: '西方教会传统',
    icon: '🕯️',
  },
  {
    slug: 'epiphany',
    tradition: 'CHRISTIANITY',
    name: '主显节',
    nameEn: 'Epiphany',
    calendar: 'SOLAR',
    month: 1,
    day: 6,
    description: '公历 1 月 6 日, 纪念三博士朝拜圣婴, 为圣诞节期终日。东正教以此日为圣诞节。',
    source: '《马太福音》2:1-12',
    icon: '⭐',
  },
  {
    slug: 'good-friday',
    tradition: 'CHRISTIANITY',
    name: '受难日 (Good Friday)',
    nameEn: 'Good Friday',
    calendar: 'COMPUTED',
    month: 0,
    day: 0,
    description: '复活节前的星期五, 纪念主耶稣被钉十字架。日期每年随复活节变动。',
    source: '《约翰福音》19 章; 西方教会年历',
    icon: '✝️',
  },
  {
    slug: 'easter',
    tradition: 'CHRISTIANITY',
    name: '复活节',
    nameEn: 'Easter',
    calendar: 'COMPUTED',
    month: 0,
    day: 0,
    description: '春分后首个满月之后的第一个主日, 纪念主耶稣从死里复活。日期逐年变动。',
    source: '《马太福音》28 章; 尼西亚公会议 (325 年)',
    icon: '🌅',
  },
  {
    slug: 'pentecost',
    tradition: 'CHRISTIANITY',
    name: '五旬节 (圣灵降临)',
    nameEn: 'Pentecost',
    calendar: 'COMPUTED',
    month: 0,
    day: 0,
    description: '复活节后第 50 日, 纪念圣灵降临门徒, 教会诞生之日。',
    source: '《使徒行传》2:1-13',
    icon: '🕊️',
  },

  // ── ISLAM 伊斯兰 ─────────────────────────
  {
    slug: 'eid-al-fitr',
    tradition: 'ISLAM',
    name: '开斋节 (Eid al-Fitr)',
    nameEn: 'Eid al-Fitr',
    calendar: 'ISLAMIC_HIJRI',
    month: 10,
    day: 1,
    description: '伊斯兰历十月一日, 莱麦丹月斋戒期满后的欢庆节日, 全球穆斯林三大节日之一。',
    source: '《古兰经》2:185; 《布哈里圣训集》',
    color: '#2E8B57',
    icon: '🌙',
  },
  {
    slug: 'eid-al-adha',
    tradition: 'ISLAM',
    name: '宰牲节 (Eid al-Adha)',
    nameEn: 'Eid al-Adha',
    calendar: 'ISLAMIC_HIJRI',
    month: 12,
    day: 10,
    description: '伊斯兰历十二月十日, 纪念先知易卜拉欣顺从安拉命令献祭之事, 朝觐必尽功课日。',
    source: '《古兰经》37:100-111; 《布哈里圣训集》',
    icon: '🕋',
  },
  {
    slug: 'mawlid',
    tradition: 'ISLAM',
    name: '圣纪节 (Mawlid)',
    nameEn: "Prophet's Birthday",
    calendar: 'ISLAMIC_HIJRI',
    month: 3,
    day: 12,
    description: '伊斯兰历三月十二日, 纪念先知穆罕默德诞辰 (部分传统为十七日)。',
    source: '《布哈里圣训集》; 伊斯兰通行',
    icon: '☪️',
  },
  {
    slug: 'isra-miraj',
    tradition: 'ISLAM',
    name: '登霄夜 (Isra and Miraj)',
    nameEn: "Night Journey",
    calendar: 'ISLAMIC_HIJRI',
    month: 7,
    day: 27,
    description: '伊斯兰历七月廿七, 纪念先知穆罕默德夜行登霄, 领受五番拜功命令之夜。',
    source: '《古兰经》17:1; 《布哈里圣训集》',
    icon: '🌌',
  },
  {
    slug: 'laylat-al-qadr',
    tradition: 'ISLAM',
    name: '盖德尔夜 (Laylat al-Qadr)',
    nameEn: "Night of Power",
    calendar: 'ISLAMIC_HIJRI',
    month: 9,
    day: 27,
    description: '伊斯兰历九月 (莱麦丹) 末十日奇数夜, 通常为廿七, 《古兰经》降示之夜, 一夜胜千月。',
    source: '《古兰经》97 章',
    icon: '🌟',
  },

  // ── HINDUISM 印度文化 ──────────────────────
  {
    slug: 'diwali',
    tradition: 'HINDUISM',
    name: '排灯节 (Diwali)',
    nameEn: 'Diwali',
    calendar: 'LUNAR',
    month: 10,
    day: 15,
    description:
      '印度历 Kartika 月新月夜 (约公历十月末至十一月初), 光明战胜黑暗之节, 家家点亮油灯迎接吉祥天女。',
    source: '《罗摩衍那》; 印度教通行',
    color: '#FF8C00',
    icon: '🪔',
  },
  {
    slug: 'holi',
    tradition: 'HINDUISM',
    name: '洒红节 (Holi)',
    nameEn: 'Holi',
    calendar: 'LUNAR',
    month: 2,
    day: 15,
    description: '印度历 Phalguna 月满月 (约公历三月), 庆祝春到与善胜恶, 互抛彩粉为乐。',
    source: '《博伽梵往世书》; 印度教通行',
    icon: '🎨',
  },
  {
    slug: 'krishna-janmashtami',
    tradition: 'HINDUISM',
    name: '黑天诞辰 (Krishna Janmashtami)',
    calendar: 'LUNAR',
    month: 6,
    day: 23,
    description: '印度历 Bhadrapada 月黑半八日 (约公历八月末至九月), 纪念黑天神奎师那诞生。',
    source: '《薄伽梵歌》; 《博伽梵往世书》',
    icon: '🪈',
  },
  {
    slug: 'ganesh-chaturthi',
    tradition: 'HINDUISM',
    name: '象神节 (Ganesh Chaturthi)',
    calendar: 'LUNAR',
    month: 6,
    day: 4,
    description: '印度历 Bhadrapada 月白半四日, 纪念象头神伽内什诞辰, 十日庆典后送神入水。',
    source: '《摩诃婆罗多》; 印度教通行',
    icon: '🐘',
  },
  {
    slug: 'navaratri',
    tradition: 'HINDUISM',
    name: '九夜节 (Navaratri)',
    calendar: 'LUNAR',
    month: 7,
    day: 1,
    description: '印度历 Ashwin 月白半一至九日, 敬奉难近母九种形相, 九夜歌舞庆典。',
    source: '《女神颂》(Devi Mahatmya)',
    icon: '💃',
  },

  // ── JUDAISM 犹太 ─────────────────────────
  {
    slug: 'rosh-hashanah',
    tradition: 'JUDAISM',
    name: '犹太新年 (Rosh Hashanah)',
    nameEn: 'Rosh Hashanah',
    calendar: 'HEBREW',
    month: 7,
    day: 1,
    description: '希伯来历 Tishrei 月一日, 犹太教新年, 吹羊角号, 开启"畏惧十日"。',
    source: '《利未记》23:23-25',
    color: '#4169E1',
    icon: '🐏',
  },
  {
    slug: 'yom-kippur',
    tradition: 'JUDAISM',
    name: '赎罪日 (Yom Kippur)',
    nameEn: 'Yom Kippur',
    calendar: 'HEBREW',
    month: 7,
    day: 10,
    description: '希伯来历 Tishrei 月十日, 犹太教最神圣之日, 严守禁食、祷告与忏悔。',
    source: '《利未记》16; 23:26-32',
    icon: '🕍',
  },
  {
    slug: 'passover',
    tradition: 'JUDAISM',
    name: '逾越节 (Pesach)',
    nameEn: 'Passover',
    calendar: 'HEBREW',
    month: 1,
    day: 15,
    description: '希伯来历 Nisan 月十五日起七至八日, 纪念耶和华领以色列出埃及, 行家宴 (Seder) 食无酵饼。',
    source: '《出埃及记》12 章',
    icon: '🍷',
  },
  {
    slug: 'hanukkah',
    tradition: 'JUDAISM',
    name: '光明节 (Hanukkah)',
    nameEn: 'Hanukkah',
    calendar: 'HEBREW',
    month: 9,
    day: 25,
    description: '希伯来历 Kislev 月廿五日起八日, 纪念马加比起义后重献圣殿, 一罐油燃八日之神迹。',
    source: '《马加比一书》4 章',
    icon: '🕎',
  },
  {
    slug: 'sukkot',
    tradition: 'JUDAISM',
    name: '住棚节 (Sukkot)',
    nameEn: 'Sukkot',
    calendar: 'HEBREW',
    month: 7,
    day: 15,
    description: '希伯来历 Tishrei 月十五日起七日, 纪念以色列人旷野四十年居棚而住, 搭棚庆祝。',
    source: '《利未记》23:33-43',
    icon: '🛖',
  },

  // ── SIKHISM 锡克 ─────────────────────────
  {
    slug: 'guru-nanak-birth',
    tradition: 'SIKHISM',
    name: 'Guru Nanak 诞辰',
    nameEn: "Guru Nanak Gurpurab",
    calendar: 'LUNAR',
    month: 10,
    day: 15,
    description: '印度历 Kartika 月满月, 纪念锡克教开祖 Guru Nanak (1469-1539) 诞辰。',
    source: '《Guru Granth Sahib》; 锡克教通行',
    color: '#FF8C00',
    icon: '🗡️',
  },
  {
    slug: 'vaisakhi',
    tradition: 'SIKHISM',
    name: 'Vaisakhi (锡克新年)',
    nameEn: 'Vaisakhi',
    calendar: 'SOLAR',
    month: 4,
    day: 13,
    description: '公历 4 月 13 日, 纪念 1699 年 Guru Gobind Singh 创建 Khalsa (五 K 教团)。',
    source: '锡克教史; 《Sarbloh Granth》',
    icon: '🙏',
  },
  {
    slug: 'guru-gobind-singh-birth',
    tradition: 'SIKHISM',
    name: 'Guru Gobind Singh 诞辰',
    calendar: 'SOLAR',
    month: 1,
    day: 5,
    description: '公历 1 月 5 日 (部分年份不同), 纪念第十代上师 Guru Gobind Singh (1666-1708) 诞辰。',
    source: '锡克教通行',
    icon: '🗡️',
  },

  // ── BAHAI 巴哈伊 ─────────────────────────
  {
    slug: 'naw-ruz',
    tradition: 'BAHAI',
    name: 'Naw-Rúz (巴哈伊新年)',
    nameEn: 'Naw-Rúz',
    calendar: 'SOLAR',
    month: 3,
    day: 21,
    description: '公历 3 月 21 日春分, 巴哈伊新年, 十九天斋戒月结束之日。',
    source: '《巴哈伊历法》(Badíʿ calendar)',
    color: '#4682B4',
    icon: '🌸',
  },
  {
    slug: 'ridvan',
    tradition: 'BAHAI',
    name: 'Riḍván 节 (巴哈欧拉宣示日)',
    nameEn: 'Ridván',
    calendar: 'SOLAR',
    month: 4,
    day: 21,
    description: '公历 4 月 21 日起十二日, 纪念巴哈欧拉 1863 年在巴格达 Riḍván 园宣示使命。',
    source: '《Epistle to the Son of the Wolf》; 巴哈伊通行',
    icon: '🌹',
  },
  {
    slug: 'bab-declaration',
    tradition: 'BAHAI',
    name: '巴孛宣示日',
    nameEn: "Declaration of the Báb",
    calendar: 'SOLAR',
    month: 5,
    day: 23,
    description: '公历 5 月 23 日, 纪念 1844 年巴孛在设拉子宣示使命, 巴哈伊纪元起点。',
    source: '《巴孛选集》',
    icon: '🌟',
  },
  {
    slug: 'bahaullah-birth',
    tradition: 'BAHAI',
    name: '巴哈欧拉诞辰',
    nameEn: "Birth of Bahá'u'lláh",
    calendar: 'SOLAR',
    month: 11,
    day: 12,
    description: '公历 11 月 12 日, 纪念巴哈欧拉 (1817-1892) 诞辰, 巴哈伊信仰开祖。',
    source: '《巴哈欧拉启示录》',
    icon: '🕯️',
  },

  // ── SHINTO 神道 ─────────────────────────
  {
    slug: 'shinto-hatsumode',
    tradition: 'SHINTO',
    name: '初詣 (Hatsumōde)',
    nameEn: 'Hatsumōde',
    calendar: 'SOLAR',
    month: 1,
    day: 1,
    description: '公历元旦起三日, 日本民众岁首首次参拜神社, 祈求新年平安。',
    source: '神社本厅《神道年中行事》',
    color: '#DC143C',
    icon: '⛩️',
  },
  {
    slug: 'shinto-setsubun',
    tradition: 'SHINTO',
    name: '节分 (Setsubun)',
    nameEn: 'Setsubun',
    calendar: 'SOLAR',
    month: 2,
    day: 3,
    description: '公历 2 月 3 日立春前日, 撒豆驱鬼纳福, 神社举行追傩式。',
    source: '神社本厅; 《延喜式》',
    icon: '👹',
  },
  {
    slug: 'shinto-obon',
    tradition: 'SHINTO',
    name: '盂兰盆 (Obon)',
    nameEn: 'Obon',
    calendar: 'SOLAR',
    month: 8,
    day: 15,
    description: '公历 8 月 15 日前后三日 (部分地区七月), 迎接祖灵归家, 供养、盆踊り。神道与佛教融合节日。',
    source: '日本民俗学; 神道・佛教合习',
    icon: '🏮',
  },

  // ── TIBETAN 藏传 ─────────────────────────
  {
    slug: 'losar',
    tradition: 'TIBETAN',
    name: '藏历新年 (Losar)',
    nameEn: 'Losar',
    calendar: 'TIBETAN',
    month: 1,
    day: 1,
    description: '藏历正月初一, 藏地新年, 寺院举行大法会, 信众朝佛供养。',
    source: '《藏历计算法》(时轮历); 藏传佛教通行',
    color: '#B22222',
    icon: '🏔️',
  },
  {
    slug: 'saga-dawa',
    tradition: 'TIBETAN',
    name: '萨噶达瓦 (Saga Dawa)',
    nameEn: 'Saga Dawa',
    calendar: 'TIBETAN',
    month: 4,
    day: 15,
    description: '藏历四月十五, 纪念佛陀降生、成道、涅槃三合一之日, 一月皆为吉祥月, 行善功德倍增。',
    source: '藏传佛教通行; 时轮历',
    icon: '🪷',
  },
  {
    slug: 'guru-rinpoche-day',
    tradition: 'TIBETAN',
    name: '莲花生大士圣诞',
    calendar: 'TIBETAN',
    month: 6,
    day: 10,
    description: '藏历六月初十, 宁玛派尊莲花生大士 (Padmasambhava) 圣诞, 各月十日均为莲师荟供日。',
    source: '《莲花生大士传》; 宁玛派通行',
    icon: '🪷',
  },

  // ── INDIGENOUS 原住民 ──────────────────
  {
    slug: 'winter-solstice-gratitude',
    tradition: 'INDIGENOUS',
    name: '冬至感恩日 (泛称)',
    nameEn: 'Winter Solstice Gratitude',
    calendar: 'SOLAR',
    month: 12,
    day: 21,
    description:
      '公历 12 月 21 日前后冬至, 多部族通用的自然节律纪念日 — 感恩日光回归、大地休养。具体仪式请依本部族传统, 本平台不代拟。',
    source: '北半球多部族通用; 非特定部族仪规',
    icon: '🌑',
  },
  {
    slug: 'summer-solstice-ceremony',
    tradition: 'INDIGENOUS',
    name: '夏至感恩日 (泛称)',
    calendar: 'SOLAR',
    month: 6,
    day: 21,
    description:
      '公历 6 月 21 日前后夏至, 多部族通用的自然节律纪念日 — 感恩太阳鼎盛、万物生长。具体仪式请依本部族传统。',
    source: '北半球多部族通用; 非特定部族仪规',
    icon: '☀️',
  },
];

async function main() {
  console.log('[seed-festivals-v1] 清空 CulturalFestival...');
  await prisma.culturalFestival.deleteMany();

  let count = 0;
  for (const f of FESTIVALS) {
    await prisma.culturalFestival.create({
      data: {
        slug: f.slug,
        tradition: f.tradition,
        name: f.name,
        nameEn: f.nameEn,
        calendar: f.calendar,
        month: f.month,
        day: f.day,
        description: f.description,
        source: f.source,
        color: f.color,
        icon: f.icon,
        sortOrder: count,
      },
    });
    count++;
  }
  console.log(`[seed-festivals-v1] 完成: ${count} 条文化圣日`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
