/**
 * seed-personal-growth.ts — 企业家个人圆满 6大主题包
 * 独立执行: npx ts-node prisma/seed-personal-growth.ts
 * 或由主 seed 调用
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const PERSONAL_THEMES = [
  // ═══════════════════════════════════════════════════════════
  // #1 觉醒之旅 — 创业者初心回溯
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'pg-awakening',
    title: '觉醒之旅',
    subtitle: '放下手机三天，找回创业初心',
    description:
      '在禅宗祖庭的钟声中，帮助被"忙碌陷阱"困住的创业者回到原点——你为什么出发？三天断舍离，从信息过载中解脱，在面壁中直面内心。不是鸡汤，是一面镜子。',
    color: '#D4A855',
    icon: '🌅',
    coverUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200',
    keywords: ['初心', '觉醒', '断舍离'],
    holySites: ['shaolin-temple', 'bodhidharma-cave'],
    routes: [],
    rituals: [
      { name: '黎明禅坐', durationMin: 45, description: '5:00起，跟随禅堂主持师父静坐一炷香，学习数息观法' },
      { name: '面壁三省', durationMin: 60, description: '在达摩面壁洞独坐一小时，用三个问题审视自己：为何出发？走到哪了？还要去哪？' },
      { name: '断舍离仪式', durationMin: 30, description: '交出手机、手表、名片，只留白纸一张，写下真正重要的三件事' },
      { name: '行禅·嵩山径', durationMin: 90, description: '沿嵩山古道行禅，每步配合呼吸，在行走中消融思虑' },
      { name: '禅茶一味', durationMin: 45, description: '与住持品茶论道，不谈商业只谈人生' },
      { name: '抄经静心', durationMin: 60, description: '手抄《心经》260字，在一笔一划中感受专注的力量' },
      { name: '篝火自白', durationMin: 90, description: '山间篝火夜话，与同行者分享最脆弱的时刻和最真实的恐惧' },
    ],
    richContent: {
      dimension: { code: 'PG-01', label: '自我认知维度', kicker: '最难的创业不是做产品，是看见自己' },
      entrepreneurPainPoint: {
        title: '你是不是陷入了"忙碌陷阱"？',
        body: '80%的创业者在公司做到第3-5年时，会陷入一种奇怪的状态：明明很忙，但感觉不到意义；明明在前进，但不知道为什么出发。你开始怀疑：这真的是我想要的吗？这不是懒惰，这是你的内心在呼唤觉醒。',
        signs: [
          '每天工作12小时，但躺下后感觉什么都没做',
          '害怕独处，一停下来就焦虑',
          '已经记不清最初创业时的那个念头',
          '越来越多地用"应该"而不是"想要"做决策',
          '身体发出警告信号——失眠、胃痛、莫名疲惫',
        ],
        stage: '创业初期·成长期',
      },
      philosophy: {
        title: '禅宗的答案：直指人心，见性成佛',
        body: '1500年前，达摩面壁九年，不是在等待什么，而是在放下一切。禅宗的核心不是修行苦功，而是"直指"——绕过所有概念和标签，直接看见真实的自己。对创业者来说，这意味着放下"CEO"的面具、"成功者"的人设，回到最初那个有热情的普通人。',
        quotes: [
          { source: '《六祖坛经》', text: '菩提本无树，明镜亦非台。本来无一物，何处惹尘埃。', translation: '智慧不需要外求，自性本自清净' },
          { source: '达摩祖师', text: '不立文字，教外别传，直指人心，见性成佛。', translation: '答案不在书里，在你心里' },
          { source: '临济义玄', text: '逢佛杀佛，逢祖杀祖。', translation: '破除一切外在权威，找到内在确信' },
          { source: '赵州从谂', text: '吃茶去。', translation: '最深的修行就在最平常的日常里' },
        ],
      },
      dailyItinerary: [
        {
          day: 1,
          title: '入山·放下',
          location: '少林寺·禅堂',
          dawn: '5:00 早课钟声中苏醒，跟随僧众上早课',
          morning: '开营仪式：交出电子设备，换上素衣。住持开示"何为觉醒"。参观达摩洞，了解面壁九年的真实故事。',
          afternoon: '第一次禅坐教学（坐姿、呼吸、心法）。断舍离仪式：写下并烧掉"不再需要的身份标签"。',
          evening: '药石(晚餐)后山间散步。第一夜：在绝对安静中入睡。',
          soloTime: '19:30-21:00 独处时间，只有一支蜡烛一张纸',
          rituals: ['断舍离仪式', '黎明禅坐'],
        },
        {
          day: 2,
          title: '面壁·直视',
          location: '达摩面壁洞·嵩山',
          dawn: '4:30 禅堂早坐，体验"动中禅"',
          morning: '徒步至达摩面壁洞（约40分钟山路）。在洞中独坐一小时，面壁三省。',
          afternoon: '行禅嵩山径：90分钟步行冥想。下山后抄经《心经》全文。',
          evening: '篝火自白：每人15分钟，讲述"最失败的那一天"和"为什么还在坚持"。',
          soloTime: '抄经后30分钟独处反思',
          rituals: ['面壁三省', '行禅·嵩山径', '抄经静心', '篝火自白'],
        },
        {
          day: 3,
          title: '回归·重启',
          location: '少林寺·方丈室',
          dawn: '5:00 最后一次禅坐，导师引导"带着觉醒回到世界"',
          morning: '与住持禅茶论道：一对一30分钟，讨论你的"觉醒问题"。写下《初心宣言》。',
          afternoon: '结营仪式：取回电子设备，但先读一遍自己写下的"三件重要的事"。合影、颁发觉醒证书。',
          evening: '启程返回——带着一份初心宣言和七天跟踪计划',
          soloTime: '晨间独处30分钟，写初心宣言',
          rituals: ['禅茶一味'],
        },
      ],
      mentorProfile: {
        name: '释延觉法师',
        title: '少林寺禅修导师·企业家禅修营创始人',
        bio: '少林寺弟子，曾在华尔街工作8年后出家。20年禅修经验，专注"商禅融合"教学。累计指导过200+企业家完成觉醒之旅。他说："我理解创业者的痛，因为我曾经就是其中一员。"',
        expertise: ['商禅融合', '压力管理', '决策心理'],
        philosophy: '修行不是逃避世界，是更清醒地回到世界',
      },
      transformationPath: [
        '第1天：从"我应该"到"我是谁"——放下角色面具',
        '第2天：从"不敢面对"到"直视恐惧"——在面壁中看见真实',
        '第3天：从"迷茫"到"清晰"——带着初心宣言重新出发',
        '第7天(回程后)：线上导师回访，检查初心宣言执行情况',
        '第30天：一封写给自己的信，对照觉醒时刻的感悟',
      ],
      targetAudience: [
        '创业3-5年，感觉"忙但空虚"的创始人',
        '刚经历重大决策失误需要重新校准方向的CEO',
        '身体频繁发出警告信号的高压企业家',
        '想要"暂停键"但不知道怎么按下的连续创业者',
      ],
      testimonials: [
        {
          name: '张明远',
          role: '某科技公司创始人',
          company: '深圳·200人团队',
          quote: '面壁洞里那一小时，我哭了。不是难过，是终于允许自己脆弱了。',
          before: '连续3年每天工作14小时，失眠严重，与家人关系紧张',
          after: '回来后砍掉了3条不赚钱的业务线，每周给自己留一天"什么都不做"的时间',
        },
        {
          name: '李思琪',
          role: '连锁品牌联合创始人',
          company: '杭州·500+门店',
          quote: '篝火夜话那晚，我第一次对别人说出"我不知道自己在做什么"。说出来那一刻，答案就出现了。',
          before: '公司上市在即，却越来越怀疑这是不是自己想要的',
          after: '推迟上市6个月，重新梳理了公司使命，团队反而更有凝聚力',
        },
      ],
      gallery: [
        'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800',
        'https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=800',
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      ],
    },
    priceFrom: 188000,
    durationDays: 3,
    sortOrder: 10,
  },

  // ═══════════════════════════════════════════════════════════
  // #2 定力之旅 — 决策者心智锻造
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'pg-fortitude',
    title: '定力之旅',
    subtitle: '在武当山修炼"不动心"，成为风暴中的锚',
    description:
      '市场暴跌、核心高管离职、产品召回……企业家面对的风暴从不停歇。道家修炼不是教你无情，而是教你在混沌中找到"不动点"。四天武当山+青城山，太极·辟谷·呼吸法，锻造你的"定力根基"。',
    color: '#6B8E6B',
    icon: '🏔️',
    coverUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200',
    keywords: ['定力', '心智', '不动心'],
    holySites: ['wudang-mountains', 'qingcheng-mountain'],
    routes: [],
    rituals: [
      { name: '晨起太极', durationMin: 60, description: '随武当道长习练太极十三式，在松柔中体会"以柔克刚"' },
      { name: '辟谷体验', durationMin: 480, description: '第2天全天辟谷(仅饮水+果蔬汁)，体验"减法"的力量' },
      { name: '道家呼吸法', durationMin: 40, description: '学习"吐故纳新"呼吸法，调整自主神经，即时降低焦虑' },
      { name: '悬崖站桩', durationMin: 30, description: '在武当南岩宫悬崖边站桩，在恐惧中找到身体的"定点"' },
      { name: '道德经默读', durationMin: 45, description: '在紫霄宫静室默读《道德经》关键篇章，逐句参悟商道' },
      { name: '星空冥想', durationMin: 60, description: '武当山金顶星空下冥想，在宇宙尺度中重新定义"大与小"' },
    ],
    richContent: {
      dimension: { code: 'PG-02', label: '心智韧性维度', kicker: '真正的强不是不怕，是怕了也能做决定' },
      entrepreneurPainPoint: {
        title: '你的决策正在被情绪绑架吗？',
        body: '当市场波动时你会失眠吗？当竞争对手出招时你会恐慌性反应吗？当团队出问题时你会愤怒决策吗？70%的企业战略失误源于CEO在压力下的情绪化决策。定力不是天赋，是可以训练的能力。',
        signs: [
          '重大决策前夜必失眠，起床后还是犹豫不决',
          '一条负面新闻就能让你焦虑一整天',
          '对团队的反应越来越暴躁，事后又后悔',
          '总觉得自己在"救火"，从来没有主动权',
          '身体越来越紧绷——肩膀硬、下巴咬紧、浅呼吸',
        ],
        stage: '成长期·成熟期',
      },
      philosophy: {
        title: '道家的答案：上善若水，不争而胜',
        body: '道家修炼的核心不是"变强"，而是"回到本然"。水为什么无敌？因为它不跟任何东西对抗，它绕过、渗透、等待。太极为什么以柔克刚？因为真正的力量不是硬抗，是顺势。对企业家来说，定力的本质不是"忍"，是"看清局势后的从容"。',
        quotes: [
          { source: '《道德经》第八章', text: '上善若水。水善利万物而不争，处众人之所恶，故几于道。', translation: '最好的领导像水一样，滋养万物但不争功' },
          { source: '《道德经》第七十六章', text: '坚强者死之徒，柔弱者生之徒。', translation: '硬撑的企业会死，柔韧的企业能活' },
          { source: '《庄子·逍遥游》', text: '至人无己，神人无功，圣人无名。', translation: '放下自我执着，反而能成就更大的事业' },
          { source: '张三丰', text: '太极者，无极而生，动静之机，阴阳之母也。', translation: '在动静转换中找到平衡，就是太极的商业智慧' },
        ],
      },
      dailyItinerary: [
        {
          day: 1,
          title: '入山·松身',
          location: '武当山·紫霄宫',
          dawn: '5:30 道观晨钟，起身做八段锦热身',
          morning: '开营仪式：道长讲解"定力三层"——身定、心定、神定。学习太极十三式基础。',
          afternoon: '道家呼吸法教学。紫霄宫静室读《道德经》选章。',
          evening: '清淡素斋后山间漫步，为明天辟谷做心理准备。',
          soloTime: '20:00-21:30 独坐听松涛',
          rituals: ['晨起太极', '道家呼吸法', '道德经默读'],
        },
        {
          day: 2,
          title: '辟谷·减法',
          location: '武当山·南岩宫',
          dawn: '5:00 辟谷日开始，仅饮温水和少量果蔬汁',
          morning: '太极晨练(空腹更能体会气感)。徒步至南岩宫，沿途行禅。',
          afternoon: '悬崖站桩：在南岩宫绝壁边站桩30分钟，直面恐惧。辟谷中的身体对话。',
          evening: '道长1对1谈话：聊聊你最害怕失去的东西是什么。',
          soloTime: '全天辟谷本身就是深度独处',
          rituals: ['辟谷体验', '晨起太极', '悬崖站桩'],
        },
        {
          day: 3,
          title: '复食·觉察',
          location: '武当山·金顶',
          dawn: '5:00 登金顶看日出(约90分钟徒步)',
          morning: '金顶日出冥想。复食仪式：一碗清粥，感受饥饿后第一口食物的力量。',
          afternoon: '太极推手实战：在对抗中体会"听劲"——不是用力，是用觉察。定力工作坊：商业场景模拟决策。',
          evening: '星空冥想：在金顶星空下，重新定义什么是"大事"。',
          soloTime: '冥想后自由时间直到入睡',
          rituals: ['晨起太极', '星空冥想'],
        },
        {
          day: 4,
          title: '下山·带走',
          location: '武当山·玄岳门',
          dawn: '最后一次太极晨练——此时你已能独立完成十三式',
          morning: '定力宣言：写下《我的不动点》——三个承诺。道长赐道号+结业仪式。',
          afternoon: '下山返程。带走：一套太极视频教学+30天呼吸法训练计划+道长微信(可远程问道)',
          evening: '',
          soloTime: '',
          rituals: ['晨起太极'],
        },
      ],
      mentorProfile: {
        name: '陈师行道长',
        title: '武当三丰派传人·企业家定力教练',
        bio: '武当山道士，太极拳第十五代传人。曾为多家上市公司董事长做私人"定力教练"。他的教学风格直接犀利："你连站桩30分钟都做不到，怎么在董事会上坐得住？"',
        expertise: ['太极心法', '压力释放', '决策定力'],
        philosophy: '定力不是忍，是清楚地知道什么值得动，什么不值得动',
      },
      transformationPath: [
        '第1天：从"紧绷"到"松开"——身体先放松，心才能定',
        '第2天：从"害怕失去"到"接受无常"——辟谷教你什么是真正需要的',
        '第3天：从"用力"到"用心"——太极推手改变你的对抗模式',
        '第4天：从"学到"到"带走"——把定力变成日常习惯',
        '第30天：线上回访，检查定力宣言执行情况',
      ],
      targetAudience: [
        '经常在压力下做出"后悔决策"的CEO',
        '身体长期紧绷、失眠、焦虑的企业领导者',
        '正在经历公司重大转型期的决策者',
        '想要提升"情绪稳定性"的管理者',
      ],
      testimonials: [
        {
          name: '王建国',
          role: '某制造业集团董事长',
          company: '东莞·2000人工厂',
          quote: '辟谷那天我才知道，很多恐惧是想象出来的。饿了一天，世界并没有崩塌。',
          before: '公司遭遇原材料暴涨，每天焦虑到胃痛，团队被他的情绪搞得人人自危',
          after: '回来后第一件事是开了一个"坏消息会"——专门讨论最坏情况。团队反而安心了',
        },
      ],
      gallery: [
        'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800',
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
        'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
        'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800',
      ],
    },
    priceFrom: 228000,
    durationDays: 4,
    sortOrder: 20,
  },

  // ═══════════════════════════════════════════════════════════
  // #3 格局之旅 — 从管理者到领袖
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'pg-vision',
    title: '格局之旅',
    subtitle: '在孔庙悟"修齐治平"，从管事到管心',
    description:
      '2500年前孔子带着理想周游列国，今天你带着困惑走进孔庙。从"管理100人"到"影响10000人"，需要的不是更多MBA技巧，而是格局的跃迁——修身、齐家、治国、平天下。三天曲阜+白鹿洞书院，在书香中找到"领袖气象"。',
    color: '#8B4513',
    icon: '📜',
    coverUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200',
    keywords: ['格局', '领袖', '修齐治平'],
    holySites: ['confucius-temple-qufu', 'white-deer-grotto-academy'],
    routes: [],
    rituals: [
      { name: '祭孔晨礼', durationMin: 40, description: '参加孔庙传统祭孔仪式，体会"礼"的力量' },
      { name: '经典晨读', durationMin: 60, description: '在书院朗读《大学》"修齐治平"章，逐句讨论商业应用' },
      { name: '书院夜话', durationMin: 90, description: '围炉夜谈，以古论今：讨论"一个领袖应该读什么书、交什么人、做什么事"' },
      { name: '君子六艺', durationMin: 120, description: '体验礼、乐、射、御、书、数——古代领袖的"全人教育"' },
      { name: '手书家训', durationMin: 60, description: '用毛笔书写自己的"企业家训"，装裱带走' },
    ],
    richContent: {
      dimension: { code: 'PG-03', label: '战略格局维度', kicker: '管理是让别人做事，领导力是让别人想做事' },
      entrepreneurPainPoint: {
        title: '你还在"管事"而不是"管心"吗？',
        body: '公司从10人到100人，你靠勤奋。从100人到1000人，你需要格局。很多企业家卡在"事必躬亲"到"运筹帷幄"的转折点：放手怕出错，不放手累死自己。这不是能力问题，是"领袖心性"还没养成。',
        signs: [
          '公司离了你就运转不了，你出差三天就出问题',
          '高管总说"老板你定"，没人敢做决策',
          '你是公司最忙的人，但战略越来越模糊',
          '读了很多管理书，但感觉越来越"技巧化"，少了真正的影响力',
          '开始怀疑自己到底是在做企业还是在打一份高级工',
        ],
        stage: '成长期·成熟期',
      },
      philosophy: {
        title: '儒家的答案：修身为本，格局天成',
        body: '《大学》说"自天子以至于庶人，壹是皆以修身为本"。格局不是学来的，是修来的。一个人内在有多宽广，外在就能影响多远。孔子为什么能影响2500年？不是因为他有权力，而是因为他有"人格的重力场"。',
        quotes: [
          { source: '《大学》', text: '修身、齐家、治国、平天下。', translation: '领袖力的根基是自我修炼' },
          { source: '《论语》', text: '其身正，不令而行；其身不正，虽令不从。', translation: '以身作则胜过一万条制度' },
          { source: '《孟子》', text: '穷则独善其身，达则兼济天下。', translation: '格局随境遇伸缩，但修身永远是底线' },
          { source: '王阳明', text: '知行合一，致良知。', translation: '真正的知识是在行动中检验的' },
        ],
      },
      dailyItinerary: [
        {
          day: 1,
          title: '入学·正心',
          location: '曲阜孔庙·杏坛',
          dawn: '6:00 祭孔晨礼',
          morning: '开营：在杏坛(孔子讲学处)举行拜师礼。参访孔庙、孔林，了解孔子的"创业故事"。',
          afternoon: '经典研读：《大学》"修齐治平"章逐句解读+商业应用讨论。写下"格局自评表"。',
          evening: '书院夜话第一夜：你心目中的"伟大企业家"是谁？他们的格局从哪来？',
          soloTime: '22:00后独处反思',
          rituals: ['祭孔晨礼', '经典晨读', '书院夜话'],
        },
        {
          day: 2,
          title: '修艺·养气',
          location: '白鹿洞书院(庐山)',
          dawn: '6:00 晨读《论语》选章',
          morning: '君子六艺体验上午场：射箭(专注力)、书法(定力)、古琴(气质)。',
          afternoon: '领袖力工作坊：从"事必躬亲"到"知人善任"的路径设计。手书企业家训。',
          evening: '书院夜话第二夜：如果你的公司是一个"国"，你是什么样的"君"？',
          soloTime: '六艺体验中有独立练习环节',
          rituals: ['经典晨读', '君子六艺', '手书家训', '书院夜话'],
        },
        {
          day: 3,
          title: '立志·出山',
          location: '白鹿洞书院',
          dawn: '最后一次晨读',
          morning: '格局宣言：每人10分钟演讲——"未来十年，我要成为什么样的领袖"。导师逐一点评。',
          afternoon: '结业仪式：颁发"君子证书"。交付物：企业家训装裱+格局行动计划+经典阅读清单。',
          evening: '返程',
          soloTime: '晨间30分钟准备演讲',
          rituals: ['经典晨读'],
        },
      ],
      mentorProfile: {
        name: '曲承恩教授',
        title: '曲阜师范大学国学院教授·企业家经典导师',
        bio: '孔子第78代传人(旁系)，国学教育30年。独创"经典商道"教学法，将四书五经中的智慧转化为现代企业管理工具。他说："孔子如果活在今天，一定是最好的CEO教练。"',
        expertise: ['经典商道', '领袖修养', '儒商文化'],
        philosophy: '格局不是想出来的，是在经典浸润和自我修炼中慢慢养出来的',
      },
      transformationPath: [
        '第1天：从"我在管公司"到"我在修自己"——格局始于修身',
        '第2天：从"技巧派"到"修养派"——六艺中找到领袖的底层素养',
        '第3天：从"今天的CEO"到"百年的传承者"——用格局宣言定义你的十年',
        '第14天：线上读书会，导师带读《论语》选章',
        '第30天：格局行动计划第一阶段检查',
      ],
      targetAudience: [
        '公司从100人到1000人的"卡点"期CEO',
        '感觉自己"技巧很多但格局不够"的管理者',
        '想要从"做企业"升级为"做事业"的创始人',
        '对传统文化感兴趣但不知如何应用于商业的企业家',
      ],
      testimonials: [
        {
          name: '陈伟华',
          role: '某互联网公司CEO',
          company: '北京·500人团队',
          quote: '在孔庙站了10分钟，突然明白了——我不是在"管"500人，我是在"养"一种文化。',
          before: '公司增长停滞，高管轮流离职，自己快被细节淹没',
          after: '回来后设立了"文化委员会"，自己只抓战略和人才，一年内公司增长40%',
        },
      ],
      gallery: [
        'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
        'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800',
        'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800',
        'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
      ],
    },
    priceFrom: 168000,
    durationDays: 3,
    sortOrder: 30,
  },

  // ═══════════════════════════════════════════════════════════
  // #4 重生之旅 — 中年危机突破
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'pg-rebirth',
    title: '重生之旅',
    subtitle: '在文化之旅路上走过"半生已过"的焦虑',
    description:
      '45岁后的企业家，最大的敌人不是竞争对手，而是"意义感缺失"。你拥有了一切——公司、房子、车子——但夜深人静时问自己"然后呢？"。重生之旅带你走上文化探访者之路，在行走中卸下半生的重量，在耶路撒冷/梵蒂冈找到"下半场"的力量。',
    color: '#7B3F00',
    icon: '🕊️',
    coverUrl: 'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=1200',
    keywords: ['重生', '中年突破', '文化之旅'],
    holySites: ['church-of-the-holy-sepulchre', 'via-dolorosa', 'vatican-city'],
    routes: [],
    rituals: [
      { name: '文化探访者启程礼', durationMin: 30, description: '在出发前写下"我要放下的三件事"，封入信封，旅程结束时打开' },
      { name: '苦路徒步', durationMin: 180, description: '走完耶路撒冷苦路十四站，每站停留反思一个人生转折点' },
      { name: '哭墙祈祷', durationMin: 60, description: '在哭墙前写下最深的愿望，塞入墙缝——不是求财求运，是对灵魂的祈愿' },
      { name: '生命叙事', durationMin: 120, description: '用"英雄之旅"模型重新讲述自己的人生故事：出发→试炼→至暗→觉醒→归来' },
      { name: '重生仪式', durationMin: 45, description: '在圣墓教堂点燃一根蜡烛，象征"旧我"的告别和"新我"的诞生' },
    ],
    richContent: {
      dimension: { code: 'PG-04', label: '生命重塑维度', kicker: '半生已过，恰好是重新开始最好的时候' },
      entrepreneurPainPoint: {
        title: '你正在经历"成功之后的空虚"吗？',
        body: '心理学有个术语叫"到达谬误"(Arrival Fallacy)——你以为达到目标就会快乐，达到后发现并没有。很多45+企业家在"成功"后坠入更深的迷茫：钱够了，但不知道为什么还在拼；公司稳了，但自己的人生开始动摇。',
        signs: [
          '公司很好，但你对它越来越没有热情',
          '开始频繁地想"如果当年……"',
          '对同龄人的"成功"感到厌倦，包括自己的',
          '健康检查报告越来越长，但你不愿面对',
          '夜里3点醒来，想的不是公司，是"这辈子到底算什么"',
        ],
        stage: '成熟期·巅峰期',
      },
      philosophy: {
        title: '基督文化的答案：死亡与复活——每个终点都是起点',
        body: '基督文化的核心叙事不是"一帆风顺"，而是"死亡与复活"。耶稣走过苦路，经历十字架，然后复活。这个故事2000年来给了无数人力量——因为它说的是一个普遍的人生真理：每一次触底，都是重生的序章。你的"中年危机"不是终点，是蜕变的开始。',
        quotes: [
          { source: '《约翰福音》12:24', text: '一粒麦子不落在地里死了，仍旧是一粒。若是死了，就结出许多子粒来。', translation: '旧的自我必须"死去"，新的可能性才能生长' },
          { source: '《哥林多后书》5:17', text: '若有人在基督里，他就是新造的人。旧事已过，都变成新的了。', translation: '重生是可能的，在任何年龄' },
          { source: '圣奥古斯丁', text: '你造我们是为了你自己，我们的心若不安息在你里面，就不得安宁。', translation: '物质成功填不满灵魂的渴望' },
          { source: '托马斯·默顿', text: '最终，最重要的不是我们做了多少事，而是我们的存在中有多少爱。', translation: '从"做"到"是"——这是中年的功课' },
        ],
      },
      dailyItinerary: [
        {
          day: 1,
          title: '启程·告别',
          location: '耶路撒冷老城',
          dawn: '清晨抵达，适应时差',
          morning: '文化探访者启程礼：在橄榄山上俯瞰耶路撒冷，写下"我要放下的三件事"。',
          afternoon: '导览耶路撒冷老城：三大文化交汇的圣地。在每个地标前停留反思。',
          evening: '第一次生命叙事工作坊：画出你的"人生曲线"——高峰与低谷。',
          soloTime: '21:00后屋顶独处，看耶路撒冷夜景',
          rituals: ['文化探访者启程礼'],
        },
        {
          day: 2,
          title: '苦路·直面',
          location: '苦路Via Dolorosa',
          dawn: '5:30 日出前出发，避开人群',
          morning: '走苦路十四站(约3小时)。每站对应一个人生阶段：出发、挫折、背叛、孤独、倒下、爬起……在第九站(耶稣第三次跌倒)停留最久。',
          afternoon: '哭墙祈祷：写一张纸条，塞进墙缝。不求生意，求内心的平静。',
          evening: '第二次生命叙事：用"英雄之旅"模型重新讲述你的人生。你现在在哪一站？',
          soloTime: '苦路行走本身是深度独处',
          rituals: ['苦路徒步', '哭墙祈祷', '生命叙事'],
        },
        {
          day: 3,
          title: '荒野·静默',
          location: '犹大荒野',
          dawn: '早起出发至犹大荒野',
          morning: '荒野独处半天：在一望无际的沙漠中独自行走。只有水壶和一个问题："下半场，我真正想活成什么样？"',
          afternoon: '荒野营地分享：与同行者讨论"荒野时刻的发现"。导师一对一辅导。',
          evening: '荒野星空下的篝火晚餐，简单但深刻。',
          soloTime: '半天荒野独处',
          rituals: [],
        },
        {
          day: 4,
          title: '死海·净化',
          location: '死海·恩戈地',
          dawn: '自然醒',
          morning: '死海漂浮冥想：在世界最低点，体验"完全放松"。恩戈地绿洲徒步。',
          afternoon: '导师工作坊：设计你的"下半场蓝图"——不是商业计划，是人生计划。',
          evening: '准备明天的重生仪式。写一封"给旧我的告别信"。',
          soloTime: '死海漂浮是天然的独处',
          rituals: [],
        },
        {
          day: 5,
          title: '重生·出发',
          location: '耶路撒冷·圣墓教堂',
          dawn: '最后的清晨冥想',
          morning: '重生仪式：在圣墓教堂点燃蜡烛，宣读"新我宣言"。打开第一天的信封，看看你放下了什么。',
          afternoon: '结业午宴。交付物：生命叙事手记+下半场蓝图+文化探访证书。',
          evening: '启程返回。带走一个答案，或者更好——带走一个更好的问题。',
          soloTime: '',
          rituals: ['重生仪式'],
        },
      ],
      mentorProfile: {
        name: '大卫·陈牧师',
        title: '耶路撒冷大学客座教授·生命叙事治疗师',
        bio: '华裔美国人，哈佛神学院毕业，在耶路撒冷生活20年。专注于帮助高成就人群(企业家/政界人士)度过"中年意义危机"。他说："我见过太多成功人士在耶路撒冷哭——那是好事，说明灵魂还活着。"',
        expertise: ['生命叙事治疗', '存在主义辅导', '灵性方向'],
        philosophy: '重生不需要教条，只需要勇气——敢于承认"旧的我已经不够了"',
      },
      transformationPath: [
        '第1天：从"不敢想"到"写出来"——把恐惧和渴望都放到纸上',
        '第2天：从"逃避"到"直面"——在苦路上走过你回避的人生阶段',
        '第3天：从"噪音"到"静默"——在荒野中听见内心的声音',
        '第4天：从"控制"到"放手"——在死海中体验完全的"无为"',
        '第5天：从"旧我"到"新我"——重生仪式不是结束，是开始',
      ],
      targetAudience: [
        '45+企业家，事业成功但感觉人生"缺少意义"',
        '刚经历重大人生变故(离婚/丧亲/大病)的企业领导者',
        '想要认真规划"人生下半场"的成功人士',
        '对基督文化感兴趣或有文化智慧背景的企业家',
      ],
      testimonials: [
        {
          name: '刘德明',
          role: '某上市公司前董事长',
          company: '退休后重新创业',
          quote: '在苦路第九站，我跪下了。不是因为文化，是因为终于允许自己承认：我累了。然后我站起来了。',
          before: '55岁，公司上市后退休，却陷入严重的"退休抑郁"，找不到存在的意义',
          after: '回来后创办了一个专门帮助退休企业家"找到下半场"的公益组织',
        },
      ],
      gallery: [
        'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800',
        'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
        'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
        'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
      ],
    },
    priceFrom: 388000,
    durationDays: 5,
    sortOrder: 40,
  },

  // ═══════════════════════════════════════════════════════════
  // #5 慈悲之旅 — 从成功到意义
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'pg-compassion',
    title: '慈悲之旅',
    subtitle: '在雪域高原遇见"比成功更大的东西"',
    description:
      '你已经证明了自己"能赚钱"。但有没有一个时刻，你想过"赚钱之外，我还能给世界什么？"。慈悲之旅带你去藏传文化的心脏——拉萨和尼泊尔蓝毗尼，在转山·供灯·与活佛对话中，找到"利他"的真正力量。不是鸡汤式的"回馈社会"，是真正体验到"给予比获取更快乐"的那个瞬间。',
    color: '#9B2335',
    icon: '🪷',
    coverUrl: 'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=1200',
    keywords: ['慈悲', '利他', '觉醒'],
    holySites: ['jokhang-temple', 'potala-palace', 'lumbini'],
    routes: [],
    rituals: [
      { name: '大昭寺朝拜', durationMin: 60, description: '跟随藏民在大昭寺转经道走三圈，体会文化智慧的"体感"' },
      { name: '酥油灯供灯', durationMin: 30, description: '在大昭寺殿内亲手点燃108盏酥油灯，每盏灯许一个"利他"的愿' },
      { name: '甘丹寺辩经', durationMin: 90, description: '观摩藏传文化辩经仪式，体会"真理越辩越明"的智慧传统' },
      { name: '纳木错湖冥想', durationMin: 60, description: '在海拔4700米的圣湖边冥想，在极致的宁静中感受"空性"' },
      { name: '活佛对话', durationMin: 60, description: '与色拉寺活佛一对一对话，讨论"财富与慈悲"的关系' },
    ],
    richContent: {
      dimension: { code: 'PG-05', label: '利他觉醒维度', kicker: '真正的富有不是拥有很多，而是需要的很少' },
      entrepreneurPainPoint: {
        title: '你有没有觉得"赚再多也不够"？',
        body: '这不是贪心，这是"意义感真空"。当物质欲望基本满足后，人的心理会从"获取模式"切换到"意义模式"。如果你没有找到"给予"的出口，这种空虚会变成无底洞。很多企业家在这个阶段疯狂消费、收藏、冒险——其实都是在填同一个洞。',
        signs: [
          '买了很多东西但很快失去兴趣',
          '对公司的增长数字感到麻木',
          '开始关注公益但不知道从何入手',
          '羡慕那些"活得简单"的人',
          '感觉自己的生命在"消耗"而不是在"贡献"',
        ],
        stage: '成熟期·巅峰期',
      },
      philosophy: {
        title: '藏传文化的答案：菩提心——为一切众生而活',
        body: '藏传文化最核心的修行不是打坐，而是"发菩提心"——为所有生命的解脱而修行。这听起来很宏大？其实它说的是一件很简单的事：当你的行动不只是为了自己，而是为了更大的东西，你会获得一种不可摧毁的力量感。',
        quotes: [
          { source: '寂天菩萨《入菩萨行论》', text: '所有世间乐，悉从利他生；一切世间苦，咸由自利起。', translation: '所有快乐来自利他，所有痛苦来自自私' },
          { source: '达赖喇嘛', text: '如果你想让别人快乐，修慈悲。如果你想让自己快乐，修慈悲。', translation: '慈悲是双赢的策略' },
          { source: '莲花生大士', text: '当铁鸟飞翔，法轮将转到西方。', translation: '古老的智慧在现代世界找到新的传播方式' },
          { source: '宗喀巴大师', text: '此生已获暇满人身，切莫空过令生义。', translation: '你这一生如此幸运，不要浪费在只为自己上' },
        ],
      },
      dailyItinerary: [
        {
          day: 1,
          title: '入藏·敬畏',
          location: '拉萨·布达拉宫',
          dawn: '适应高原(海拔3650米)',
          morning: '抵达拉萨，入住后休息适应海拔。下午参观布达拉宫，了解藏传文化的"慈悲传统"。',
          afternoon: '布达拉宫深度参访，导师讲解五世达赖建造宫殿的"利他"初衷。',
          evening: '藏餐体验+开营讨论："你认为什么是慈悲？"',
          soloTime: '早睡适应高原',
          rituals: [],
        },
        {
          day: 2,
          title: '转经·体感',
          location: '大昭寺·八廓街',
          dawn: '随藏民5:30起身',
          morning: '大昭寺朝拜：跟随藏民转经三圈。供灯108盏。观察磕长头的信众。',
          afternoon: '甘丹寺辩经观摩。与年轻僧人交流他们的"人生选择"。',
          evening: '讨论："这些人放弃了世俗成功，他们失去了什么？又得到了什么？"',
          soloTime: '转经道上的行走冥想',
          rituals: ['大昭寺朝拜', '酥油灯供灯', '甘丹寺辩经'],
        },
        {
          day: 3,
          title: '圣湖·空性',
          location: '纳木错',
          dawn: '出发前往纳木错(约4小时车程)',
          morning: '沿途经过念青唐古拉山，在那根拉山口(5190米)短暂停留。',
          afternoon: '纳木错湖边冥想：在海拔4700米的圣湖边静坐一小时。只有天空、湖水和你。',
          evening: '纳木错湖边帐篷过夜(条件许可时)。星空下讨论"空性与商业"。',
          soloTime: '湖边冥想即深度独处',
          rituals: ['纳木错湖冥想'],
        },
        {
          day: 4,
          title: '对话·答案',
          location: '色拉寺',
          dawn: '返回拉萨',
          morning: '色拉寺活佛对话：一对一60分钟，主题"财富是工具还是牢笼"。',
          afternoon: '慈悲行动计划工作坊：设计你的"利他项目"——不是捐钱，是用你的能力和资源做真正有意义的事。',
          evening: '结营仪式：每人分享"我带走的一句话"。颁发文化探访证书。',
          soloTime: '活佛对话后的独处消化时间',
          rituals: ['活佛对话'],
        },
      ],
      mentorProfile: {
        name: '丹增嘉措格西',
        title: '色拉寺高级讲师·跨文化对话推动者',
        bio: '藏族，在色拉寺学习18年获格西学位(相当于佛学博士)。曾赴美国哈佛大学做访问学者，精通藏、中、英三语。专注于帮助"成功人士"找到物质之外的精神坐标。',
        expertise: ['菩提心修行', '跨文化灵性对话', '慈悲商业'],
        philosophy: '慈悲不是软弱，是最强大的商业策略——因为它创造真正的信任',
      },
      transformationPath: [
        '第1天：从"游客心态"到"文化探访者心态"——用敬畏的眼光看世界',
        '第2天：从"了解慈悲"到"体感慈悲"——在转经和供灯中感受',
        '第3天：从"满"到"空"——在圣湖边体验"无"的力量',
        '第4天：从"想"到"做"——把慈悲转化为具体的行动计划',
        '第30天：慈悲行动计划第一步执行回顾',
      ],
      targetAudience: [
        '物质充裕但灵魂空虚的成功企业家',
        '想要从"做慈善"升级为"有战略的公益"的企业家',
        '对藏传文化感兴趣的领导者',
        '正在考虑"企业社会责任"战略的CEO',
      ],
      testimonials: [
        {
          name: '赵晓峰',
          role: '某地产集团创始人',
          company: '上海·年营收30亿',
          quote: '活佛问我："你建了多少房子？"我说几万套。他说："有多少是你真的关心住在里面的人？"那一刻我被击中了。',
          before: '地产行业下行，对行业和自己的选择产生深度怀疑',
          after: '启动了"长者友好社区"项目，用利润的10%建设养老配套。他说这是他做过最有成就感的事',
        },
      ],
      gallery: [
        'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=800',
        'https://images.unsplash.com/photo-1461863109726-246fa9598dc3?w=800',
        'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800',
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
      ],
    },
    priceFrom: 328000,
    durationDays: 4,
    sortOrder: 50,
  },

  // ═══════════════════════════════════════════════════════════
  // #6 传灯之旅 — 企业家精神遗产
  // ═══════════════════════════════════════════════════════════
  {
    slug: 'pg-legacy',
    title: '传灯之旅',
    subtitle: '把一生的智慧凝练为可传承的精神遗产',
    description:
      '50+岁的企业家，开始想一个问题："我走之后，留下什么？"不是公司和财产——这些律师能搞定。是你的精神、价值观、人生智慧——这些才是真正的遗产。传灯之旅在曹溪南华寺·少林·终南山，通过传灯法会、立遗嘱仪式、导师认证，帮你把一生凝练为"一盏灯"。',
    color: '#C49B3C',
    icon: '🏮',
    coverUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200',
    keywords: ['传承', '遗产', '传灯'],
    holySites: ['nanhua-temple', 'shaolin-temple', 'zhongnan-mountain'],
    routes: [],
    rituals: [
      { name: '传灯法会', durationMin: 60, description: '手持莲花灯，在南华寺传灯——灯灯相续，薪火不灭' },
      { name: '立遗嘱仪式', durationMin: 120, description: '不是法律遗嘱，是"精神遗嘱"——写下你最想传给下一代的三个信念' },
      { name: '六祖坛前发愿', durationMin: 30, description: '在六祖慧能真身前发大愿——"我此生最终要完成什么"' },
      { name: '终南隐修', durationMin: 240, description: '终南山独居草庐半天，体验"大隐隐于市"的终极简朴' },
      { name: '口述历史', durationMin: 90, description: '导师引导你录制90分钟"口述历史"——你的人生故事，留给未来的人' },
    ],
    richContent: {
      dimension: { code: 'PG-06', label: '智慧传承维度', kicker: '最好的遗产不是财富，是让后人知道你为什么活' },
      entrepreneurPainPoint: {
        title: '你想过"走后留下什么"吗？',
        body: '华人企业家有个普遍焦虑：一代创业、二代守业、三代败业。为什么？因为传下去的只有钱和股份，没有传下去"为什么要做这件事"的精神。企业家精神遗产=价值观+人生智慧+失败教训+做人准则。这些东西不写下来，就会随你消失。',
        signs: [
          '开始频繁想"如果我明天不在了"',
          '发现二代对公司没有你当年的热情',
          '同龄的企业家朋友开始"出事"——健康、婚姻、传承',
          '想写自传但不知道从何下笔',
          '参加了很多财富传承讲座，但感觉"不是那个东西"',
        ],
        stage: '巅峰期',
      },
      philosophy: {
        title: '禅宗的答案：传灯——一灯能除千年暗',
        body: '六祖慧能是中国禅宗最重要的传承者。他不识字，却留下了《六祖坛经》；他一生没有建过大寺，却让禅宗照亮了整个东亚。传灯的意义不在于"灯"有多亮，而在于"传"——你的光亮能不能点亮别人。企业家的传灯，就是把你一生的"活法"变成后人的"灯塔"。',
        quotes: [
          { source: '《六祖坛经》', text: '一灯能除千年暗，一智能灭万年愚。', translation: '一个人的智慧可以照亮无数后人' },
          { source: '《传灯录》', text: '灯灯相续，光光无尽。', translation: '传承的本质是让光明永不断绝' },
          { source: '五祖弘忍', text: '不识本心，学法无益。', translation: '传给后人的首先是"认识自己"的能力' },
          { source: '曹溪禅训', text: '落叶归根，根深则叶茂。', translation: '回归本源，才能滋养后世' },
        ],
      },
      dailyItinerary: [
        {
          day: 1,
          title: '归根·曹溪',
          location: '韶关南华寺',
          dawn: '抵达曹溪祖庭',
          morning: '参访六祖慧能真身殿，了解一个"文盲"如何成为中国最有影响力的思想家。住持讲"传灯"的真意。',
          afternoon: '第一次口述历史：导师引导你讲述"人生的第一个关键转折"。全程录音录像。',
          evening: '六祖坛前发愿：用三句话说出"我此生最终要完成什么"。',
          soloTime: '发愿后的独处时间',
          rituals: ['六祖坛前发愿', '口述历史'],
        },
        {
          day: 2,
          title: '凝练·少林',
          location: '嵩山少林寺',
          dawn: '转场至少林寺',
          morning: '少林寺塔林——1500年来历代高僧的"遗产"就刻在这些石塔上。导师讲"什么值得被记住"。',
          afternoon: '精神遗嘱工作坊(上)：列出"我一生学到的10个最重要的道理"。筛选到3个。逐个深度展开。',
          evening: '与同行者分享各自的"精神遗嘱"草稿。互相提问和完善。',
          soloTime: '工作坊间隙有独立思考时间',
          rituals: ['立遗嘱仪式'],
        },
        {
          day: 3,
          title: '隐修·终南',
          location: '终南山',
          dawn: '清晨出发至终南山',
          morning: '拜访终南山隐士(现代仍有5000+隐士在此修行)。了解"放下一切"是什么感觉。',
          afternoon: '终南隐修体验：在草庐中独居4小时。只有笔和纸。任务：完成精神遗嘱终稿。',
          evening: '山中素斋。讨论"隐与显"——什么时候该退到幕后。',
          soloTime: '4小时草庐独处',
          rituals: ['终南隐修'],
        },
        {
          day: 4,
          title: '口述·录制',
          location: '终南山·专业录制',
          dawn: '最后的山间晨练',
          morning: '第二次口述历史(完整版90分钟)：从出生到现在，你的人生故事。专业录像团队记录。',
          afternoon: '精神遗嘱定稿：手写+签名+封蜡。两份——一份自己保存，一份留在南华寺。',
          evening: '准备明天的传灯仪式。写给最重要的人的一封信。',
          soloTime: '写信是最深的独处',
          rituals: ['口述历史'],
        },
        {
          day: 5,
          title: '传灯·永续',
          location: '南华寺',
          dawn: '返回南华寺',
          morning: '传灯法会：每人手持莲花灯，从六祖殿传出，灯灯相续。在仪式中宣读精神遗嘱核心句。',
          afternoon: '结业仪式。交付物：口述历史视频+精神遗嘱(手写原件)+传灯者证书+人生智慧小册子(导师整理)。',
          evening: '返程。你带走的不是纪念品，是一盏点亮的灯。',
          soloTime: '',
          rituals: ['传灯法会'],
        },
      ],
      mentorProfile: {
        name: '明觉法师',
        title: '南华寺首座·企业家精神导师',
        bio: '曹溪南华寺首座(第二把手)。出家前是企业法律顾问，40岁出家。20年禅修功底，专门接待"想要传承精神遗产"的企业家。他说："大部分企业家只忙着给后人留钱，忘了最重要的是留一盏灯。"',
        expertise: ['禅宗传灯', '精神遗嘱', '人生回顾引导'],
        philosophy: '你不需要完美的一生才能传灯——真实的、有错误的、有反思的一生才最照亮人',
      },
      transformationPath: [
        '第1天：从"不敢想"到"开始想"——在祖庭中感受传承的力量',
        '第2天：从"模糊"到"清晰"——凝练你一生的核心智慧',
        '第3天：从"热闹"到"安静"——在隐修中完成精神遗嘱',
        '第4天：从"心里想"到"说出来"——口述历史让遗产有了形态',
        '第5天：从"个人"到"传承"——传灯法会让一盏灯变成永不熄灭的火',
      ],
      targetAudience: [
        '50+企业家，开始认真考虑"传承"问题',
        '创一代担心"富不过三代"的家族企业主',
        '想要留下"不只是钱"的遗产的企业家',
        '正在考虑退休或交班的成功人士',
      ],
      testimonials: [
        {
          name: '林志远',
          role: '某家族企业第一代创始人',
          company: '福建·三代同堂',
          quote: '传灯法会那晚，我儿子看了我写的精神遗嘱哭了。他说从来不知道爸爸创业时吃过那么多苦。那一刻，我知道这趟来对了。',
          before: '73岁，公司交给了儿子，但儿子总说"我不是你"',
          after: '精神遗嘱被儿子裱起来挂在办公室。两代人的关系改善了，因为儿子终于"懂了爸爸"',
        },
      ],
      gallery: [
        'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800',
        'https://images.unsplash.com/photo-1476611317561-60117649dd94?w=800',
        'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=800',
        'https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=800',
      ],
    },
    priceFrom: 388000,
    durationDays: 5,
    sortOrder: 60,
  },
];

async function seedPersonalGrowth() {
  console.log('🧘 Seeding personal-growth themes...');

  for (const theme of PERSONAL_THEMES) {
    await prisma.teamCultureTheme.upsert({
      where: { slug: theme.slug },
      update: {
        title: theme.title,
        subtitle: theme.subtitle,
        description: theme.description,
        color: theme.color,
        icon: theme.icon,
        coverUrl: theme.coverUrl,
        keywords: theme.keywords,
        holySites: theme.holySites,
        routes: theme.routes,
        rituals: theme.rituals as never,
        richContent: theme.richContent as never,
        priceFrom: theme.priceFrom,
        durationDays: theme.durationDays,
        sortOrder: theme.sortOrder,
        category: 'PERSONAL',
        isPublished: true,
      },
      create: {
        slug: theme.slug,
        title: theme.title,
        subtitle: theme.subtitle,
        description: theme.description,
        color: theme.color,
        icon: theme.icon,
        coverUrl: theme.coverUrl,
        keywords: theme.keywords,
        holySites: theme.holySites,
        routes: theme.routes,
        rituals: theme.rituals as never,
        richContent: theme.richContent as never,
        priceFrom: theme.priceFrom,
        durationDays: theme.durationDays,
        sortOrder: theme.sortOrder,
        category: 'PERSONAL',
        isPublished: true,
      },
    });
    console.log(`  ✅ ${theme.title} (${theme.slug})`);
  }

  console.log(`🧘 Personal growth: ${PERSONAL_THEMES.length} themes seeded`);
}

// 支持独立执行和被导入调用
if (require.main === module) {
  seedPersonalGrowth()
    .then(() => prisma.$disconnect())
    .catch((e) => {
      console.error(e);
      prisma.$disconnect();
      process.exit(1);
    });
}

export { seedPersonalGrowth };
