export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/holy-sites/index',
    'pages/routes/index',
    'pages/route-detail/index',
    'pages/temples/index',
    'pages/patriarchs/index',
    'pages/teachings/index',
    'pages/seals/index',
    'pages/profile/index',
    'pages/religion-detail/index',
    'pages/holy-site-detail/index',
    'pages/temple-detail/index',
    'pages/patriarch-detail/index',
    'pages/seal-detail/index',
    'pages/teaching-detail/index',
    'pages/chat/index',
    'pages/trips/index',
    'pages/trip-detail/index',
    'pages/journals/index',
    'pages/journal-create/index',
    'pages/journal-detail/index',
    'pages/map/index',
    'pages/search/index',
    'pages/orders/index',
    'pages/notifications/index',
    'pages/checkout/index',
    'pages/collections/index',
    'pages/collection-detail/index',
    'pages/write-review/index',
    'pages/community/index',
    'pages/guide-detail/index',
    'pages/question-detail/index',
    'pages/coupons/index',
    'pages/promotions/index',
    'pages/membership/index',
    'pages/points-mall/index',
    'pages/packages/index',
    'pages/package-detail/index',
    'pages/prices/index',
    'pages/price-calendar/index',
    'pages/merchants/index',
    'pages/merchant-detail/index',
    'pages/messages/index',
    'pages/chat-room/index',
    'pages/religions/index',
    'pages/guides/index',
    'pages/price-compare/index',
    'pages/price-trend/index',
    'pages/price-alerts/index',
    'pages/leaderboard/index',
    'pages/photos/index',
    'pages/referral/index',
    'pages/about/index',
    'pages/privacy/index',
    'pages/terms/index',
    'pages/team-culture/index',
    'pages/cultivation/index',
    'pages/cultivation/apply'
  ],
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#0066FF',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png'
      },
      {
        pagePath: 'pages/holy-sites/index',
        text: '目的地',
        iconPath: 'assets/tab-map.png',
        selectedIconPath: 'assets/tab-map-active.png'
      },
      {
        pagePath: 'pages/seals/index',
        text: '体验',
        iconPath: 'assets/tab-seal.png',
        selectedIconPath: 'assets/tab-seal-active.png'
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tab-profile.png',
        selectedIconPath: 'assets/tab-profile-active.png'
      }
    ]
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTitleText: '佳绩之旅',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F5F5F5'
  }
})
